### ISSUE TITLE
Zimuku KeyError

### ISSUE THREAD

**Issue by yimingzhaomath** [morpheus65535/bazarr#1415] opened 2021-05-24 15:41 UTC
**Describe the bug**
There are two issues. Not sure if it's related.

1. The provider Zimuku seems to be broken again. When I manually search for a subtitle, I can find the subtitle in the list. But after I click the download icon, the provider just returns a "KeyError".  This happens for every show that I am requesting subtitles for. As an example: Young.Sheldon.S04E01.Graduation.1080p.AMZN.WEBRip.DDP5.1.x264-TOMMY[rarbg].mkv

2. For some shows, Zimuku returns no subtitle. But a search on the provider's website reveals there are exact matches.

**To Reproduce**
I am attaching both logs.

For 1: 
[For issue 1.log](https://github.com/morpheus65535/bazarr/files/6533455/For.issue.1.log)

For 2:
[For issue 2.log](https://github.com/morpheus65535/bazarr/files/6533519/For.issue.2.log)
Note that I searched for The.Resident.S04E10.1080p.WEB.H264-CAKES[rarbg].mkv. 

Here is a screenshot from Zimuku's website
<img width="1369" alt="Screen Shot 2021-05-24 at 11 40 25 AM" src="https://user-images.githubusercontent.com/13087183/119371899-d75f8b00-bc84-11eb-82e8-7ca86dc59865.png">

**Software (please complete the following information):**
 - Bazarr: 0.9.5
 - Radarr version 3.2.0.5048
 - Sonarr version 3.0.6.1196
 - OS: Linux-4.15.0-126-generic-x86_64-with-Ubuntu-18.04-bionic

**Comment by morpheus65535** [comment] 2021-05-29 02:50
@zx900930 any chance you could look into this one? Thanks!

**Comment by zx900930** [comment] 2021-05-29 07:25
@morpheus65535 The problem is the website changed its domain name from http://www.zimuku.la -> http://zimuku.org/
the fix was change urls in the zimuku.py
```
    server_url = "http://www.zimuku.la"
    search_url = "/search?q={}"
    download_url = "http://www.zimuku.la/"
```
to
```
    server_url = "http://zimuku.org"
    search_url = "/search?q={}"
    download_url = "http://zimuku.org/"
```

**Comment by morpheus65535** [comment] 2021-05-29 12:25
@zx900930 are you able to create a PR?

**Comment by zx900930** [comment] 2021-05-29 15:19
For the no result issues, plz attach a full log so I can find out the exact cause of the problem.

**Comment by yimingzhaomath** [comment] 2021-05-29 16:07
@zx900930 I attached the full log here, for the "no result" issue. Thanks.

[For.issue.2.log](https://github.com/morpheus65535/bazarr/files/6564950/For.issue.2.log)

**Comment by morpheus65535** [comment] 2021-06-11 23:45
@zx900930 is there something else to fix here? @yimingzhaomath may I close this issue or not?

**Comment by morpheus65535** [comment] 2021-06-24 01:44
No news, good news.

**Closed by morpheus65535** 2021-06-24 01:44 UTC
Labels: help wanted
