### ISSUE TITLE
Setting dialog appearing

### ISSUE THREAD

**Issue by shifoc** [morpheus65535/bazarr#1702] opened 2022-01-30 00:01 UTC
**Describe the bug**
I get this dialog even if I didn't change anything in the settings

**To Reproduce**
1. Go to a setting page
2. try to go to another page

**Expected behavior**
Get the dialogue when something changed

**Screenshots**
![image](https://user-images.githubusercontent.com/32818143/151681627-467058a7-9238-48a6-87c7-fb57761eb6f0.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.3-beta.21
 - OS: Windows 10

**Comment by morpheus65535** [comment] 2022-01-30 13:19
I can't reproduce this one. What browser are you using?

**Comment by shifoc** [comment] 2022-01-30 14:42
chrome

**Comment by morpheus65535** [comment] 2022-01-30 14:45
Same as me. Does it do the same in Incognito mode? Can you show us your dev console?

**Comment by shifoc** [comment] 2022-01-30 14:59
no, it does not do the same on incognito mode.
![image](https://user-images.githubusercontent.com/32818143/151704995-a9c788dc-03be-4985-81d9-1463898ac6b8.png)
is this what you mean by dev console?

**Comment by morpheus65535** [comment] 2022-01-30 16:07
You probably have some Chrome addon that is causing this issue then.

**Comment by morpheus65535** [comment] 2022-02-01 11:40
Anything else you can tell us about your browser extensions? Without that, theres not much we can do to help.

**Comment by shifoc** [comment] 2022-02-01 16:14
I disabled all the extensions and it still happened! On chrome and Firefox.

**Comment by morpheus65535** [comment] 2022-02-01 16:17
If it doesn't appear in Incognito mode, it means that something is preventing it from working as expected in your normal browsing session. Did you try from another computer or your phone maybe?

**Comment by shifoc** [comment] 2022-02-01 16:26
I just tried it from my phone and I do not have the same issue there

**Comment by morpheus65535** [comment] 2022-02-01 16:51
So the issue is with your computer. If it would ahve been on a single browser, I would have suggest to empty the cache but with multiple browsers... starnge... maybe some security software installed.

**Comment by shifoc** [comment] 2022-02-03 22:06
I paused my antivirus and still have the same issue. it seems the issue is not from your side so I will live with it, thanks. I don't know if you want me to close the issue so feel free to do so!

**Comment by morpheus65535** [comment] 2022-02-03 22:20
I will close it but if you find the issue and are able to reproduce it, don't hesitate to reopen it. Thanks!

**Closed by morpheus65535** 2022-02-03 22:20 UTC
Labels: awaiting feedback, cannot reproduce
