### ISSUE TITLE
Failed installation Ubuntu (24.04)

### ISSUE THREAD

**Issue by DannyJanmaat** [morpheus65535/bazarr#2503] opened 2024-05-23 20:35 UTC
Failed installation Bazarr on Ubuntu 24.04 LXC/VM.

Followed instructions on 'https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/#ubuntu-debian-install-requirements-with'.
Problem : 'python3-distutils' deprecated. Replaced by 'setuptools'. https://docs.python.org/3.10/library/distutils.html

Software : Proxmox 8.2.2, LXC/VM Ubuntu 24.04.

**Comment by morpheus65535** [comment] 2024-05-23 22:09
Provide full installation log. Only the final error message doesn't help.

**Comment by DannyJanmaat** [comment] 2024-05-23 23:43
Hey Morpheus65535,

Try install the software via the provided instructions and you immediatelly see what I mean. The instructions for Ubuntu simply don't work because of the deprecated Python3-distutils. I hope you can update the instructions soon so we can get it working again on Ubuntu :).

**Comment by morpheus65535** [comment] 2024-05-28 02:41
Have you tried installing `setuptools` which is supposed to include `distutils`?

`apt-get install python3-setuptools`

**Comment by DannyJanmaat** [comment] 2024-05-28 08:00
Hey hello,

I'm trying to get this work. Via setupstools it won't work because in utils.py script it depends on importing a lost functionality the looseversion. I already solved that problem.

I guess I have it working already but I use now a python venv within LXC what simply don't work. I will have to verify if I can get it working by excluding venv.

I have in the coming days time to dug in and let you know the solution.


________________________________

**Comment by morpheus65535** [comment] 2024-05-28 10:19
Let me know! I don't have a environment to test it so your input is welcome.

**Comment by carrow8993** [comment] 2024-06-23 21:28
I ran into the same issue trying to test the current dev environment under Ubuntu 24.04. The setuptools package provided through apt is only on version 68.1.2, a later version is needed to run properly/respect distutils import. I was able to resolve the issue by forcing my venv to update to the latest setuptools (70.1.0).

As far as I can tell, until apt gets the update, Ubuntu 24.04 hosts will either have to host their install through a venv or use pip's --break-system-packages flag to update the system env's version, with the risk of breaking system packages.

**Comment by GoldenCracker97** [comment] 2024-07-19 16:44
Thought I'd chime in on my Ubuntu 24.04 install. Identical issue to DannyJanmaat. (my first github bug report, cheers)

**Comment by morpheus65535** [comment] 2024-08-06 03:15
Is @carrow8993 fix your issue @DannyJanmaat ?

**Comment by MaZchen** [comment] 2024-08-18 18:38
> Thought I'd chime in on my Ubuntu 24.04 install. Identical issue to DannyJanmaat. (my first github bug report, cheers)

same here....

`python3-setuptools is already the newest version (68.1.2-2ubuntu1)`

Following the instructions on https://wiki.bazarr.media/Getting-Started/Installation/Linux/linux/

`/opt/bazarr$ python3 bazarr.py
Python version greater than 3.11.x is unsupported. Current version is 3.12.3. Keep in mind that even if it works, you're on your own.
Bazarr starting child process with PID 628794...
/opt/bazarr/bazarr/../custom_libs/subzero/language.py:165: SyntaxWarning: invalid escape sequence '\.'
  IETF_MATCH = ".+\.([^-.]+)(?:-[A-Za-z]+)?$"
/opt/bazarr/bazarr/../custom_libs/subzero/language.py:166: SyntaxWarning: invalid escape sequence '\.'
  ENDSWITH_LANGUAGECODE_RE = re.compile("\.([^-.]{2,3})(?:-[A-Za-z]{2,})?$")
/opt/bazarr/bazarr/../custom_libs/subzero/language.py:170: SyntaxWarning: invalid escape sequence '\.'
  language_match = re.match(".+\.([^\.]+)$" if not ietf
2024-08-18 20:34:04,895 - root                             (7a5298895080) :  ERROR (check_update:174) - BAZARR unable to unzip release
Traceback (most recent call last):
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/bazarr/bazarr/main.py", line 51, in <module>
    migrate_db(app)
  File "/opt/bazarr/bazarr/app/database.py", line 327, in migrate_db
    flask_migrate.upgrade(directory=migrations_directory)
  File "/opt/bazarr/bazarr/../libs/flask_migrate/__init__.py", line 111, in wrapped
    f(*args, **kwargs)
  File "/opt/bazarr/bazarr/../libs/flask_migrate/__init__.py", line 200, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/bazarr/bazarr/../libs/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/opt/bazarr/bazarr/../libs/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/opt/bazarr/bazarr/../libs/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../libs/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/bazarr/migrations/env.py", line 117, in <module>
    run_migrations_online()
  File "/opt/bazarr/migrations/env.py", line 106, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/bazarr/bazarr/../libs/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/bazarr/bazarr/../libs/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/opt/bazarr/migrations/versions/1e38aa77a491_.py", line 31, in upgrade
    with op.batch_alter_table('table_history', schema=None) as batch_op:
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/opt/bazarr/bazarr/../libs/alembic/operations/base.py", line 398, in batch_alter_table
    impl.flush()
  File "/opt/bazarr/bazarr/../libs/alembic/operations/batch.py", line 164, in flush
    batch_impl._create(self.impl)
  File "/opt/bazarr/bazarr/../libs/alembic/operations/batch.py", line 448, in _create
    op_impl.create_table(self.new_table)
  File "/opt/bazarr/bazarr/../libs/alembic/ddl/impl.py", line 366, in create_table
    self._exec(schema.CreateTable(table))
  File "/opt/bazarr/bazarr/../libs/alembic/ddl/impl.py", line 207, in _exec
    return conn.execute(construct, multiparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1408, in execute
    return meth(
           ^^^^^
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
    return connection._execute_ddl(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1519, in _execute_ddl
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1839, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1979, in _exec_single_context
    self._handle_dbapi_exception(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2335, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1960, in _exec_single_context
    self.dialect.do_execute(
  File "/opt/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL:
CREATE TABLE _alembic_tmp_table_history (
        id INTEGER NOT NULL,
        action INTEGER NOT NULL,
        description TEXT NOT NULL,
        language TEXT,
        provider TEXT,
        score INTEGER,
        "sonarrEpisodeId" INTEGER,
        "sonarrSeriesId" INTEGER,
        subs_id TEXT,
        subtitles_path TEXT,
        timestamp DATETIME NOT NULL,
        video_path TEXT,
        matched TEXT,
        not_matched TEXT,
        "upgradedFromId" INTEGER,
        PRIMARY KEY (id),
        CONSTRAINT "fk_history_upgradedFromId_id" FOREIGN KEY("upgradedFromId") REFERENCES table_history (id),
        FOREIGN KEY("sonarrSeriesId") REFERENCES table_shows ("sonarrSeriesId") ON DELETE CASCADE,
        FOREIGN KEY("sonarrEpisodeId") REFERENCES table_episodes ("sonarrEpisodeId") ON DELETE CASCADE
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
`

**Comment by DannyJanmaat** [comment] 2024-08-18 19:01
I didn't had time to solve this, I hope the creator of this tool get this working again. You can temp get this working by using a earlier python version in a venv environment.

**Comment by MaZchen** [comment] 2024-08-18 19:04
> I didn't had time to solve this, I hope the creator of this tool get this working again. You can temp get this working by using a earlier python version in a venv environment.

thanks. Unfortunately I am not that familiar with Linux. I tried to follow the instructions given in this issue and related ones, but without success.... I think to remember I had read in a related issue that almost 50% seem so run fine in Python 3.12, just don't see how.

**Comment by DannyJanmaat** [comment] 2024-08-18 21:39
DistUtils is deprecated; that's why you need to use the older version for direct result.

Else you have to install a 3th party Setuptools for it to work. I had it working, except I ran it from a LXC (Proxmox) and it don't have direct full support for virtual environments.

I have a vacation coming, maybe I will have time for this

**Comment by morpheus65535** [comment] 2024-08-29 18:33
Ok so I've deployed an Ubuntu 24.04 virtual machine, followed the wiki with some adaptations:
1. Requirements installation: `apt-get install 7zip python3-dev python3-pip **python3-setuptools** unrar unzip`
2. Before step 6, I had to disable EXTERNALLY-MANAGED flag introduced in newer distros: `mv /usr/lib/python3.12/EXTERNALLY-MANAGED /usr/lib/python3.12/EXTERNALLY-MANAGED.bkp`

Once you start Bazarr 1.4.3, you can see some SyntaxWarning caused by outdated REGEX string that are fixed in upcoming 1.4.4.

Globally, it's working perfectly fine if you install `python3-setuptools`. Regarding EXTERNALLY-MANAGED flag, you can also use venv to prevent having to disable this globally.

I don't see anything to fix in Bazarr but I'll add mentions to the wiki about those 2 adaptations.

Thanks for reporting.

**Closed by morpheus65535** 2024-08-29 18:33 UTC
Labels: awaiting feedback

**Comment by MaZchen** [comment] 2024-08-31 08:52
> Ok so I've deployed an Ubuntu 24.04 virtual machine, followed the wiki with some adaptations:

works! Thanks a million!
