### ISSUE TITLE
Provider LegendasDivx not working

### ISSUE THREAD

**Issue by n0pe0n** [morpheus65535/bazarr#1044] opened 2020-08-02 15:00 UTC
Describe the bug
[LegendasDivx ](https://www.legendasdivx.pt)is not working, it keeps calling an error.

To Reproduce

Enable LegedasDivx as a provider'
Search for subtitles
Expected behavior
Subtitles download

Screenshots
![123](https://user-images.githubusercontent.com/20689862/88807015-1332dc80-d1a9-11ea-81d6-e15aaf99d32a.png)

Throttling legendasdivx for 20 minutes, until 20/08/02 13:29, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'

Software (please complete the following information):

Bazarr: [0.9.0.1]
Radarr version [0.2.0.1504]
Sonarr version [3.0.3.904]
OS: [Linux-4.15.0-112-generic-x86_64-with]
Python Version: [3.8.5]

**Comment by halali** [comment] 2020-08-02 19:04
Provide debug log

**Comment by n0pe0n** [comment] 2020-08-02 20:55
`     |Throttling legendastv for 10 minutes, until 20/08/02 09:23, because of: HTTPError. Exception info: '404 Client Error: Not Found for url: http://legendas.tv/notfound'|
02/08/2020 09:23:58|INFO    |root                            |Using legendastv again after 10 minutes, (disabled because: HTTPError)|
02/08/2020 09:39:02|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 09:39:07|INFO    |root                            |BAZARR Finished searching for missing Subtitles. Check History for more information.|
02/08/2020 11:36:37|WARNING |retry.api                       |HTTPSConnectionPool(host='www.legendasdivx.pt', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
02/08/2020 11:38:58|INFO    |root                            |BAZARR your login credentials have been migrated successfully and your password is now equal to your username. Please change it as soon as possible in settings.|
02/08/2020 11:39:00|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
02/08/2020 11:40:11|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
02/08/2020 11:43:37|INFO    |root                            |Bazarr is being restarted...|
02/08/2020 11:43:46|INFO    |root                            |BAZARR is started and waiting for request on http://0.***.***.***:6767/|
02/08/2020 11:51:59|ERROR   |root                            |BAZARR subtitles file doesn't seems to be text based. Skipping this file: /mnt/remote/Media/Movies/Concerts/Guns N' Roses - Live at the Ritz (1988)/Guns N' Roses - Live at the Ritz (1988).sub|'Traceback (most recent call last):\n  File "/app/bazarr/list_subtitles.py", line 379, in guess_external_subtitles\n    text = text.decode(guess["encoding"])\nTypeError: decode() argument \'encoding\' must be str, not None'|
02/08/2020 11:52:15|INFO    |root                            |Provider legendasdivx throttle count 1 of 5, waiting 5sec and trying again|
02/08/2020 11:52:22|WARNING |retry.api                       |('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), retrying in 5 seconds...|
02/08/2020 11:52:22|INFO    |root                            |Provider legendasdivx throttle count 2 of 5, waiting 5sec and trying again|
02/08/2020 11:52:24|INFO    |root                            |Provider legendasdivx throttle count 3 of 5, waiting 5sec and trying again|
02/08/2020 11:52:29|ERROR   |root                            |BAZARR subtitles file doesn't seems to be text based. Skipping this file: /mnt/remote/Media/Movies/Concerts/Guns N' Roses - Live at the Ritz (1988)/Guns N' Roses - Live at the Ritz (1988).sub|'Traceback (most recent call last):\n  File "/app/bazarr/list_subtitles.py", line 379, in guess_external_subtitles\n    text = text.decode(guess["encoding"])\nTypeError: decode() argument \'encoding\' must be str, not None'|
02/08/2020 11:52:31|INFO    |root                            |Provider legendasdivx throttle count 4 of 5, waiting 5sec and trying again|
02/08/2020 11:52:32|INFO    |root                            |Throttling legendasdivx for 20 minutes, until 20/08/02 12:12, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'|
02/08/2020 11:52:35|INFO    |root                            |Throttling legendasdivx for 20 minutes, until 20/08/02 12:12, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'|
02/08/2020 11:54:03|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 11:55:10|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 11:56:33|WARNING |apscheduler.scheduler           |Execution of job "Update Movie list from Radarr (trigger: interval[0:05:00], next run at: 2020-08-02 11:56:33 CEST)" skipped: maximum number of running instances reached (1)|
02/08/2020 11:56:42|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 11:58:31|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 11:59:52|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:00:52|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:01:54|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:02:31|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:02:44|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:03:12|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:03:28|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:03:38|INFO    |root                            |BAZARR throttled providers have been reset.|
02/08/2020 12:03:51|INFO    |apprise.URLBase                 |Sent Discord notification.|
02/08/2020 12:03:55|INFO    |root                            |Throttling legendasdivx for 20 minutes, until 20/08/02 12:23, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'|
02/08/2020 12:03:58|INFO    |root                            |Throttling legendasdivx for 20 minutes, until 20/08/02 12:23, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'|
02/08/2020 12:03:59|INFO    |root                            |Throttling legendasdivx for 20 minutes, until 20/08/02 12:23, because of: ServiceUnavailable. Exception info: 'LegendasDivx.pt :: Uncaught error: %r'|`

**Comment by morpheus65535** [comment] 2020-08-03 01:51
Duplicate of #1040

**Closed by morpheus65535** 2020-08-03 01:51 UTC
Labels: duplicate
