### ISSUE TITLE
[Bug] Erratic subtitle download behaviour

### ISSUE THREAD

**Issue by markhaines** [morpheus65535/bazarr#213] opened 2018-11-04 19:25 UTC
Am getting weird behaviour with Bazarr. The log file gets spammed every 5mins with the following error:

**Message**
Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-11-04 19:22:17 GMT)" raised an exception

**Exception**
Traceback (most recent call last):
 File "/app/bazarr/libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/get_movies.py", line 118, in update_movies
  store_subtitles_movie(path_replace_movie(added_path[0]))
TypeError: \NoneType\ object has no attribute \__getitem__\

But occassionaly, at random intervals (maybe once a day - but not at the same time each day) it will magically spring into life an pull down anywhere between 10 - 50 odd subtitles (there are 700+ in the wanted queue), before breaking again.

If I try and do a manual forced download of a single movie's subtitles this works fine.  If I kick off a full sweep of the wanted list the prgram appears to crash (webUI becomes unresponsive for a while).

As it works sometimes but not others, and there isn't anything that I can decipher in the logs am not sure what to try next.

**Software (please complete the following information):**
 - Bazarr: v0.6.6.3
 - Radarr version v0.2.0.1120
 - Sonarr - not enabled.
 - OS: Docker on DSM 6.2

**Additional context**
Screenshot below.

<img width="720" alt="system_-_bazarr" src="https://user-images.githubusercontent.com/1022008/47968636-b7373480-e064-11e8-96be-4cdb76cb0f57.png">

**Comment by morpheus65535** [comment] 2018-11-05 03:30
I've just pushed a fix that involve more logging for this issue. Could you please test it and report back? Thanks!

**Comment by morpheus65535** [comment] 2018-11-05 11:34
I cannot reproduce your issue so I'm running blind here. Your issue is (probably) related to a movies in Radarr for which the API return an empty string for path. Ultimately, you're going to have it fixed but I try to add logging so we could determine what movies is in problem.

Can you try our development image until we fix this? linuxserver/bazarr:development

Thanks!

**Comment by markhaines** [comment] 2018-11-05 11:36
Ah, you think it might be a specific movie title within a folder that's causing the issue?  I have a second, separate instance of Radarr running I use solely for 4k titles - will point it at that and see what happens.  Will flip to dev branch as well.

Cheers

**Comment by markhaines** [comment] 2018-11-05 12:01
Weirdly I don't seem to be able to setup a second instance at the moment as there's an error with populating the language list; instead of getting the language / country name I just see the 2 character abbreviation and it won't let me add more than one, and doesn't seem to save whatever I select anyway.

<img width="620" alt="settings_-_bazarr" src="https://user-images.githubusercontent.com/1022008/47997035-69690d80-e0f2-11e8-9afe-254276e01c6c.png">

**Comment by morpheus65535** [comment] 2018-11-05 12:08
@halali will fix this language issue ASAP but you'll have to remove your config directory and pull the new image. Sorry for the inconvenience. Thank you for reporting!

**Comment by markhaines** [comment] 2018-11-05 12:18
This was on a completely fresh install it was doing it.  But will wait for dev image to propagate and have another play later.

**Comment by morpheus65535** [comment] 2018-11-06 11:37
Did you try the new image that have been build yesterday?

**Comment by markhaines** [comment] 2018-11-06 11:41
Watchtower updated Bazarr overnight, am on the developer image, version is still .67 tho - is that correct?  It was able to pull some subtitles when i tried to do a forced search to the point that I think I've now hit the 200 subs a day limit on OpenSubtitles, however the logs still imply theres an error (I've seen a 'throttled' log response before so think this is likely still same underlying issue:

<img width="1124" alt="system_-_bazarr" src="https://user-images.githubusercontent.com/1022008/48062048-c4fdce80-e1b8-11e8-9a14-2658e058631d.png">

**Comment by morpheus65535** [comment] 2018-11-06 11:44
No version bump this time, you're correct. Does your language settings now appear correctly? Can you provide the traceback for your exception?

**Comment by markhaines** [comment] 2018-11-06 11:45
<img width="1121" alt="system_-_bazarr" src="https://user-images.githubusercontent.com/1022008/48062220-566d4080-e1b9-11e8-9ba8-3c05038c5f1f.png">

Here's a further screenshot showing manual searching working (the UI still dies when I trigger this but I can reload using the root url and it works ok).

**Comment by markhaines** [comment] 2018-11-06 11:48
Example traceback error:

06/11/2018 00:05:03|DEBUG|BAZARR Starting movie sync from Radarr.|
06/11/2018 00:05:03|DEBUG|Starting new HTTPS connection (1): movies.******.com:443|
06/11/2018 00:05:03|DEBUG|https://movies.*******.com:443 "GET /api/profile?apikey=848*************94acfa417ab HTTP/1.1" 200 None|
06/11/2018 00:05:03|DEBUG|Starting new HTTPS connection (1): movies.hainesy.com:443|
06/11/2018 00:05:04|DEBUG|https://movies.*******.com:443 "GET /api/movie?apikey=848*************94acfa417ab HTTP/1.1" 200 None|
06/11/2018 00:05:05|ERROR|Job "Update movies list from Radarr (trigger: interval[0:05:00], next run at: 2018-11-06 00:10:03 GMT)" raised an exception|'Traceback (most recent call last):\n  File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job\n    retval = job.func(*job.args, **job.kwargs)\n  File "/app/bazarr/bazarr/get_movies.py", line 121, in update_movies\n    store_subtitles_movie(path_replace_movie(added_path[0]))\nTypeError: \'NoneType\' object has no attribute \'__getitem__\''|

**Comment by morpheus65535** [comment] 2018-11-06 12:05
It seems you still have the previous version. Can you pull the new image?

**Comment by morpheus65535** [comment] 2018-11-06 13:34
Did you pull image between deletion and recreation? `docker pull linuxserver/bazarr:latest`

**Comment by morpheus65535** [comment] 2018-11-06 13:34
Thanks for the language selection test.

**Comment by markhaines** [comment] 2018-11-06 13:39
Ah, I was on development version still.  Have deleted, pulled and recreated 'latest' instead.  Forced an 'update movies check' and this is usual error:

<img width="700" alt="system_-_bazarr" src="https://user-images.githubusercontent.com/1022008/48067900-59702d00-e1c9-11e8-8a2e-3734ae151572.png">

**Comment by morpheus65535** [comment] 2018-11-06 14:17
Should get the same result with dev branch. Is it possible to organize a team viewer session where I could try to debug this on your setup? I cannot reproduce this behavior.

**Comment by morpheus65535** [comment] 2018-11-06 20:18
0.6.7.1 image is available

**Comment by markhaines** [comment] 2018-11-06 20:50
> Should get the same result with dev branch. Is it possible to organize a team viewer session where I could try to debug this on your setup? I cannot reproduce this behavior.

Yes, that would be cool - could do something later this week?  What time zone are you in?

**Comment by morpheus65535** [comment] 2018-11-06 21:03
Maybe friday? I work from home. I'm in GMT-5.

**Comment by piduchesne** [comment] 2018-11-13 19:20
Hello, i can reproduce the exact same bug

**Comment by morpheus65535** [comment] 2018-11-13 22:36
@piduchesne Are you sure you are running 0.6.7.1?

**Comment by morpheus65535** [comment] 2018-11-14 00:28
It’s a totally different issue. Please open a new issue report and add your log file.

**Comment by morpheus65535** [comment] 2018-11-15 13:29
@markhaines Do you still have thi issue?

**Comment by markhaines** [comment] 2018-11-15 14:05
Have just checked, and yes - afraid so.  The app seems otherwise stable though and I've noticed it will automatically pull down subs for new titles that Radarr has grabbed without issue.

**Comment by morpheus65535** [comment] 2018-12-30 19:34
Is this still an issue or I can close it?

**Comment by morpheus65535** [comment] 2019-01-03 05:58
No feedback. Closing this issue.

**Closed by morpheus65535** 2019-01-03 05:58 UTC
Labels: awaiting feedback, bug, priority:medium
