### ISSUE TITLE
Needs external IP for connection to radarr and sonarr on the same computer

### ISSUE THREAD

**Issue by janlimpens** [morpheus65535/bazarr#94] opened 2018-06-20 18:56 UTC
I get no connection to the services, neither with 127.0.0.1 nor localhost. I need to use the "external ip", in my case the one given to the device by my router (192.168.1.x).

On a Raspi3.

**Comment by morpheus65535** [comment] 2018-06-20 23:57
Must be related to your network configuration because it work perfectly well on Windows 10, Ubuntu 16.10 and Alpine Linux 3.7. That's something that have been tested a lot by other user before.

**Comment by janlimpens** [comment] 2018-06-21 00:51
Both Radarr and Sonarr use localhost to connect to Kodi, transmission and sabnzb. This should not be the issue. I guess it has to do with docker.
```docker info``` gives me this line:
Insecure Registries:
 127.0.0.0/8

Could be related to that, I guess…

But thanks for the heads up!

Jan

**Comment by morpheus65535** [comment] 2018-06-21 00:59
Ok, I suppose your using bridged network mode in docker? If that's the case, you need to know that each docker got his own ip address in a special ip range (usually 172.17.0.0/16). So, for Bazarr running in docker, localhost or 127.0.0.1 refer to the local container, not something running directly onto the RPI like Sonarr and Radarr. If you want to reach the host from the container, you need to use the "external ip" of the host (192.168.1.x) or the ip or the docker bridge interface on the host (something like 172.17.0.1).

Your issue is only a misunderstanding or docker networking stack. :-)

**Comment by evertonstz** [comment] 2018-06-24 16:48
I can't reproduce it now but I used to have the same issue on my old vps provider.

**Comment by morpheus65535** [comment] 2018-06-24 16:50
@evertonstz Using Bazarr or another software inside a docker container?

**Comment by evertonstz** [comment] 2018-06-24 16:51
@morpheus65535 both bazzar and other software. This is definitely a problem with docker.

**Comment by morpheus65535** [comment] 2018-06-24 16:52
@evertonstz Ok thanks for your feedback. Maybe related to a bug in a previous version of docker that have been fixed since.

**Comment by morpheus65535** [comment] 2018-06-24 16:56
BTW I'm using docker 18.03.1-ce on my setup.

**Comment by morpheus65535** [comment] 2018-07-04 02:24
No answer, closing issue.

**Closed by morpheus65535** 2018-07-04 02:24 UTC
Labels: awaiting feedback, cannot reproduce
