### ISSUE TITLE
Crashing on upload manual

### ISSUE THREAD

**Issue by iHunterX** [morpheus65535/bazarr#1865] opened 2022-06-05 11:22 UTC
**Describe the bug**
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

**To Reproduce**
1. Go to any series
2. Click on 'Upload' multiple files
3. Upload
4. See error:  'Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.'

**Expected behavior**
Welp, not a crash
**Screenshots**
![image](https://user-images.githubusercontent.com/16854718/172048066-0cb19caf-5435-42b1-a44d-430e8051f105.png)

**Software (please complete the following information):**
 - Bazarr: 1.0.4
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version  3.0.8.1507
 - OS: Docker -  Synology

**Additional context**

**Comment by morpheus65535** [comment] 2022-06-06 10:40
@LASER-Yi Should that be fixed in new UI?

**Comment by morpheus65535** [comment] 2022-06-10 19:09
@LASER-Yi fixed?

**Comment by LASER-Yi** [comment] 2022-06-11 05:04
> @LASER-Yi fixed?

Cannot reproduce in the new UI. I will close this issue.

**Closed by LASER-Yi** 2022-06-11 05:04 UTC
Labels: bug, cannot reproduce
