### ISSUE TITLE
LegendasDivX provider fails with TypeError and downloads incorrect subtitle

### ISSUE THREAD

**Issue by JpF4E** [morpheus65535/bazarr#834] opened 2020-02-22 23:17 UTC
**Describe the bug**
When downloading a subtitle for the series "Shooter", episode **S02E04** the provider fails with the error: "TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'".

For this episode the provider downloads a Rar file with the subtitles for all the episodes of the season and it fails opening a file from the inside of the Rar file. See "Additional Context" for logs.

**To Reproduce**
1. Add series Shooter
2. Monitor episode S02E04 (I believe it also happens to other episodes)
3. Force subtitle download with legendasdivx provider configured

**Expected behavior**
It should not have given the error.

**Screenshots**
No need.

**Software (please complete the following information):**
 - Bazarr: 0.8.4.1
 - Radarr version No Radarr
 - Sonarr version 2.0.0.5338
 - OS: CentOS 8

**Additional context**
Relevant logs:

```
22/02/2020 22:15:03|DEBUG   |subliminal_patch.core           |<LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&lid=261021' [pt:None]>: Trying to download subtitle with matches {'year', 'release_group', 'video_codec', 'hearing_impaired', 'resolution', 'format', 'season', 'series', 'episode'}, score: 357; release(s): shooter s02


releases:

shooter.s02e01.720p.hdtv.x264-avs
shooter.s02e01.1080p.amzn.web-dl.dd+5.1.h.264-qoq
shooter.s02e02.480p.web.dl.x264.rmteam
shooter.s02e02.720p.hdtv.x264-avs
shooter.s02e02.hdtv.x264-avs
shooter.s02e02.internal.720p.webrip.x264-strife
shooter.s02e03.720p.hdtv.x264-sva
shooter.s02e03.1080p.web.x264-strife
shooter.s02e03.hdtv.x264-sva
shooter.s02e03.webrip.x264-rarbg
shooter.s02e04.720p.hdtv.x264-sva
shooter.s02e04.1080p.amzn.webrip.ddp5.1.x264-qoq
shooter.s02e04.hdtv.x264-sva
shooter.s02e04.webrip.x264-rarbg
shooter.s02e05.720p.hdtv.x264-sva
shooter.s02e05.1080p.web.x264-tbs
shooter.s02e05.hdtv.x264-sva
shooter.s02e05.webrip.x264-rarbg
shooter.s02e06.720p.hdtv.x264-avs
shooter.s02e06.hdtv.x264-sva
shooter.s02e06.1080p.hdtv.x264-brisk
shooter.s02e06.internal.720p.webrip.x264-strife
shooter.s02e06.internal.1080p.webrip.x264-strife
shooter.s02e06.nf.web-dl-webrip.x264
shooter.s02e06.webrip.x264-rarbg
shooter.s02e07.720p.hdtv.x264-avs
shooter.s02e07.hdtv.x264-sva
shooter.s02e07.internal.720p.webrip.x264-strife_rarbg
shooter.s02e08.720p.hdtv.x264-avs
shooter.s02e08.hdtv.x264-sva
shooter.s02e08.internal.720p.webrip.x264-strife
shooter.s02e08.internal.1080p.webrip.x264-strife
shooter.s02e08.webrip.x264-rarbg


notas:
legendas para releases provenientes da netflix
caso dêem para mais releases, deixem nos comentários, por favor.

créditos mantidos.

update: 21h00 - 6/09/2017nota: legenda está no formato utf8 - download em ansi|
22/02/2020 22:15:03|INFO    |subliminal_patch.core           |Downloading subtitle <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&lid=261021' [pt:None]>|
22/02/2020 22:15:03|DEBUG   |urllib3.connectionpool          |https://www.legendasdivx.pt:443 "GET /modules.php?name=Downloads&d_op=getit&lid=261021 HTTP/1.1" 200 None|

...

22/02/2020 22:15:05|DEBUG   |subliminal_patch.providers.legendasdivx|Identified rar archive|
22/02/2020 22:15:05|DEBUG   |subliminal_patch.providers.legendasdivx|returning from archive: Shooter.S02E01.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.srt|
22/02/2020 22:15:05|ERROR   |subliminal_patch.core           |Unexpected error in provider 'legendasdivx', Traceback: Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 266, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 305, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1133, in open    return self._open_unrar_membuf(self._rarfile, inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1174, in _open_unrar_membuf    return self._open_unrar(tmpname, inf, psw, tmpname, force_file=True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__    restore_signals, start_new_session)  File "/usr/lib64/python3.6/subprocess.py", line 1278, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib64/python3.6/os.py", line 800, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 259, in download_subtitle    self[subtitle.provider_name].download_subtitle(subtitle)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 266, in download_subtitle    subtitle_content = self._get_subtitle_from_archive(archive)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/legendasdivx.py", line 305, in _get_subtitle_from_archive    return archive.read(name)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 771, in read    with self.open(fname, 'r', psw) as f:  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 756, in open    return self._file_parser.open(inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1133, in open    return self._open_unrar_membuf(self._rarfile, inf, psw)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1174, in _open_unrar_membuf    return self._open_unrar(tmpname, inf, psw, tmpname, force_file=True)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1191, in _open_unrar    return PipeReader(self, inf, cmd, tmpfile)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2142, in __init__    super(PipeReader, self).__init__(rf, inf)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 1983, in __init__    self._open()  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2165, in _open    self._proc = custom_popen(self._cmd)  File "/opt/bazarr/bazarr/../libs/rarfile.py", line 2813, in custom_popen    creationflags=creationflags)  File "/usr/lib64/python3.6/subprocess.py", line 729, in __init__    restore_signals, start_new_session)  File "/usr/lib64/python3.6/subprocess.py", line 1278, in _execute_child    executable = os.fsencode(executable)  File "/usr/lib64/python3.6/os.py", line 800, in fsencode    filename = fspath(filename)  # Does type-checking of `filename`.TypeError: expected str, bytes or os.PathLike object, not NoneType|
22/02/2020 22:15:05|INFO    |root                            |Throttling legendasdivx for 10 minutes, until 20/02/22 22:25, because of: TypeError. Exception info: 'expected str, bytes or os.PathLike object, not NoneType'|
22/02/2020 22:15:05|DEBUG   |subliminal_patch.core           |<LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&lid=259564' [pt:None]>: Trying to download subtitle with matches {'year', 'release_group', 'video_codec', 'hearing_impaired', 'resolution', 'format', 'season', 'series', 'episode'}, score: 357; release(s): releases

shooter.s02e04.hdtv.x264-sva
shooter.s02e04.720p.hdtv.x264-sva

|
22/02/2020 22:15:05|WARNING |subliminal_patch.core           |Provider 'legendasdivx' is discarded|
```

**Comment by morpheus65535** [comment] 2020-02-22 23:19
Did you tried dev branch?

**Comment by JpF4E** [comment] 2020-02-22 23:37
Yes, just tried it and it fails with the TypeError.

**Comment by GermanG** [comment] 2020-02-23 19:03
I see two different issues here
1. is the error trying to decompress the rar file.
1. is trying to get the wrong subtitle out of an archive with many subtitles!

For 1, I'd like to have the log line having the text with 
```
BAZARR is using these video object properties
```
I'll try to reproduce it with that info.

For 2, in series is seemed to be easy if I try to match the season and episode, but then the issue is how that info can be: s01e01, 1x1, 101, etc. For movies can be worst, if we have for different releases in the same archive, that'll be more difficult to figure out.

**Comment by JpF4E** [comment] 2020-02-23 20:57
The log you asked for:

`22/02/2020 22:14:58|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/home/joao/Series/Shooter/Season 2/Shooter.S02E04.720p.HDTV.x264-SVA[eztv].mkv', 'format': 'HDTV', 'release_group': 'SVA', 'resolution': '720p', 'video_codec': 'h264', 'audio_codec': 'AC3', 'imdb_id': None, 'hashes': {'opensubtitles': '7713ccbf259dd615'}, 'size': 1011505684, 'subtitle_languages': set(), 'original_name': 'Shooter.S02E04.720p.HDTV.x264-SVA[eztv].mkv', 'plexapi_metadata': {}, 'hints': {'title': 'Shooter', 'type': 'episode', 'single_value': True, 'expected_title': ['Shooter']}, 'audio_languages': set(), 'external_subtitle_languages': set(), 'series': 'Shooter', 'season': 2, 'episode': 4, 'title': 'The Dark End of the Street', 'year': 2016, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 311900, 'series_imdb_id': None, 'alternative_series': [], 'used_scene_name': True, 'original_path': '/home/joao/Series/Shooter/Season 2/Shooter.S02E04.720p.HDTV.x264-SVA[eztv].mkv', 'fps': 23.976}|`

**Comment by GermanG** [comment] 2020-02-24 07:19
@JpF4E Regretfully I cannot reproduce the error. Silly question, do you have unrar installed? (It's mandatory for the python unrar module). 
@morpheus65535 I've made a short script to test that provider, I think it can fit any provider. I know everything is hardcoded ;)

**Comment by JpF4E** [comment] 2020-02-24 14:12
Okay, I didn't have unrar installed. And that was the problem.
I setup a CentOS 8 server some time ago and probably never needed it before.
The provider is now fine to me. I understand there are problems with the score calculation when many subs come in the same archive. You can close the issue by then if you decide to tackle that.
Thank you.

**Comment by GermanG** [comment] 2020-02-24 15:18
@JpF4E did you check with the lastest dev? I've made a PR today that might fix the issue (not scoring yet)

**Comment by JpF4E** [comment] 2020-02-24 15:19
I tried your latest change in development:
It now downloads the correct subtitle and the file is indeed in the disk and correctly named.
However in the bazarr interface it still displays as missing, like it isn't detecting the new file.
<details>
  <summary>Logs</summary>

```
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|Identified rar archive|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E01.1080p.AMZN.WEB-DL.DD+5.1.H.264-QOQ.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E1 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E01.720p.HDTV.x264-AVS.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E1 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E02.480p.WEB.DL.x264.RMTeam.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E2 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E02.720p.HDTV.x264-AVS.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E2 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E02.HDTV.x264-AVS.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E2 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E02.iNTERNAL.720p.WEBRip.x264-STRiFE.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E2 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E03.1080p.WEB.x264-STRiFE.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E3 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E03.720p.HDTV.x264-SVA.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E3 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E03.HDTV.x264-SVA.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E3 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E03.WEBRip.x264-RARBG.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E3 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle does not match video, skipping|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|guessing Shooter.S02E04.1080p.AMZN.WEBRip.DDP5.1.x264-QOQ.srt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|subtitle S2E4 video S2E4|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.providers.legendasdivx|returning from archive: Shooter.S02E04.1080p.AMZN.WEBRip.DDP5.1.x264-QOQ.srt|
24/02/2020 15:05:53|INFO    |subliminal_patch.subtitle       |Guessing encoding for language pt|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.subtitle       |Trying encodings ['utf-8', 'latin-1', 'iso-8859-15', 'iso-8859-9', 'iso-8859-4', 'iso-8859-1']|
24/02/2020 15:05:53|INFO    |subliminal_patch.subtitle       |Guessed encoding latin-1|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.subtitle       |Changing encoding: to utf-8, from latin-1|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.core           |All languages downloaded|
24/02/2020 15:05:53|INFO    |subliminal_patch.core           |Downloaded 1 subtitle(s)|
24/02/2020 15:05:53|DEBUG   |subliminal.core                 |Terminating initialized providers|
24/02/2020 15:05:53|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
24/02/2020 15:05:53|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): api.opensubtitles.org:80|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
24/02/2020 15:05:53|DEBUG   |urllib3.connectionpool          |http://api.opensubtitles.org:80 "POST /xml-rpc HTTP/1.1" 200 171|
24/02/2020 15:05:53|INFO    |subliminal_patch.core           |Terminating provider legendasdivx|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
24/02/2020 15:05:53|DEBUG   |subliminal_patch.core           |Saving <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&lid=261021' [pt:utf-8]> to '/home/joao/Series/Shooter/Season 2/Shooter.S02E04.720p.HDTV.x264-SVA[eztv].pt.srt'|
24/02/2020 15:05:53|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /home/joao/Series/Shooter/Season 2/Shooter.S02E04.720p.HDTV.x264-SVA[eztv].pt.srt|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 da7d9d3c-8bd8-482e-8152-f3675c2870ef|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 1d2d7b19-8835-4ebe-89a8-5450ca513e0a|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 752d182f-f31f-40de-b938-13668942837a|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 7f43fb5a-ab64-461d-90fe-e668c85ec5d5|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT configured, updated FROM system, None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 f484c9fe-01fa-48bd-9e70-44dc754e573d|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT configured, updated FROM system, []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 89ba499a-1a3c-4ee8-978d-4be6dc657eef|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |execute: SELECT table_shows.title as seriesTitle, table_episodes.season || 'x' || table_episodes.episode as episode_number, table_episodes.title as episodeTitle, table_episodes.missing_subtitles, table_episodes.sonarrSeriesId, table_episodes.path, table_shows.hearing_impaired, table_episodes.sonarrEpisodeId, table_episodes.scene_name, table_episodes.failedAttempts FROM table_episodes INNER JOIN table_shows on table_shows.sonarrSeriesId = table_episodes.sonarrSeriesId WHERE table_episodes.missing_subtitles != '[]' ORDER BY table_episodes._rowid_ DESC LIMIT ? OFFSET ?, (25, 0)|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |Sleeping: 0.001 cf03aaff-8313-4f8c-aeb0-183c73447260|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: SELECT table_shows.title as seriesTitle, table_episodes.season || 'x' || table_episodes.episode as episode_number, table_episodes.title as episodeTitle, table_episodes.missing_subtitles, table_episodes.sonarrSeriesId, table_episodes.path, table_shows.hearing_impaired, table_episodes.sonarrEpisodeId, table_episodes.scene_name, table_episodes.failedAttempts FROM table_episodes INNER JOIN table_shows on table_shows.sonarrSeriesId = table_episodes.sonarrSeriesId WHERE table_episodes.missing_subtitles != '[]' ORDER BY table_episodes._rowid_ DESC LIMIT ? OFFSET ?, (25, 0)|
24/02/2020 15:05:53|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |execute: SELECT * FROM table_settings_languages ORDER BY name, None|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |Sleeping: 0.001 0eefcc2d-117d-47a2-bbe5-35695b1478c9|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: SELECT * FROM table_settings_languages ORDER BY name, []|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |execute: SELECT * FROM table_settings_notifier ORDER BY name, None|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |Sleeping: 0.001 062773ef-5195-4cce-a0e1-11b93e3f209b|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: SELECT * FROM table_settings_notifier ORDER BY name, []|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |Sleeping: 0.001 d468987f-712e-42eb-a8a2-0a040990396a|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_episodes WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |execute: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', None|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |Sleeping: 0.001 82639fa1-acc7-4eaf-8e9d-0ebb7ca83cf5|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: SELECT COUNT(*) as count FROM table_movies WHERE missing_subtitles != '[]', []|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |execute: SELECT configured, updated FROM system, None|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |Sleeping: 0.001 da03d53e-7c9a-4de2-a370-47937141562d|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: SELECT configured, updated FROM system, []|
24/02/2020 15:05:55|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |execute: UPDATE table_settings_languages SET enabled=0, None|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.001 94075a74-9885-4101-ad3d-7066709d446e|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: UPDATE table_settings_languages SET enabled=0, []|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |execute: UPDATE table_settings_languages SET enabled=1 WHERE code2=?, ('en',)|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.001 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.002 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.004 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.008 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.016 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.032 8f837cec-ba87-4696-851c-469b450ac9c6|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: UPDATE table_settings_languages SET enabled=1 WHERE code2=?, ('en',)|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: commit|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |execute: UPDATE table_settings_languages SET enabled=1 WHERE code2=?, ('pt',)|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.001 cd56f25e-e171-4608-983a-f73fae5cf737|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.002 cd56f25e-e171-4608-983a-f73fae5cf737|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.004 cd56f25e-e171-4608-983a-f73fae5cf737|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.008 cd56f25e-e171-4608-983a-f73fae5cf737|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |Sleeping: 0.016 cd56f25e-e171-4608-983a-f73fae5cf737|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |sql_queue: 0|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: UPDATE table_settings_languages SET enabled=1 WHERE code2=?, ('pt',)|
24/02/2020 15:05:57|DEBUG   |sqlite3worker                   |run: commit|
```
</details>

**Comment by GermanG** [comment] 2020-02-24 15:24
And you're not looking for Shooter.S02E04? Maybe is not the version you want, can you try my repo? 
https://github.com/GermanG/bazarr/tree/legendasdivx (it's the legendasdivx branch) I've put scoring there.

**Comment by JpF4E** [comment] 2020-02-24 15:46
I cloned your repo and now I can't find the provider at all:
![Screenshot (4)](https://user-images.githubusercontent.com/20103641/75167146-da379d00-571c-11ea-8feb-acf850771394.png)

**Comment by JpF4E** [comment] 2020-02-24 15:51
> And you're not looking for Shooter.S02E04? Maybe is not the version you want, can you try my repo?
> https://github.com/GermanG/bazarr/tree/legendasdivx (it's the legendasdivx branch) I've put scoring there.

I was looking for that episode. In the Missing section I clicked to search the subtitles. The loading phased out but the episode remained in the missing section as if the subtitle was still not present (or no results returned) but it downloaded the subtitles correctly. It's just the interface that didn't detect it. The correct srt was present alongside the mkv.

**Comment by GermanG** [comment] 2020-02-24 15:57
> I cloned your repo and now I can't find the provider at all:
> ![Screenshot (4)](https://user-images.githubusercontent.com/20103641/75167146-da379d00-571c-11ea-8feb-acf850771394.png)

Looks like you're in the master branch (I'm following development branch directly from morpheus65535)

git checkout legendasdivx

**Comment by GermanG** [comment] 2020-02-24 15:59
> > And you're not looking for Shooter.S02E04? Maybe is not the version you want, can you try my repo?
> > https://github.com/GermanG/bazarr/tree/legendasdivx (it's the legendasdivx branch) I've put scoring there.
> 
> I was looking for that episode. In the Missing section I clicked to search the subtitles. The loading phased out but the episode remained in the missing section as if the subtitle was still not present (or no results returned) but it downloaded the subtitles correctly. It's just the interface that didn't detect it. The correct srt was present alongside the mkv.

This behaviour happens to me when I mess up with the provider and something breaks, surprisingly your log doesn't show anything.

**Comment by JpF4E** [comment] 2020-02-24 16:25
> > I cloned your repo and now I can't find the provider at all:
> > ![Screenshot (4)](https://user-images.githubusercontent.com/20103641/75167146-da379d00-571c-11ea-8feb-acf850771394.png)
> 
> Looks like you're in the master branch (I'm following development branch directly from morpheus65535)
> 
> git checkout legendasdivx

Ahh you're right, damn you git.

Okay, with your version it worked fine.
I cleared my data folder though. Maybe there could be some kind of inconsistency.
I'm going to try the development branch again with no data folder and then try with my old one.

**Comment by JpF4E** [comment] 2020-02-24 16:46
Okay, I did both tests that I mentioned and it worked fine. It probably was some kind of inconsistency that I created.

Feel free to close the issue when you merge.

**Comment by morpheus65535** [comment] 2020-02-24 19:55
Merged. I close this one. Thanks @GermanG !

**Closed by morpheus65535** 2020-02-24 19:55 UTC
