### ISSUE TITLE
subs4series and subs4free error

### ISSUE THREAD

**Issue by babos123** [morpheus65535/bazarr#913] opened 2020-04-06 14:20 UTC
I have open an issue in the past with the same problem https://github.com/morpheus65535/bazarr/issues/773#issue-555051529
pkoutsias had made a fix but in my system isnt working.

subs4series and subs4free most of the times is HTTPError and when not again isnt downloading
anything.
(opensubtitles working and downloading subs)

So..
Bazarr Version: 0.8.4.3
Sonarr Version: 3.0.3.750
Radarr Version: 3.0.0.2784
Operating System: Linux-4.15.0-72-generic-x86_64-with
Python Version: 3.8.2

I have cleaned log files and enable debug log. and i search for one movie/series 

2 log files for the 2 providers:

[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/4438910/bazarr.1.log)

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4438911/bazarr.log)

**Comment by morpheus65535** [comment] 2020-04-08 00:42
`HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.subs4series.com/search_report.php?search=manifest&searchType=1'`

@pkoutsias does this provider have username/password? From Bazarr UI I would say no but it could be a new requirement...

**Comment by arpal-jpg** [comment] 2020-04-08 07:53
> `HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.subs4series.com/search_report.php?search=manifest&searchType=1'`
> 
> @pkoutsias does this provider have username/password? From Bazarr UI I would say no but it could be a new requirement...

No, it does not require username/passowr... I have the same problem, in fact i made the fix and the http error is replaced with an attribute error
"Throttling subs4series for 10 minutes, until 20/04/08 10:58, because of: AttributeError. Exception info: "'NoneType' object has no attribute 'contents'"

**Comment by morpheus65535** [comment] 2020-04-08 11:16
@arpal-jpg A debug log could help.

**Comment by arpal-jpg** [comment] 2020-04-08 11:27
@morpheus65535 here it is :)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4450158/bazarr.log)

**Comment by morpheus65535** [comment] 2020-04-08 11:30
You have to wait for the throttling to expire and try again for me to see the root cause in your debug log. Right now I just the consequence.

**Comment by pen-ops** [comment] 2020-04-08 11:37
Same here 
[bazarr(1).log](https://github.com/morpheus65535/bazarr/files/4450192/bazarr.1.log)

**Comment by morpheus65535** [comment] 2020-04-08 12:00
As we are already using random user agent, I suppose they've implemented captcha that we do not try to solve. @pkoutsias when you'll get free time, could you take a look at this please? Thanks!

**Comment by arpal-jpg** [comment] 2020-04-08 12:10
@morpheus65535 yes, unfortunately captcha implementation is what they have done!!!

**Comment by NickCh11** [comment] 2020-04-08 12:10
> 
> 
> As we are already using random user agent, I suppose they've implemented captcha that we do not try to solve. @pkoutsias when you'll get free time, could you take a look at this please? Thanks!

no they dont use captcha

**Comment by NickCh11** [comment] 2020-04-08 12:11
i dont see capctha when i try to download manually from site

**Comment by arpal-jpg** [comment] 2020-04-08 12:14
i do see it, it appears at the last step, you have to validate captcha for the download to start!!!
![IMG_20200408_151210](https://user-images.githubusercontent.com/62991187/78782998-9be3fd80-79ab-11ea-837e-b291577de349.jpg)

**Comment by NickCh11** [comment] 2020-04-08 12:21
![image](https://user-images.githubusercontent.com/58607503/78783554-80c5bd80-79ac-11ea-9057-8d2e83f45f97.png)
i don't maybe you downloaded a lot?

**Comment by NickCh11** [comment] 2020-04-08 12:24
i tried subs4series but also no captcha for me

**Comment by babos123** [comment] 2020-04-08 12:32
I try both no captcha for me either

**Comment by morpheus65535** [comment] 2020-04-08 12:39
They implemented Cloudflare protection that could involve solving a captcha or not. It depends of the context. Making this work for Subscene took a couple of weeks so don't expect this provider to work for a while (if it ver get fixed at all).

**Comment by arpal-jpg** [comment] 2020-04-08 12:40
Well, dont know why this happens to me, i rebooted router but captcha is still on, although on a new ip adress...

**Comment by morpheus65535** [comment] 2020-04-28 12:01
@pkoutsias did you had time to look into this one? Thanks!

**Comment by pkoutsias** [comment] 2020-04-29 07:26
@morpheus65535 I don't get captcha myself, but either way, I don't have the time right now to make captcha work.

**Comment by morpheus65535** [comment] 2020-04-29 11:01
@pkoutsias no problem mate, thanks!

**Comment by morpheus65535** [comment] 2020-07-06 17:59
I've made some fixes to both providers. They're both working fine for me but Ive never encountered Captcha so I cannot help with that. Can someone here test the fixes I've made in dev branch?

**Comment by NickCh11** [comment] 2020-07-06 18:21
> 
> 
> I've made some fixes to both providers. They're both working fine for me but Ive never encountered Captcha so I cannot help with that. Can someone here test the fixes I've made in dev branch?

nice work! i cant test it tho sorry.

**Comment by babos123** [comment] 2020-07-06 18:23
testing now

**Comment by babos123** [comment] 2020-07-06 20:07
if anti-captcha is required then tomorrow i will subscribe to a provider.
if not then in latest dev isnt working at least for me. the same HTTPError
Throttling subs4free for 10 minutes, until 20/07/06 18:29, because of: HTTPError. Exception info: '403 Client Error: Forbidden for url: https://www.sf4-industry.com/search_report.php?search=clemency&searchType=1'

**Comment by morpheus65535** [comment] 2020-07-06 20:11
Anti-Captcha isn't implemented for this provider so it won'T change anything.

As the latest dev branch is using subs4free.info instead of sf4-industry.com in every queries, you probably don't have the latest dev.

**Comment by babos123** [comment] 2020-07-07 05:22
You are right! I update to latest now.
Sub4free is working!
Sub4series isnt....getting the same httperror
I just update so I will keep testing ofcourse

**Comment by evripidesk** [comment] 2020-07-07 05:47
> You are right! I update to latest now.
> Sub4free is working!
> Sub4series isnt....getting the same httperror
> I just update so I will keep testing ofcourse

How do you update? I checked from task  - Update Bazarr from source on Github
but I get BAZARR No new version of Bazarr available.

**Comment by babos123** [comment] 2020-07-07 05:51
> > You are right! I update to latest now.
> > Sub4free is working!
> > Sub4series isnt....getting the same httperror
> > I just update so I will keep testing ofcourse
> 
> How do you update? I checked from task - Update Bazarr from source on Github
> but I get BAZARR No new version of Bazarr available.

I use docker so i just update through portainer

**Comment by halali** [comment] 2020-07-07 07:53
@evripidesk yoi have to be on development Branch.

**Comment by evripidesk** [comment] 2020-07-07 08:19
Yes I already set to dev branch

**Comment by NickCh11** [comment] 2020-07-07 14:08
both work great for me good job!

**Comment by morpheus65535** [comment] 2020-07-07 14:55
subs4series seems to be redirecting (302) to `m.subs4series.com` from time to time. I don't get what is causing it but I'm looking into it. Currently, you can reset provider throttling and retry and it will eventually work.

**Comment by morpheus65535** [comment] 2020-07-07 15:44
Ok I found out the issue. We were using a randomly selected user-agent to make requests to subs4series and our list of user-agents does include mobile browser user-agents. When we were randomly using a mobile browser agent, we were getting redirected to subs4series mobile website where URL doesn't match anymore. We were running into a 404 that cannot be parsed as expected and was raising an exception that make Bazarr throttle this provider.

This should be fixed by forcing Chrome user-agent. Please run some test and confirm.

**Closed** 2020-07-13 18:13 UTC
Labels: awaiting feedback

**Comment by pen-ops** [comment] 2020-07-23 17:54
subs4free seems to work , subs4series still has issues
[bazarr(1).log](https://github.com/morpheus65535/bazarr/files/4967889/bazarr.1.log)

**Comment by morpheus65535** [comment] 2020-07-23 18:10
> subs4free seems to work , subs4series still has issues
> [bazarr(1).log](https://github.com/morpheus65535/bazarr/files/4967889/bazarr.1.log)

HTTP 403 error means access denied. You've been blocked my friend. Probably your IP or whole country. Permanently or temporarily, who knows...

**Comment by pen-ops** [comment] 2020-07-23 18:13
haha you are taking the piss. The ip is fine I have double checked. I also have paid for anti-captcha. Also whatever sub I download from subs4free it makes the video unplayable if I preselect the sub and then play the video. If I choose a different subs (etc from anotherwebsite) it plays fine.

**Comment by pen-ops** [comment] 2020-07-23 18:14
anyway thanks for trying, but consider this issue still open.
