### ISSUE TITLE
Post Processing not working for Series / audio_language issue

### ISSUE THREAD

**Issue by SimpsomRJ** [morpheus65535/bazarr#1071] opened 2020-08-14 19:45 UTC
**Describe the bug**
Post processing fails

**To Reproduce**
enable post processing
set processing to "echo 0"
You should see in the logs:
BAZARR Post-processing result for file /tv/xxx/xxx.mkv : 0

**Expected behavior**
Execute post processing with no problems. When running on movies everything works. Only when using for tv shows that this error is found.

**Software (please complete the following information):**
 - Bazarr: 0.9.0.1
 - Sonarr version: 3.0.3.907
 - OS: Synology
 - Docker image: linuxserver/bazarr:latest

**Error logs**
14/08/2020 15:37:47|DEBUG   |root                            |FFprobe found: OrderedDict([('path', "/series/Marvel's Agents of S.H.I.E.L.D/Season 07/Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS.mkv"), ('duration', datetime.timedelta(seconds=5081, microseconds=992000)), ('size', 1641418623), ('bit_rate', 2583898), ('container', 'mkv'), ('video', [OrderedDict([('id', 0), ('width', 1280), ('height', 716), ('scan_type', 'Progressive'), ('aspect_ratio', 1.788), ('pixel_aspect_ratio', 1.0), ('resolution', '720p'), ('frame_rate', 23.976), ('bit_depth', 8), ('codec', 'H.264'), ('profile', 'High'), ('default', True)])]), ('audio', [OrderedDict([('id', 1), ('codec', 'AC-3'), ('channels_count', 6), ('channels', '5.1'), ('bit_rate', 384000), ('sampling_rate', 48000), ('default', True)])]), ('provider', {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.3.1'}})])|

14/08/2020 15:37:47|DEBUG   |root                            |BAZARR is using these video object properties: {'name': "/series/Marvel's Agents of S.H.I.E.L.D/Season 07/Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS.mkv", 'source': 'HDTV', 'release_group': 'KILLERS', 'resolution': '720p', 'video_codec': 'H.264', 'audio_codec': 'AC3', 'imdb_id': None, 'hashes': {}, 'size': 1641418623, 'subtitle_languages': set(), 'original_name': 'Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS.mkv', 'plexapi_metadata': {}, 'hints': {'title': "Marvel's Agents of S.H.I.E.L.D.", 'type': 'episode', 'single_value': True, 'expected_title': ["Marvel's Agents of S.H.I.E.L.D."]}, 'audio_languages': set(), 'external_subtitle_languages': set(), 'series': "Marvel's Agents of S.H.I.E.L.D.", 'season': 7, 'episode': 12, 'title': 'The End is at Hand', 'year': 2013, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 263365, 'series_imdb_id': None, 'alternative_series': ['Marvel Agents of SHIELD', 'Agents of SHIELD', 'Marvels Agents of SHIELD', 'Agents Of S.H.I.E.L.D.', 'Marvels Agents of S H I E L D', 'A SHIELD ügynökei', 'A SHIELD ugynokei'], 'used_scene_name': True, 'original_path': "/series/Marvel's Agents of S.H.I.E.L.D/Season 07/Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS.mkv", 'fps': 23.976}|

14/08/2020 15:37:54|ERROR   |app                             |Exception on /bazarr/api/episodes_subtitles_manual_download [POST]|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request    rv = self.dispatch_request()  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper    resp = resource(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view    return self.dispatch_request(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request    resp = meth(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 59, in wrapper    return actual_method(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 597, in post    result = manual_download_subtitle(episodePath, language, audio_language, hi, forced, subtitle,  File "/app/bazarr/bazarr/get_subtitle.py", line 499, in manual_download_subtitle    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,  File "/app/bazarr/bazarr/helper.py", line 109, in pp_replace    pp_command = pp_command.replace('{{episode_language_code2}}', episode_language_code2)TypeError: replace() argument 2 must be str, not None|

**Comment by morpheus65535** [comment] 2020-08-15 12:21
I've just tried it and it works for me:

`BAZARR Post-processing result for file /tv/Marvel's Agents of S.H.I.E.L.D/Season 7/Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS[rarbg].mkv : 0 `

What subtitles languages are you searching for? In my case it was English.

**Comment by SimpsomRJ** [comment] 2020-08-15 14:50
This is just a sample. It is happening with all tv shows. I tried English and Portuguesa.

Eduardo

On Aug 15, 2020, at 8:22 AM, morpheus65535 <notifications@github.com> wrote:

﻿

I've just tried it and it works for me:

BAZARR Post-processing result for file /tv/Marvel's Agents of S.H.I.E.L.D/Season 7/Marvels.Agents.of.S.H.I.E.L.D.S07E12-13.720p.HDTV.x264-KILLERS[rarbg].mkv : 0

What subtitles languages are you searching for? In my case it was English.

**Comment by morpheus65535** [comment] 2020-08-16 13:10
If you provide a complete debug log while reproducing the issue, I could take a look but to be honest, if I cannot reproduce it and if it works for you when you disable custom post-processing, there's something wrong in your setup.

**Comment by SimpsomRJ** [comment] 2020-08-16 21:27
I did a manual search and download for another tv show with debug enabled. You can see the search on 2 providers, download and the exception at the end.

https://pastebin.com/0QiEQrEi

**Comment by morpheus65535** [comment] 2020-08-17 13:56
What is returned by a call to this Sonarr API endpoint?

`/api/v3/languageprofile?apikey=######################################`

**Comment by SimpsomRJ** [comment] 2020-08-17 14:19
This is the result of this request.

```
[
  {
    "name": "En-Pt",
    "upgradeAllowed": false,
    "cutoff": {
      "id": 1,
      "name": "English"
    },
    "languages": [
      {
        "language": {
          "id": 0,
          "name": "Unknown"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 13,
          "name": "Vietnamese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 17,
          "name": "Turkish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 14,
          "name": "Swedish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 3,
          "name": "Spanish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 11,
          "name": "Russian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 12,
          "name": "Polish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 15,
          "name": "Norwegian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 24,
          "name": "Lithuanian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 21,
          "name": "Korean"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 8,
          "name": "Japanese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 5,
          "name": "Italian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 9,
          "name": "Icelandic"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 22,
          "name": "Hungarian"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 23,
          "name": "Hebrew"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 20,
          "name": "Greek"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 4,
          "name": "German"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 2,
          "name": "French"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 19,
          "name": "Flemish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 16,
          "name": "Finnish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 7,
          "name": "Dutch"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 6,
          "name": "Danish"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 25,
          "name": "Czech"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 10,
          "name": "Chinese"
        },
        "allowed": false
      },
      {
        "language": {
          "id": 18,
          "name": "Portuguese"
        },
        "allowed": true
      },
      {
        "language": {
          "id": 1,
          "name": "English"
        },
        "allowed": true
      }
    ],
    "id": 1
  }
]
```

**Comment by morpheus65535** [comment] 2020-08-17 14:27
https://github.com/morpheus65535/bazarr/blob/f7c85f09e011bfbd032e03e18fd869570383d0ab/bazarr/get_series.py#L190

We assumed that profile name was a valid language name like `English`. Yours is `En-Pt` so Bazarr cannot match it to a "real" language name and return `False`.

Radarr is providing the "real" media file audio track language so we can use it. Sonarr only do it on episode and Bazarr haven't been built to take care of episode audio track language.

I'll have to think about how to move there...

**Comment by SimpsomRJ** [comment] 2020-08-17 14:34
I changed the profile name on Sonarr and still face the same issue:

`{
    "name": "English",
    "upgradeAllowed": false,
    "cutoff": {
      "id": 1,
      "name": "English"
    },`

`17/08/2020 10:32:50|DEBUG   |root                            |BAZARR 22 Subtitles have been found for this file: /series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv|
17/08/2020 10:32:50|DEBUG   |root                            |BAZARR Ended searching Subtitles for this file: /series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv|
17/08/2020 10:32:59|DEBUG   |root                            |BAZARR Manually downloading Subtitles for this file: /series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv|
17/08/2020 10:32:59|DEBUG   |subzero.video                   |Parsing video: the.100.s07e11.1080p.web.h264-btx.mkv, hints: {'title': 'The 100', 'type': 'episode'}|
17/08/2020 10:32:59|INFO    |subliminal_patch.core           |Determining basic video properties for 'the.100.s07e11.1080p.web.h264-btx.mkv' in '/series/The 100/Season 07'|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.core           |GuessIt found: {
    "title": "The 100",
    "season": 7,
    "episode": 11,
    "screen_size": "1080p",
    "source": "Web",
    "video_codec": "H.264",
    "release_group": "btx",
    "container": "mkv",
    "type": "episode"
}|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.core           |Size is 2560722418|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.core           |Computed hashes {'opensubtitles': '858f0b4cdff2dd27'}|
17/08/2020 10:32:59|DEBUG   |root                            |BAZARR FFprobe used is /usr/bin/ffprobe|
17/08/2020 10:32:59|DEBUG   |root                            |FFprobe found: OrderedDict([('path', '/series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv'), ('duration', datetime.timedelta(seconds=2545, microseconds=672000)), ('size', 2560722418), ('bit_rate', 8047297), ('container', 'mkv'), ('video', [OrderedDict([('id', 0), ('width', 1920), ('height', 1080), ('scan_type', 'Progressive'), ('aspect_ratio', 1.778), ('pixel_aspect_ratio', 1.0), ('resolution', '1080p'), ('frame_rate', 23.976), ('bit_depth', 8), ('codec', 'H.264'), ('profile', 'High'), ('default', True)])]), ('audio', [OrderedDict([('id', 1), ('codec', 'AAC'), ('profile', 'Low Complexity'), ('channels_count', 2), ('channels', '2.0'), ('sampling_rate', 44100), ('default', True)])]), ('provider', {'name': 'ffmpeg', 'version': {'/usr/bin/ffprobe': 'v4.3.1'}})])|
17/08/2020 10:32:59|DEBUG   |root                            |BAZARR is using these video object properties: {'name': '/series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv', 'source': 'Web', 'release_group': 'btx', 'resolution': '1080p', 'video_codec': 'H.264', 'audio_codec': 'AAC', 'imdb_id': None, 'hashes': {'opensubtitles': '858f0b4cdff2dd27'}, 'size': 2560722418, 'subtitle_languages': set(), 'original_name': 'the.100.s07e11.1080p.web.h264-btx.mkv', 'plexapi_metadata': {}, 'hints': {'title': 'The 100', 'type': 'episode', 'single_value': True, 'expected_title': ['The 100']}, 'audio_languages': set(), 'external_subtitle_languages': set(), 'series': 'The 100', 'season': 7, 'episode': 11, 'title': 'Etherea', 'year': 2014, 'original_series': True, 'tvdb_id': None, 'series_tvdb_id': 268592, 'series_imdb_id': None, 'alternative_series': ['Los 100', 'Les 100'], 'used_scene_name': True, 'original_path': '/series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv', 'fps': 23.976}|
17/08/2020 10:32:59|INFO    |subliminal_patch.core           |Using 1 threads for 1 providers ({'opensubtitles'})|
17/08/2020 10:32:59|INFO    |subliminal_patch.core           |Downloading subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8315242/sid-20iK-HBJ4EqdvjwGa2QVw6Q6mdf/the-100-etherea-en' [en:None]> with score 357|
17/08/2020 10:32:59|INFO    |subliminal_patch.core           |Downloading subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8315242/sid-20iK-HBJ4EqdvjwGa2QVw6Q6mdf/the-100-etherea-en' [en:None]>|
17/08/2020 10:32:59|INFO    |subliminal_patch.core           |Initializing provider opensubtitles|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.providers.opensubtitles|Using timeout: 15|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.providers.opensubtitles|Using HTTPS connection|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.providers.opensubtitles|Using previous login token: '20iK-HBJ4EXXXXXXXXXXXXXXXXX'|
17/08/2020 10:32:59|INFO    |subliminal_patch.providers.opensubtitles|Downloading subtitle <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8315242/sid-20iK-HBJ4EqdvjwGa2QVw6Q6mdf/the-100-etherea-en' [en:None]>|
17/08/2020 10:32:59|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.org:443|
17/08/2020 10:32:59|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on api.opensubtitles.org|
17/08/2020 10:33:00|INFO    |engineio.server                 |3b0e6850b3cb43f0bc25f318f9bab12f: Client is gone, closing socket|
17/08/2020 10:33:00|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.org:443 "POST /xml-rpc HTTP/1.1" 200 12743|
17/08/2020 10:33:00|DEBUG   |subliminal_patch.subtitle       |Changing encoding: to utf-8, from ascii|
17/08/2020 10:33:00|DEBUG   |subliminal.core                 |Terminating initialized providers|
17/08/2020 10:33:00|INFO    |subliminal_patch.core           |Terminating provider opensubtitles|
17/08/2020 10:33:00|DEBUG   |root                            |BAZARR Subtitles file downloaded for this file:/series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.mkv|
17/08/2020 10:33:00|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
17/08/2020 10:33:00|DEBUG   |subliminal_patch.core           |Saving <OpenSubtitlesSubtitle 'http://www.opensubtitles.org/en/subtitles/8315242/sid-20iK-HBJ4EqdvjwGa2QVw6Q6mdf/the-100-etherea-en' [en:utf-8]> to '/series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.en.srt'|
17/08/2020 10:33:00|DEBUG   |root                            |BAZARR Subtitles file saved to disk: /series/The 100/Season 07/the.100.s07e11.1080p.web.h264-btx.en.srt|
17/08/2020 10:33:00|ERROR   |app                             |Exception on /bazarr/api/episodes_subtitles_manual_download [POST]|Traceback (most recent call last):  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request    rv = self.dispatch_request()  File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request    return self.view_functions[rule.endpoint](**req.view_args)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper    resp = resource(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view    return self.dispatch_request(*args, **kwargs)  File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request    resp = meth(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 59, in wrapper    return actual_method(*args, **kwargs)  File "/app/bazarr/bazarr/api.py", line 616, in post    result = manual_download_subtitle(episodePath, language, audio_language, hi, forced, subtitle,  File "/app/bazarr/bazarr/get_subtitle.py", line 505, in manual_download_subtitle    command = pp_replace(postprocessing_cmd, path, downloaded_path, downloaded_language,  File "/app/bazarr/bazarr/helper.py", line 109, in pp_replace    pp_command = pp_command.replace('{{episode_language_code2}}', episode_language_code2)TypeError: replace() argument 2 must be str, not None|`

**Comment by morpheus65535** [comment] 2020-08-17 14:52
Did you gave time to the sync series with Sonarr task to execute properly? In Series view, what audio language is there?

**Comment by SimpsomRJ** [comment] 2020-08-17 15:09
Of course I did not... 👎  for me. After forcing a sync it started working.

Thanks for the help on this. My suggestion is including this in the documentation or FAQ for someone else that might run into this.

**Comment by morpheus65535** [comment] 2020-08-17 15:28
I'll keep it open as a reminder.

**Comment by morpheus65535** [comment] 2020-08-20 14:20
This should be fixed in dev branch with this commit: https://github.com/morpheus65535/bazarr/commit/ebde79a8cd5efcbc1d9584a71ed652f7e983060a

**Closed by morpheus65535** 2020-08-20 14:20 UTC
Labels: bug, priority:medium
