### ISSUE TITLE
No scroll or zoom on mobile browser

### ISSUE THREAD

**Issue by aptalca** [morpheus65535/bazarr#183] opened 2018-10-12 15:17 UTC
**Describe the bug**
On chrome mobile (android), certain pages in the gui do not allow touch scrolling or zooming. The formatting also looks off. The pages with this issue are Movies, Series, and System. The other pages work properly for both scrolling and zooming.

**To Reproduce**
In the android chrome browser, open the Series tab and try to scroll or zoom.

**Software (please complete the following information):**
 - Bazarr: 0.6.6.2
 - OS: linuxserver docker on unraid

**Comment by morpheus65535** [comment] 2018-10-12 16:05
It seems to be a regression in Semantic-UI 2.3.2. I'm testing with 2.4 atm. Thanks for reporting.

**Comment by morpheus65535** [comment] 2018-10-12 17:03
Should be fixed in upcoming 0.6.6.3.

**Closed by morpheus65535** 2018-10-12 17:03 UTC
Labels: bug, priority:high
