### ISSUE TITLE
NameError: name 'wanted_search_missing_subtitles' is not defined

### ISSUE THREAD

**Issue by joda-joda** [morpheus65535/bazarr#919] opened 2020-04-10 02:49 UTC
**Describe the bug**
Everything in bazarr is working just fine except the bulk download button (download wanted subtitles).

**To Reproduce**
Just press "Download wanted subtitles" button.

**Expected behavior**
Subtitles for everything!

**Software (please complete the following information):**
 - Bazarr Ver. 0.8.4.2 
 - Radarr Ver. 0.2.0.1480
 - Sonarr Ver. 2.0.0.5344
 - OS: Linux 5.6.3 (bazarr, radarr, sonarr etc. in docker using linuxserver.io dockers(network_mode: "host", no userns-remap)

**Additional context**
Tried two fresh setups, both ended up the same way.

$ docker logs bazarr
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/bottle.py", line 866, in _handle
    return route.call(**args)
  File "/app/bazarr/bazarr/../libs/bottle.py", line 1744, in wrapper
    rv = callback(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 133, in wrapper
    return func(*a, **ka)
  File "/app/bazarr/bazarr/main.py", line 1191, in wanted_search_missing_subtitles_list
    scheduler.add_job(wanted_search_missing_subtitles, name='manual_wanted_search_missing_subtitles')
NameError: name 'wanted_search_missing_subtitles' is not defined

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4459652/bazarr.log)

**Comment by joda-joda** [comment] 2020-04-10 07:23
I left it running for a couple of hours and now that I returned it seems to be doing the bulk downloading all by itself. Some magic going on here.

**Comment by morpheus65535** [comment] 2020-04-10 13:26
Duplicate of #849 that have been fixed in 0.8.4.3 in dev branch.

**Closed by morpheus65535** 2020-04-10 13:26 UTC
