### ISSUE TITLE
cannot download subtitles from assrt?

### ISSUE THREAD

**Issue by justinluy** [morpheus65535/bazarr#1028] opened 2020-07-14 10:58 UTC
here is the debug log

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4918300/bazarr.log)

**Comment by morpheus65535** [comment] 2020-07-19 23:28
`https://api.assrt.net/v1/sub/search?token=KJZERJXFk6MwMt0EgdRinOEdpoiU9fgA&q=TheWalkingDead+S03E05&is_file=1` url is working perfectly fine for me in Bazarr and in browser (even if I reuse Bazarr user-agent). If it's still not working for you, your IP have probably been blocked by assrt (temporarily or not). HTTP 509 error code meens `Bandwidth Limit Exceeded`.

**Comment by morpheus65535** [comment] 2020-07-23 12:18
As I cannot reproduce, I'll close this issue. Reopen it if you face it again in the future.

**Closed by morpheus65535** 2020-07-23 12:18 UTC
Labels: awaiting feedback, cannot reproduce
