### ISSUE TITLE
Bazarr isn't scoring correctly (giving a to low score for a 100% filename match)

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#1022] opened 2020-06-21 10:05 UTC
**Describe the bug**
Bazarr gives a to low score for a 100% match on filename.

**To Reproduce**
Did a manual search on a episode and it only get's a 75% score but the filename is like 100% match. 

**Expected behavior**
Get a higher score

**Screenshots**
![image](https://user-images.githubusercontent.com/6155095/85221779-02779580-b3b7-11ea-9792-a2fd9de01bf9.png)
![image](https://user-images.githubusercontent.com/6155095/85221788-13280b80-b3b7-11ea-86a8-4848120eddea.png)

**Software (please complete the following information):**
![image](https://user-images.githubusercontent.com/6155095/85221825-57b3a700-b3b7-11ea-94b0-613bd728c036.png)

**Additional context**
This isn't the only show where it happens

**Comment by morpheus65535** [comment] 2020-06-21 13:45
Please provide a debug log so I can see based on what the scoring is done.

**Comment by TRaSH-** [comment] 2020-06-21 15:18
someone told me i don't need to keep debug logs running ;)

https://pastebin.com/f6tWpXHc

**Comment by morpheus65535** [comment] 2020-06-21 16:29
That's strange, it should match. I'll try to reproduce.

**Comment by TRaSH-** [comment] 2020-06-22 16:25
had also a few other shows where it happens,

**Comment by morpheus65535** [comment] 2020-06-24 10:44
Well that's strange... it works fine for me... :-/

![image](https://user-images.githubusercontent.com/5130500/85541474-063d2f00-b5e6-11ea-8e42-e80fe53494fd.png)

**Comment by TRaSH-** [comment] 2020-06-25 19:07
updated to the latest dev still the same result
![image](https://user-images.githubusercontent.com/6155095/85783616-c5e5ca00-b727-11ea-8161-42d20781281f.png)

**Comment by morpheus65535** [comment] 2020-06-26 01:01
The fix I was referring to on Discord was about the subtitles upload dialog cosmetic issue.

I can't reproduce this one. The same release give me a 100% searching for Dutch on OpenSubtitles.

**Comment by TRaSH-** [comment] 2020-06-26 04:11
Could it be a issue with the database ?
Every time I try and test it I get the same low score.
I noticed a few errors when I start the container something about MySQL tables

**Comment by morpheus65535** [comment] 2020-06-26 11:01
You can try to remove the shows from Sonarr, let Bazarr sync and re-import the shows in Sonarr. Just to make sure you have the proper metadata. Next step would be to delete bazarr.db but I don't think it will fix anything if previous step didn't do it.

**Comment by TRaSH-** [comment] 2020-06-26 18:30
series with years in it seems to have issues

**Comment by TRaSH-** [comment] 2020-07-02 02:55
@morpheus65535 
Just a ping and a heads up.
Yesterday I did a clean database,
Couldn't test yet because opensubtitles API didn't return any results at all.
Perhaps a hiccup.
But could you test with a year in the series title

**Comment by TRaSH-** [comment] 2020-07-03 18:19
this is the results after a clean library
![image](https://user-images.githubusercontent.com/6155095/86491201-67919a80-bd6a-11ea-9f51-a062dd05df84.png)

**Comment by morpheus65535** [comment] 2020-07-03 18:21
I guess the problem is really with the name in the series name. I'll try to test it this afternoon, I didn't forget you! ;-)

**Comment by TRaSH-** [comment] 2020-07-03 18:57
![image](https://user-images.githubusercontent.com/6155095/86492312-079cf300-bd6e-11ea-9959-a9ac4485824e.png)

did a test on my test setup,
seems that bazarr fails when theirs a year in the title/series folder
in my opinion that shouldn't weight that heavy if the year is correct,
Being you also got MacGyver (2016) and Magnum.
And Sonarr has the option for adding they year
![image](https://user-images.githubusercontent.com/6155095/86492523-b7726080-bd6e-11ea-95ff-a9f27803ac8c.png)

**Comment by morpheus65535** [comment] 2020-07-03 19:56
As we discuss on Discord, OpenSubtitles.org return year 2020 for Batwoman. As it doesn't match with the year in directory name, subliminal lower the score accordingly. My recommandation would be to contact OS and make them correct the data returned.

**Comment by morpheus65535** [comment] 2020-07-03 20:06
Here's the json returned for a single subtitles matching Batwoman episode. Look at the `MovieYear`.
[data.txt](https://github.com/morpheus65535/bazarr/files/4871307/data.txt)

**Comment by morpheus65535** [comment] 2020-07-05 12:37
I'll close this issue for now as it seems related to an error in data returned by OpenSubtitles.org API. Feel free to reopn it if the change you requested in OS forum doesn't fix your issue.

**Closed by morpheus65535** 2020-07-05 12:37 UTC
