### ISSUE TITLE
Particular filename(s) crashes "Search for wanted subtitles" task

### ISSUE THREAD

**Issue by Darkstylo** [morpheus65535/bazarr#403] opened 2019-04-18 10:50 UTC
**Describe the bug**
Once it processes a certain episode, the task crashes.

**To Reproduce**
1. Start "Search for wanted subtitles"
2. Once it processes the episode in conflict, the task crashes.

**Expected behavior**
N/A

**Screenshots**
N/A

**Software:**
 - Bazarr: v0.7.4
 - Radarr version v0.2.0.1293
 - Sonarr version v3.0.1.441
 - OS: Linux

I will provide debug logs on discord

**Comment by morpheus65535** [comment] 2019-04-18 10:52
@Panni the issue is with subliminal_patch. The user will send is debug log to you in private.

**Comment by pannal** [comment] 2019-04-21 00:58
That's not an issue with subliminal_patch, but with subliminal's sanitize function. It seems like there's empty data passed.

I'll need more info about the episode in question to make something out of that.

**Comment by pannal** [comment] 2019-04-21 01:29
Will be fixed in an upcoming version.

**Comment by pannal** [comment] 2019-04-21 01:29
https://github.com/pannal/Sub-Zero.bundle/commit/ce2296c95db73c712fd60187535105df62287029

**Comment by morpheus65535** [comment] 2019-04-30 10:19
Is this fix since last update to dev branch 2 days ago?

**Comment by Darkstylo** [comment] 2019-05-01 06:16
@morpheus65535 it seems to be fixed!

**Comment by morpheus65535** [comment] 2019-05-01 10:03
Thanks!

**Closed** 2019-05-01 10:03 UTC
Labels: awaiting feedback, bug, library related
