### ISSUE TITLE
issue with bazarr not live updating shows from sonarr 

### ISSUE THREAD

**Issue by mhmm555** [morpheus65535/bazarr#1985] opened 2022-11-08 15:35 UTC
hello my issue is that bazarr will not live update my shows from sonarr it only works with manual sync and possibly the scheduler which i havent tried but not live update, the only logs that i have are bellow

BAZAR trying to connect to Sonar SignalR feed...

the terminal output is bellow

----------------------------------------------------------------------------------------------------------------------------------------------------

```
Bazarr starting...

2022-11-08 09:05:17,135 - root (700077237000) : INFO (signalr_client:50) - BAZARR trying to connect to Sonarr SignalR feed...

2022-11-08 09:05:17,135 - root (7ff84f6bf4c0) : INFO (server:64) - BAZARR is started and waiting for request on http://0.0.0.0:6767/

Exception in thread Thread-4:

Traceback (most recent call last):

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner

    self.run()

  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run

    self._target(*self._args, **self._kwargs)

  File "/Applications/bazarr/bazarr/app/signalr_client.py", line 54, in start

    self.connection.start()

  File "/Applications/bazarr/bazarr/../libs/signalr/_connection.py", line 55, in start

    listener = self.__transport.start()

  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_auto_transport.py", line 28, in start

    return self.__transport.start()

  File "/Applications/bazarr/bazarr/../libs/signalr/transports/_ws_transport.py", line 34, in start

    self.ws = create_connection(ws_url,

  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 606, in create_connection

    websock.connect(url, **options)

  File "/Applications/bazarr/bazarr/../libs/websocket/_core.py", line 253, in connect

    self.handshake_response = handshake(self.sock, *addrs, **options)

  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 57, in handshake

    status, resp = _get_resp_headers(sock)

  File "/Applications/bazarr/bazarr/../libs/websocket/_handshake.py", line 143, in _get_resp_headers

    raise WebSocketBadStatusException("Handshake status %d %s", status, status_message, resp_headers)

websocket._exceptions.WebSocketBadStatusException: Handshake status 400 Bad Request
```

**To Reproduce**
1. Go to 'sonarr'
2. Click on 'download series'
3. go to bazarr "shows not showing up in the series section of bazarr after download from sonarr"

**Expected behavior**
shows live updating in bazarr when i download them from sonarr and bazarr automatically downloading the subtitles

**Software (please complete the following information):**
 - Bazarr: 1.1.2
 - Sonarr version 3.0.9.1549
 - OS: mac OS 13 (ventura)

**Additional context**

**Comment by morpheus65535** [comment] 2022-11-08 16:56
I can't reproduce. Probably related to something wrong with your Sonarr instance. Just to be sure you can try to update to latest beta version where I've updated websocket module to latest version.

**Comment by morpheus65535** [comment] 2022-11-08 18:03
You chnage branch to development in Settings-->General and force an update of Bazarr in System-->Tasks.

**Comment by morpheus65535** [comment] 2022-11-09 00:56
Of course it's related. SignalR/Websocket is the live connection that Bazarr establish with Sonarr to get live update (the same way the Sonarr UI does). I ask for Sonarr trace log covering the period  where Bazarr raise the 400 http error exception. Until we can demonstrate that the issue is on Bazarr side, this error is considered as being provided by Sonarr.

**Comment by morpheus65535** [comment] 2022-11-09 01:08
Yes, I need the Sonarr log (level: trace). It needs to cover the period while you start Bazarr and get the error in Bazarr.

**Comment by morpheus65535** [comment] 2022-11-09 01:28
Hmmm doesn't seems to include SignalR info in trace log. Can you do it gain at debug level please?

**Comment by morpheus65535** [comment] 2022-11-09 01:45
There's nothing in there related to SignalR... Did you restart Bazarr while doing those log files?

**Comment by morpheus65535** [comment] 2022-11-09 20:45
> you want me to test 1.1.3-beta.14 or the next one?

beta.15 that will be released during the night.

**Comment by morpheus65535** [comment] 2022-11-11 01:59
This one should do it.

**Comment by morpheus65535** [comment] 2022-11-11 15:31
Thanks for testing!

**Closed by morpheus65535** 2022-11-11 15:31 UTC
Labels: bug, library related, awaiting feedback, fixed

**Comment by morpheus65535** [comment] 2023-04-11 02:52
Nothing as changed, this fix is still there in latest beta. You'll have to reproduce the issue with debug logging and open a new issue.
