### ISSUE TITLE
Implement - Series page listing next/previous

### ISSUE THREAD

**Issue by Zeusy123** [morpheus65535/bazarr#16] opened 2017-11-29 12:35 UTC
Ive over 400 series, sereis page does take some time and memory to load with such numbers, perhaps pagenation should be implemented like you did with log page?

Actually on further thought, perhaps an alphabet along the bottom also???
Option to show 25/50/100 per page?

**Comment by morpheus65535** [comment] 2017-11-29 13:07
Duplicate of #5

**Closed** 2017-11-29 13:07 UTC
Labels: duplicate
