### ISSUE TITLE
Notification settings not saving after removing Discord

### ISSUE THREAD

**Issue by Zxurian** [morpheus65535/bazarr#2005] opened 2022-12-06 21:36 UTC
**Describe the bug**
Unable to save a removal of Discord notification. Removing it from the UI works, but when I attempt to save, I get a flyout of
```
Error 500
You have disconnected from the server
```

I tested changing the UI Page size and saving it and it saved without issue, so only occuring when I try to remove Discord notification then save.

**To Reproduce**
1. Have discord notifications setup
2. Click on Settings -> Notifications
3. Click on the Discord notification
4. Click the remove button
5. click save at the top

**Expected behavior**
It should save the removal of discord notifications

**Screenshots**
![image](https://user-images.githubusercontent.com/573371/206028123-87783632-6874-492e-b79f-4d7e1ef709d3.png)

**Software (please complete the following information):**
 - Bazarr: 1.1.3
 - Radarr version n/a
 - Sonarr version 3.0.9.1549
 - OS: Linux-5.19.17-Unraid-x86_64-with
 - Running as docker container under Unraid.

**Additional context**
Found #1594 when seeing if it was an existing issue but the problem isn't exactly the same

**Comment by morpheus65535** [comment] 2022-12-07 11:22
Issue confirmed on my side:
```
Traceback (most recent call last):
  File "/app/bin/bazarr/../libs/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/app/bin/bazarr/../libs/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/bin/bazarr/../libs/flask_restx/api.py", line 405, in wrapper
    resp = resource(*args, **kwargs)
  File "/app/bin/bazarr/../libs/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/bin/bazarr/../libs/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/bin/bazarr/api/utils.py", line 30, in wrapper
    return actual_method(*args, **kwargs)
  File "/app/bin/bazarr/api/system/settings.py", line 105, in post
    item = json.loads(item)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

@LASER-Yi can you look into it please? Same issue as languages profiles.

**Comment by KevinBoone90** [comment] 2022-12-16 10:29
Having the same issues adding or removing a Discord Notification Setting

**Comment by morpheus65535** [comment] 2022-12-16 11:08
Fixed in dev branch.

**Comment by KevinBoone90** [comment] 2022-12-16 11:22
Awesome, works perfectly!

**Comment by morpheus65535** [comment] 2022-12-16 11:23
Thanks for the feedbck!

**Closed by morpheus65535** 2022-12-16 11:23 UTC
Labels: bug, priority:high, awaiting feedback, fixed

**Comment by Churator** [comment] 2023-01-30 09:47
Is it still on Dev branch only? or migrated to master ? (not sure how to check myself)

**Comment by morpheus65535** [comment] 2023-01-30 11:14
> Is it still on Dev branch only? or migrated to master ? (not sure how to check myself)

It's in master since 1.1.4.
