### ISSUE TITLE
Job "Upgrade previously downloaded Subtitles (trigger: interval[3:00:00], next run at: 2021-03-26 15:34:33 CET)" raised an exception

### ISSUE THREAD

**Issue by lukjod** [morpheus65535/bazarr#1345] opened 2021-03-26 11:43 UTC
Similiar as previous one
log:
`Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
  retval = job.func(*job.args, **job.kwargs)
 File "/app/bazarr/bazarr/get_subtitle.py", line 1308, in upgrade_subtitles
  result = download_subtitle(path_mappings.path_replace(episode[\video_path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 177, in download_subtitle
  downloaded_subtitles = download_best_subtitles({video}, language_set, int(min_score), hi,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 820, in download_best_subtitles
  subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 462, in list_subtitles
  for provider, provider_subtitles in executor.map(self.list_subtitles_provider, self.providers,
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
  yield fs.pop().result()
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
  return self.__get_result()
 File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
  raise self._exception
 File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
  result = self.fn(*self.args, **self.kwargs)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 448, in list_subtitles_provider
  provider_subtitles = super(SZAsyncProviderPool, self).list_subtitles_provider(provider, video, languages)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 148, in list_subtitles_provider
  if not provider_registry[provider].check(video):
AttributeError: \NoneType\ object has no attribute \check\`

**Comment by mvanbaak** [comment] 2021-03-26 11:45
Duplicate of #1344

**Closed** 2021-03-26 12:20 UTC
