### ISSUE TITLE
Assrt provider rate limited error

### ISSUE THREAD

**Issue by ycflash** [morpheus65535/bazarr#1953] opened 2022-09-22 03:19 UTC
Hi, assrt provider has a query rate limit 5/min as (refer: [assrt api doc](http://assrt.net/api/doc)). 

error like this: `Throttling assrt for 10 minutes, until 22/09/22 10:52, because of: HTTPError. Exception info: '509 Server Error: for url: https://api.assrt.net/v1/sub/search?token=<token>&q=How+It%27s+Made+S07E01&is_file=1'`

Is a query rate function possible on this provider?

**Comment by morpheus65535** [comment] 2022-09-28 14:17
From https://assrt.net/api/doc#api%E9%85%8D%E9%A2%9D (Google translate):

> API quota
> For the principle of fair use, the initial API quota is 20 times per minute . Note that each token and each IP share the same quota. If user A and user B use different tokens, but the IP is the same, they can use a total of 20 quotas per minute; similarly, users with different IPs use the same token You can only use a total of 20 API requests per minute.

Based on that, I'll add some pause to the provider to prevent making more than 20 queries to the API. Please test the upcoming beta and confirm if it fixes your issue.

**Comment by ycflash** [comment] 2022-09-29 14:35
My newly create account on assrt shows only 5 queries per minute, maybe the site changed default quota 5 queries/minute.

**Comment by morpheus65535** [comment] 2022-09-30 01:15
> Would an option field to allow user specify quota number a better solution?

That's more complicated. I'm not speakign the language, maybe you can get in relation with the admins and try to clarify this maximum number of queries per minutes?

**Comment by ycflash** [comment] 2022-09-30 02:41
@morpheus65535 OK, I'll try to contact assrt site admin, will feedback later. Thanks!

**Comment by ycflash** [comment] 2022-10-08 15:00
Failed to get response from assrt admin..

As assrt api doc indicates ( http://assrt.net/api/doc#userquota ), query rate can be obtained by api: 
`curl "https://api.assrt.net/v1/user/quota?token=TOKEN"`
here is my result:
`{"user":{"result":"succeed","action":"quota","quota":5},"status":0}`

If an option to allow user his query rate to assrt is not currently applicable, maybe lower down to 5 is a more simple solution? 

Thanks.

**Comment by morpheus65535** [comment] 2022-10-10 01:55
I've added a call to get the proper maximum number of requests per minute. It should be fine in upcoming beta. Can you test and confirm please?

**Comment by ycflash** [comment] 2022-10-10 06:24
Great!  
I'll try to have a test, and will feedback later.

**Comment by ycflash** [comment] 2022-10-12 05:20
I have tested v1.1.2-beta.20, it dosen't show error detail,  can't tell what error I'm facing..
`Using assrt again after 10 minutes, (disabled because: HTTPError)`

**Comment by morpheus65535** [comment] 2022-10-12 10:09
This is the part where the provider is removed from the throttled providers. You have to look earlier to see what caused this exception.

**Comment by ycflash** [comment] 2022-10-12 14:29
logs filtered by 'assrt' show as bellow. bazarr v1.1.2-beta.20 started about a few minutes befroe 12/10/2022 01:41:08.
```
12/10/2022 01:41:08|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
12/10/2022 05:03:13|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/12 05:13, because of: KeyError. Exception info: 0|
12/10/2022 06:49:07|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: KeyError)|
12/10/2022 07:08:56|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
12/10/2022 07:38:29|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
12/10/2022 07:39:58|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
12/10/2022 07:53:23|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/12 08:03, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
12/10/2022 10:12:37|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
12/10/2022 10:51:43|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/12 11:01, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
12/10/2022 13:12:37|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
12/10/2022 13:34:00|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/12 13:44, because of: HTTPError. Exception info: '509 Server Error:  for url: https://api.assrt.net/v1/sub/search?token=UblWobOcCv5Nd1MnFldqVktvwEXB7pu6&q=Minuscule+S02E32&is_file=1'|
12/10/2022 14:10:29|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
12/10/2022 16:22:41|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
12/10/2022 16:23:03|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...|
12/10/2022 16:23:23|INFO    |root                            |Throttling assrt for 1 hour, until 22/10/12 17:23, because of: ReadTimeout. Exception info: ReadTimeoutError("HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10)")|
12/10/2022 19:12:37|INFO    |root                            |Using assrt again after 1 hour, (disabled because: ReadTimeout)|
12/10/2022 19:51:55|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/12 20:01, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
12/10/2022 22:12:37|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
```
I'll give it a try with debug log enabled, and see what will come.

**Comment by ycflash** [comment] 2022-10-13 02:53
```
HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=10), retrying in 5 seconds...
Throttling assrt for 10 minutes, until 22/10/13 10:28, because of: ValueError. Exception info: 'sleep length must be non-negative'
```
When I try curl "https://api.assrt.net/v1/sub/search?token=<token>&q=How+It%27s+Made+S07E01&is_file=1" in shell, return result ok, not read timeout err.

**Comment by morpheus65535** [comment] 2022-10-13 12:34
I've made some improvements that will be part of upcoming beta. Can you test it please?

**Comment by ycflash** [comment] 2022-10-13 12:56
OK, I'll have a test when it's available.

**Comment by ycflash** [comment] 2022-10-16 14:28
Tested v1.1.2 release, error log filtered by keyword 'assrt' shows some KeyError, is it about api key of assrt site?
```
$ grep assrt ~/Downloads/bazarr.log  -i
16/10/2022 14:39:38|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
16/10/2022 17:37:28|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/16 17:47, because of: KeyError. Exception info: 0|
16/10/2022 19:05:18|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: KeyError)|
16/10/2022 20:37:02|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/16 20:47, because of: KeyError. Exception info: 0|
16/10/2022 22:18:33|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: KeyError)|
```

**Comment by morpheus65535** [comment] 2022-10-17 03:13
> Tested v1.1.2 release, error log filtered by keyword 'assrt' shows some KeyError, is it about api key of assrt site?

Those KeyError are caused by the API actually returning no subtitles details. Bazarr try to access directly the first one of none so it raise an exception. I can try to fix it but it won't be elegant. It will not throttle provider anymore but won'T be able to download the subtitles either.

**Comment by morpheus65535** [comment] 2022-10-17 03:14
Please test upcoming beta and provide feedback.

**Comment by ycflash** [comment] 2022-10-19 03:44
tested 1.1.3-beta.0, error log frequency seams reduced.
```
19/10/2022 05:29:23|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
19/10/2022 05:51:58|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/19 06:01, because of: HTTPError. Exception info: '509 Server Error:  for url: https://api.assrt.net/v1/sub/search?token=<token>&q=007%EF%BC%9A%E5%A5%B3%E7%8E%8B%E5%AF%86%E4%BD%BF+1969&is_file=1'|
19/10/2022 08:29:23|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
19/10/2022 09:17:38|INFO    |root                            |Throttling assrt for 10 minutes, until 22/10/19 09:27, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
19/10/2022 10:07:51|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
```

**Comment by ycflash** [comment] 2022-10-19 03:56
As assrt api doc says (translate to english by google: http://assrt.net/api/doc#errors

`The developer should judge the status value in the reply message. If it is not zero, it means that an error has occurred. It is important to note that errors sometimes affect HTTP status codes, with APIError being 200 and ClientFail and ServerFail being 4xx and 5xx respectively.`

status code should be parsed instead of http error code. eg. status 30900 should be 'Quota Exceeded'

```
$ curl 'https://api.assrt.net/v1/sub/search?token=<token>&q=007%EF%BC%9A%E5%A5%B3%E7%8E%8B%E5%AF%86%E4%BD%BF+1969&is_file=1'
{"sub":{"action":"search","keyword":"007\uff1a\u5973\u738b\u5bc6\u4f7f 1969","result":"succeed","subs":[{"native_name":"","upload_time":"2013-04-16 04:58:25","vote_score":0,"videoname":"007\u7cfb\u5217\u7b2c06\u96c6\uff1a\u5973\u738b\u5bc6\u4f7f(\u94c1\u91d1\u521a\u52c7\u7834\u96ea\u5c71\u5821).On.Her.Majesty's.Secret.Service.1969.BluRay.720p.DTS.x264-CHD","lang":{"langlist":{"langeng":true,"langchs":true,"langdou":true},"desc":"\u82f1 \u7b80 \u53cc\u8bed"},"id":233216,"revision":0,"subtype":"\u5176\u4ed6"},{"native_name":"007\uff1a\u5973\u738b\u5bc6\u4f7f\u7ec8\u6781\u6536\u85cf\u7248","upload_time":"2007-04-13 08:05:00","vote_score":0,"videoname":"On.Her.Majestys.Secret.Service.1969.007.ULTiMATE.EDiTiON.iNTERNAL.DVDRiP.X264.DTS-KiSS","lang":{"langlist":{"langeng":true,"langchs":true},"desc":"\u82f1 \u7b80"},"id":58254,"revision":0,"subtype":"Subrip(srt)"}]},"status":0}
$ curl 'https://api.assrt.net/v1/sub/search?token=<token>&q=007%EF%BC%9A%E5%A5%B3%E7%8E%8B%E5%AF%86%E4%BD%BF+1969&is_file=1'
{"status":30900,"errmsg":"you are exceeding request limits"}
```

**Comment by morpheus65535** [comment] 2022-10-29 15:27
Should be improved in next beta.

**Comment by ycflash** [comment] 2022-10-31 03:49
Good, I'll have a test when ready.

**Comment by ycflash** [comment] 2022-11-07 08:29
tested 1.1.3-beta.12, seams not logging detailed status code:

`Throttling assrt for 10 minutes, until 22/11/07 15:48, because of: HTTPError. Exception info: '493 Client Error: for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='`

**Comment by morpheus65535** [comment] 2022-11-09 21:14
I've been lazy with my previous fix. This one should make it. Could you test upcoming beta please?

**Comment by ycflash** [comment] 2022-11-10 07:57
Thank you for your active hardworking on this. I'm having 1.1.3-beta.15 running now, will feedback later.

**Comment by ycflash** [comment] 2022-11-15 14:50
throttled a lot, and even quota number returned is 0. here are some sample logs:
```
15/11/2022 15:16:57|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
15/11/2022 15:50:15|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 16:00, because of: ProviderError. Exception info: "Cannot get user request quota per minute from provider: {'user': {'result': 'succeed', 'quota': 0, 'action': 'quota'}, 'status': 0}"|
15/11/2022 15:50:21|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 16:00, because of: HTTPError. Exception info: '509 Server Error:  for url: https://api.assrt.net/v1/sub/search?token=<token>&q=%E5%86%B3%E6%88%98%E7%8C%A9%E7%90%83+1973&is_file=1'|
15/11/2022 16:00:21|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
15/11/2022 17:07:07|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 17:17, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
15/11/2022 18:16:58|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
15/11/2022 19:42:02|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
15/11/2022 19:52:33|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
15/11/2022 19:52:36|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Max retries exceeded with url: /v1/sub/search?token=<token>&q=007%EF%BC%9A%E5%A4%AA%E7%A9%BA%E5%9F%8E+1979&is_file=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7fb0786391b0>, 'Connection to api.assrt.net timed out. (connect timeout=15)')), retrying in 5 seconds...|
15/11/2022 19:55:18|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
15/11/2022 19:55:39|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
15/11/2022 20:46:07|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 20:56, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
15/11/2022 20:56:08|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
15/11/2022 21:00:31|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
15/11/2022 21:03:14|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 21:13, because of: KeyError. Exception info: 0|
15/11/2022 21:16:57|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: KeyError)|
15/11/2022 21:59:09|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/15 22:09, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
15/11/2022 22:09:10|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
```

**Comment by morpheus65535** [comment] 2022-11-18 20:41
I've fixed one small error I made. Can you test upcoming beta please?

**Comment by ycflash** [comment] 2022-11-21 14:37
I've test 1.1.3-beta.21, some throttled logs as bellow. Is it better to show detailed json respone from api server, which would tell us what really happened?
```
21/11/2022 00:19:44|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 03:11:33|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 03:21, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 03:21:33|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 04:37:27|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 04:47, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<toke>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 05:33:54|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 06:19:02|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 06:29, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 06:29:03|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 07:33:17|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 07:43, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 08:33:55|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 09:19:52|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 09:29, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 09:29:53|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 10:29:18|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 10:39, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 11:33:54|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 12:18:55|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 12:28, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 12:28:55|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 13:28:32|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 13:38, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 13:38:35|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 15:18:58|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 15:28, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 15:28:58|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 16:35:03|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 16:45, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 17:33:54|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 18:01:25|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
21/11/2022 18:19:34|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 18:29, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 18:29:34|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 18:38:43|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
21/11/2022 18:45:42|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
21/11/2022 19:25:32|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 19:35, because of: HTTPError. Exception info: '503 Server Error: Service Temporarily Unavailable for url: https://api.assrt.net/v1/sub/search?token=<token>&q=Desperate+Housewives+S05E06&is_file=1'|
21/11/2022 20:33:54|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|
21/11/2022 20:53:53|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
21/11/2022 20:53:53|WARNING |retry.api                       |HTTPSConnectionPool(host='api.assrt.net', port=443): Read timed out. (read timeout=15), retrying in 5 seconds...|
21/11/2022 21:19:41|INFO    |root                            |Throttling assrt for 10 minutes, until 22/11/21 21:29, because of: HTTPError. Exception info: '493 Client Error:  for url: http://assrt.net/download/error/L29udGhlZmx5LzA2MjgxOC8tLzEvW+eHpuWLldCl5L+LXS5PdmVyLlRoZS5IZWRnZS4yMDA2Llh2aUQuQUMzLjJBVURJTy5DRDEtV0FGLkNocy5zcnQ='|
21/11/2022 21:29:42|INFO    |root                            |Using assrt again after 10 minutes, (disabled because: HTTPError)|

```

**Comment by ycflash** [comment] 2022-12-07 05:25
don't see any cf related response of my test.  But, thank you anyway. thanks！

**Comment by morpheus65535** [comment] 2024-11-12 01:39
@ycflash I see downloads from this provider. Is this still an issue?

**Comment by ycflash** [comment] 2024-11-12 07:17
not working with 1.4.5 :
`Throttling assrt for 10 minutes, until 24/11/12 15:26, because of: TypeError. Exception info: "''bool' object is not subscriptable' ~ assrt.py@128"`

**Comment by morpheus65535** [comment] 2024-11-18 04:06
I fixed what seems to be long standing typos in this provider. Let me know if upcoming beta helps.

**Comment by morpheus65535** [comment] 2024-12-21 01:35
No news, good news!

**Closed by morpheus65535** 2024-12-21 01:35 UTC
Labels: bug, awaiting feedback, fixed
