### ISSUE TITLE
Exeption in /api/search_wanted_movies

### ISSUE THREAD

**Issue by Coollision** [morpheus65535/bazarr#1210] opened 2020-12-06 11:24 UTC
**Describe the bug:**
I think I have an issue that is kind of similar to #1122 
Exception on /api/search_wanted_movies [GET]

**To Reproduce**
1. Go to 'wanted => movies'
2. Click on 'search All'

**Expected behavior**
finding all missing movie subtitles

**Current behavior**
Search for missing subtitle halts after error

**Software**
 - Bazarr: [0.9.0.8] docker image: linuxserver/bazarr:development
 - Radarr version [3.0.0.4235]
 - Sonarr version [3.0.4.1023]
 - OS: k3s

**Additional context**
error found in logs:
Message
Exception on /api/search_wanted_movies [GET]
Exception
Traceback (most recent call last):
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1949, in full_dispatch_request
  rv = self.dispatch_request()
 File "/app/bazarr/bazarr/../libs/flask/app.py", line 1935, in dispatch_request
  return self.view_functions[rule.endpoint](**req.view_args)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 458, in wrapper
  resp = resource(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask/views.py", line 89, in view
  return self.dispatch_request(*args, **kwargs)
 File "/app/bazarr/bazarr/../libs/flask_restful/__init__.py", line 573, in dispatch_request
  resp = meth(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 62, in wrapper
  return actual_method(*args, **kwargs)
 File "/app/bazarr/bazarr/api.py", line 1754, in get
  wanted_search_missing_subtitles_movies()
 File "/app/bazarr/bazarr/get_subtitle.py", line 997, in wanted_search_missing_subtitles_movies
  wanted_download_subtitles_movie(movie[\path\], i, count_movies)
 File "/app/bazarr/bazarr/get_subtitle.py", line 933, in wanted_download_subtitles_movie
  result = download_subtitle(path_mappings.path_replace_movie(movie[\path\]),
 File "/app/bazarr/bazarr/get_subtitle.py", line 168, in download_subtitle
  downloaded_subtitles = download_best_subtitles({video}, language_set, int(min_score), hi,
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 796, in download_best_subtitles
  subtitles = pool.download_best_subtitles(pool.list_subtitles(video, languages - video.subtitle_languages),
 File "/app/bazarr/bazarr/../libs/subliminal_patch/core.py", line 360, in download_best_subtitles
  matches = s.get_matches(video)
 File "/app/bazarr/bazarr/../libs/subliminal_patch/providers/subsunacs.py", line 108, in get_matches
  if isinstance(video, Movie) and (self.num_cds > 1 or \cd\ in guess_filename):
TypeError: \>\ not supported between instances of \NoneType\ and \int\

**Comment by morpheus65535** [comment] 2020-12-06 14:07
@josdion this one seems to be related to a fix you made to subsunacs provider. Can you take a look please?

**Comment by interlark** [comment] 2020-12-06 14:27
Looks like the issue is in subsunacs provider, you can temporary turn it off and ask provider's author to update the code.

**Comment by Coollision** [comment] 2020-12-06 15:07
@morpheus65535 @interlark thanks for the help, it seems to be running smoothly now!

**Comment by morpheus65535** [comment] 2020-12-06 15:48
Ok, I'll close it but feel free to re-open if you face the issue again.

**Closed by morpheus65535** 2020-12-06 15:48 UTC
Labels: help wanted
