### ISSUE TITLE
Provider 'opensubtitlescom' is discarded

### ISSUE THREAD

**Issue by L2v2P** [morpheus65535/bazarr#1798] opened 2022-04-11 08:54 UTC
**Describe the bug**
For the last week or so I can't download any subtitels for https://www.opensubtitles.com/ anymore. When I switch the log level to DEBUG I can see many occurrences (one for each of the subtitles found) of "Provider 'opensubtitlescom' is discarded". I have no idea why opensubtitles is discarded. Can you shed some light on it?

**Comment by halali** [comment] 2022-04-11 10:19
Duplicate of #1793

**Closed** 2022-04-11 10:19 UTC

**Comment by morpheus65535** [comment] 2022-04-11 10:24
Anyway, without a debug log, there's no way to tell what's your issue.
