### ISSUE TITLE
Task interval settings

### ISSUE THREAD

**Issue by tms5d** [morpheus65535/bazarr#422] opened 2019-05-01 15:45 UTC
Please make the 'system --> tasks' interval configurable, or at least change the timing of 'Update series list from Sonarr | every 60 seconds' to something ike 5 minutes or so.

With this setting on 60 seconds, my (NAS) drives keep spinning 24/7. Thanks!

![image](https://user-images.githubusercontent.com/26542244/57025980-ece66000-6c38-11e9-9e7d-d9ae90d1ab45.png)

**Comment by morpheus65535** [comment] 2019-05-01 16:00
Duplicate of #242.

**Closed by morpheus65535** 2019-05-01 16:00 UTC
