### ISSUE TITLE
Translating Subtitles Doesn't Work

### ISSUE THREAD

**Issue by DanAykroyd256** [morpheus65535/bazarr#1672] opened 2022-01-09 06:00 UTC
**Describe the bug**
When selecting an English subtitle and going to “Tools” to translate to Spanish (haven't tried other languages since I don't care about them, but this seems general), nothing happens, the subtitle doesn't get translated and I get an “Exception on /api/subtitles [PATCH]” in the log, with “IndexError: list index out of range” in stack details (see full details at the bottom). This happened for any subtitless I have tried

**To Reproduce**
1. Go to Movie
2. Click on Tools and select an english subtitle with its checkbox
3. Select Translate from dropdown actions and translate to Spanish

**Expected behavior**
Subtitle gets translated

**Screenshots**
<img width="368" alt="Screen Shot 2022-01-09 at 02 56 15" src="https://user-images.githubusercontent.com/64184474/148671083-d6dfedc7-b570-40e4-84d8-09809feba306.png">

**Software (please complete the following information):**
 - Bazarr: 1.0.2
 - Radarr version 3.2.2.5080
 - OS: Windows 10

**Additional context**

**Every translation I've tried gives this exact stack trace error**
`Stack traceback×Close
Traceback (most recent call last):

  File "c:\\program files (x86)\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

  File "c:\\program files (x86)\\bazarr\\bazarr\\../libs\\flask\\app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "c:\\program files (x86)\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 467, in wrapper

    resp = resource(*args, **kwargs)

  File "c:\\program files (x86)\\bazarr\\bazarr\\../libs\\flask\\views.py", line 89, in view

    return self.dispatch_request(*args, **kwargs)

  File "c:\\program files (x86)\\bazarr\\bazarr\\../libs\\flask_restful\\__init__.py", line 582, in dispatch_request

    resp = meth(*args, **kwargs)

  File "c:\\program files (x86)\\bazarr\\bazarr\\api\\utils.py", line 30, in wrapper

    return actual_method(*args, **kwargs)

  File "c:\\program files (x86)\\bazarr\\bazarr\\api\\subtitles\\subtitles.py", line 52, in patch

    result = translate_subtitles_file(video_path=video_path, source_srt_file=subtitles_path,

  File "c:\\program files (x86)\\bazarr\\bazarr\\utils.py", line 492, in translate_subtitles_file

    line.plaintext = translated_lines_list[i]

IndexError: list index out of range `

**Comment by morpheus65535** [comment] 2022-01-09 14:46
I've just tested out and I can't reproduce. I've translated subtitles to Spanish and other languages without any issue. Are you using stuff like pihole that would prevent Bazarr from reaching Google Translate service?

**Comment by DanAykroyd256** [comment] 2022-01-09 19:29
Hi morpheus, thanks for taking the time to test this.

No, I'm currently running Bazarr on a spare laptop directly connected to the router, without any ad blocker in between.

Is there anything I can provide to help further troubleshoot this? This happens with any subtitle I try, so it's not only an isolated case. Here is a short video showing what's happening.

![2022-01-09_16-20-26 (1)](https://user-images.githubusercontent.com/64184474/148697659-b49bfb67-29c1-4740-952f-e4e4ebcda659.gif)

**Comment by morpheus65535** [comment] 2022-01-10 00:18
Send me the source subtitles you use for translation.

**Comment by DanAykroyd256** [comment] 2022-01-10 05:08
Thanks morpehus.

Of all the subtitles I had to translate, I have only one that found that worked sucesfully, updates the UI with the resulted subtitle ready and the subtitle (.srt) is properly available on disk. I'm including it in the zip file.

All the others subtitles (I'm attaching 3 in total) give up the same error; two translating from english to spanish and one trying to go from spanish to english.

The good thing, with that subtitled that worked, is that now we know it's not an issue with something interrupting the connection to Google Translate. I have no idea why the other subtitles are giving the “Out of index” error, but perhaps you can find something there, specially comparing with the subtitle that worked that I'm also attaching.

Thanks again for looking into this, I really appreciate it.

<img width="537" alt="Screen Shot 2022-01-10 at 02 08 13" src="https://user-images.githubusercontent.com/64184474/148720642-279495df-05b2-42b0-a057-e0ac8b3dec35.png">

[Translation Errors Subtitles.zip](https://github.com/morpheus65535/bazarr/files/7836887/Translation.Errors.Subtitles.zip)

**Comment by DanAykroyd256** [comment] 2022-01-14 00:40
Hi @morpheus65535,

Did you get a chance to try translating this subtitles? Do you want me to send the .zip file through some other means?

Thanks again.

**Comment by morpheus65535** [comment] 2022-01-14 00:42
@DanAykroyd256 don't worry, I still have this on my to do list. Should find time to test this this weekend. Sorry for the delay, new year beginning at work is crazy.

**Comment by morpheus65535** [comment] 2022-01-16 15:47
@DanAykroyd256 all 3 subtitles are malformed. You can't have an entry without text to show:
```
1
00:00:06,000 --> 00:00:12,074


2
00:01:39,466 --> 00:01:41,662
You're late. The Boss is here.
```

**Comment by morpheus65535** [comment] 2022-01-16 16:51
It should be fixed in upcoming 1.0.3-beta.12. It won't translate malformed subtitles but it will properly log an error.

**Closed by morpheus65535** 2022-01-16 16:51 UTC
Labels: cannot reproduce

**Comment by DanAykroyd256** [comment] 2022-01-18 05:16
Thanks for testing @morpheus65535! Now it makes sense…

Those empty spaces are there because the ads were removed from the subtitle by a post-processing command calling the [Subclean](https://www.npmjs.com/package/subclean) project.

Wouldn't it be possible to translate the rest of the file and leave those empty spaces untouched? If not, it would break integration for translating most of subtitles with ads removed from them from people using Sublean.

Thanks again.

**Comment by morpheus65535** [comment] 2022-01-18 11:46
> Wouldn't it be possible to translate the rest of the file and leave those empty spaces untouched? If not, it would break integration for translating most of subtitles with ads removed from them from people using Subclean.

In fact, I don't see why I would make some dirty patch that could impact proper subtitles for a script that create malformed subtitles. They should do the work properly and we wouldn't run into those issues.

On top of that, we do not encourage the use of those ads removal scripts but instead recommand that you look into the provider VIP status that would give you ads-free subtitles.

**Comment by DanAykroyd256** [comment] 2022-01-18 16:36
> They should do the work properly and we wouldn't run into those issues.

What would this be? Putting some text in those empty spaces? Precisely, the idea is to leave them blank, with the timestamp intact, so the clients playing the movie don't render them (and they don't have any problems handling that properly with these malformed subitltes)

Besides this use case for removing ads, if in any subtitles, for some reason, there is an empty text somewhere in the file, would the translation break completely? Don't you think that it would be a better user experience to handle a random blank line gracefully instead of aborting the translation fully because of its existence in the file?

Thanks.

**Comment by morpheus65535** [comment] 2022-01-18 17:14
Honestly, the srt file standard is define by a succession of 3 lines blocks. The last line can be multiple line but MUST contain text. Although some player may support an empty string, it doesn't respect the standard.

I may try to see if I can patch the libraries we use to parse subtitles files to circumvent this but I do not make promises.

**Comment by DanAykroyd256** [comment] 2022-01-18 23:37
Thanks morpheus, I hope this would be possible to achieve, as it would provide a seamless user experience for users with subtitles with empty spaces (for any reason), and I would be able to rely on the Bazarr “Tool” to translate all of them that I need to be translated; from within the same platform and leaving manual subtitle management behind.

Have a great rest of the week!

**Comment by morpheus65535** [comment] 2022-01-18 23:54
In fact this was only an issue when the first block contains an empty string. This should be fixed in upcoming beta release.

**Comment by DanAykroyd256** [comment] 2022-01-19 00:36
Great! Looking forward to it; thanks morpheus.
