### ISSUE TITLE
WebUI seems to randomly crash?

### ISSUE THREAD

**Issue by PassiveLemon** [morpheus65535/bazarr#2470] opened 2024-04-24 20:41 UTC
**Describe the bug**
After running for a while, the WebUI will become inaccessible, however, the container will still be running. If I restart the container, the UI will become accessible again. Nothing particularly of interest shows in the logs when the issue is present so it's hard to track.

**To Reproduce**
Not sure how.

**Software (please complete the following information):**
 - Bazarr: 1.4.3-beta.24
 - Radarr version 5.4.6.8723
 - Sonarr version 4.0.4.1491
 - OS: Docker

**Comment by PassiveLemon** [comment] 2024-04-24 20:43
Side note: Adjust the position of the activity popup because it covers up page navigation
![image](https://github.com/morpheus65535/bazarr/assets/72527881/d27e74c8-746e-4600-bab9-3193356370a6)

**Comment by PassiveLemon** [comment] 2024-04-25 00:59
[bazarrui.log](https://github.com/morpheus65535/bazarr/files/15102406/bazarrui.log)
Just caught it doing it again so here's the last 150 lines from Docker logs. It appears that nothing functions anymore once it happens. If there isn't enough evidence, I can send a longer log.

**Comment by morpheus65535** [comment] 2024-04-25 01:09
This logs only tell me that a subtitles downloaded from animetosho encoding wasn't guessed properly. I think we'll need a longer log...

**Comment by PassiveLemon** [comment] 2024-04-25 01:23
[_bazarr_logs.txt](https://github.com/morpheus65535/bazarr/files/15102664/_bazarr_logs.txt)
Might as well send the whole thing

**Comment by anderson-oki** [comment] 2024-04-25 01:36
@PassiveLemon What do you mean the web ui becomes inaccessible? Do you get like refused to connect error from browser? Also do you still get logs while the WebUI is inaccessible?

**Comment by PassiveLemon** [comment] 2024-04-25 01:38
I get Firefoxes "Hmm. We're having trouble finding that site." error. And no, I do not seem to get any more logs once it happens.

**Comment by anderson-oki** [comment] 2024-04-25 01:43
Yeah i guess python3 process died for some reason 🤔

**Comment by flensburg2** [comment] 2024-04-25 07:57
Doing some maintenance today on all my bazarr setup, disk mappings etc. Third time now in an hour where UI crashes and cant reach backend. So there seem to be an issue for sure.

**Comment by morpheus65535** [comment] 2024-04-25 10:24
Just for testing purpose, what happen if you disable animetosho provider for a while?

**Comment by anderson-oki** [comment] 2024-04-25 10:43
Perhaps @flensburg2 can also provide some logs?

**Comment by morpheus65535** [comment] 2024-04-25 10:44
> Perhaps @flensburg2 can also provide some logs?

https://github.com/morpheus65535/bazarr/issues/2470#issuecomment-2076137237

**Comment by flensburg2** [comment] 2024-04-25 10:47
> Just for testing purpose, what happen if you disable animetosho provider for a while?

Never had animetosho enabled.

**Comment by anderson-oki** [comment] 2024-04-25 10:47
I saw PassiveLemon logs i was wondering if they have different behaviors and jf they are both using animetosho?

**Comment by morpheus65535** [comment] 2024-04-25 10:48
> I saw PassiveLemon logs i was wondering if they have different behaviors and if they are both using animetosho?

My bad, sorry. It's still early here ;)

**Comment by morpheus65535** [comment] 2024-04-25 16:08
> Never had animetosho enabled.

This message was for @PassiveLemon .

@flensburg2 can you provide debug logs?

**Comment by PassiveLemon** [comment] 2024-04-26 00:43
I removed the animetosho provider and AniDB integration and I have yet to see it happen. I'll give it overnight before I say with confidence though.

**Comment by PassiveLemon** [comment] 2024-04-26 18:46
No problems so far. I guess it can be reasonably assumed that the animetosho provider or AniDB integration is the culprit

**Comment by morpheus65535** [comment] 2024-04-27 02:10
@flensburg2 still waiting for your logs.

@PassiveLemon thanks for checking that.

@anderson-oki are you able to look into this?

**Comment by anderson-oki** [comment] 2024-04-27 02:13
The animetosho encoding issue is a separated issue and i can for sure reproduce but doesnt break anything else. I will be looking to fix that but it seems unrelated?

I have been running the docker version with an uptime of 32 hours fully using anidb and animetosho and i cant find anything that can be causing it. I will keep looking into it but im not sure if i can spot the root cause soon without more details.

**Comment by anderson-oki** [comment] 2024-04-27 02:16
@morpheus65535 can we ask to try the beta 26 since it fixes some exceptions? My guess in the worst case the exceptions are accumulating some garbage that kills it? Or maybe Docker disk space for the cache?

**Comment by morpheus65535** [comment] 2024-04-27 02:20
> @morpheus65535 can we ask to try the beta 26 since it fixes some exceptions? My guess in the worst case the exceptions are accumulating some garbage that kills it fixed on the beta 26. Or maybe Docker disk space for the cache?

Of course we can ask @PassiveLemon to test latest beta. Can you also provide docker-compose just in case we see something?

**Comment by PassiveLemon** [comment] 2024-04-27 02:58
Heres my docker-compose:
```yaml
bazarr:
  image: lscr.io/linuxserver/bazarr:development-version-v1.4.3-beta.24
  container_name: bazarr
  restart: always
  volumes:
    - /home/docker/Containers/Media/Bazarr/config/:/config/:rw
    - /home/HDD2TBEXT4/Media/:/data/:rw
  environment:
    TZ: "${TZ}"
    PUID: "${PUID}"
    PGID: "${PGID}"
  ports:
    - 55367:6767/tcp
  networks:
    torrent:
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 300M
```
I'm going to bump it to beta 26, renable animetosho/anidb and let it run over night and see if anything happens

**Comment by anderson-oki** [comment] 2024-04-27 04:42
Thanks @PassiveLemon, please re-send the logs of the version 26 if the breaks again 🙇🏻

**Comment by morpheus65535** [comment] 2024-04-27 10:47
Limiting Bazarr to 300M of memory is probably the root cause. Depending of what feature you use, it may require more memory than that. Subtitles synchronization could use over a gigabyte of memory depending of audio track format.

**Comment by anderson-oki** [comment] 2024-04-27 13:43
I can reproduce the issue lowering the memory. The `/lsiopy/bin/python3 -u /app/bazarr/bin/bazarr/main.py --no-update --config /config` gets killed on kernel level by out of memory.

**Comment by PassiveLemon** [comment] 2024-04-27 14:17
Hm i didn't even think of that. Usually if i have memory problems, the container just becomes slow but i've never had crashes before. I'll increase it

**Comment by morpheus65535** [comment] 2024-04-30 02:14
So everything seems to be good now. I'll close this issue but let me know if you experience it again.

**Closed by morpheus65535** 2024-04-30 02:14 UTC

**Comment by PassiveLemon** [comment] 2024-05-01 19:13
Hmm well it's happening again. Memory limit is set to 1 gigabyte

**Comment by anderson-oki** [comment] 2024-05-02 00:26
@PassiveLemon Let me ask a couple more questions and ask you to try something:

1 - Does it happen on a specific time every time? Like more specifically on the time it is set on the `Settings > Scheduler`?

2 - Can you try to open `System > Tasks` and run some tasks like `Index All Movie` , or maybe the other tasks as well.

Can you see if while doing the `2` it crashes? Or maybe monitor the memory usage while running the tasks?

**Comment by PassiveLemon** [comment] 2024-05-02 19:32
Looking at where the logs end (4:02 AM), it seems like either the search for missing movie or series subtitles is at least partially responsible. The issue is that I ran it last night and it didn't crash. I'm running it again to confirm though

**Comment by anderson-oki** [comment] 2024-05-06 14:14
So it seems to die at 4AM, what schedulers do you have for 4AM? Can you reproduce manually running the Task?

**Comment by PassiveLemon** [comment] 2024-05-06 20:53
The only thing that runs specifically at 4 AM is indexing but other stuff could have happened to run at 4 AM at that time too just from default intervals. I've tried running all of the tasks multiple times and have not been able to reproduce it. In fact, it hasn't crashed since I sent the last comment. This is so finicky

**Comment by anderson-oki** [comment] 2024-05-07 00:48
Some people reported that the `Automatic Subtitles Synchronization` is causing some out of memory on their environment, perhaps because it consumes a lot of memory for bigger movies.

**Comment by mathieures** [comment] 2025-01-09 18:58
Increasing maximum memory usage to 1Gi on a Kubernetes cluster fixed numerous crashes for me, including whenever I was searching for subtitles or even uploading manually-downloaded subtitles (Bazarr was not very useful in that state I must admit).

There were no error messages in the logs, only the famous "Error 500 You have disconnected from the server" message in the web UI, so it was pretty hard to diagnose. Thank you for the recommendation @morpheus65535, as I would probably have taken way longer to find the issue!

For what it’s worth, `Automatic Subtitles Synchronization` was not enabled, but the `Anime Tosho` provider was.
