### ISSUE TITLE
Providers not working (probably because of pihole)

### ISSUE THREAD

**Issue by Casvt** [morpheus65535/bazarr#1258] opened 2021-02-03 10:35 UTC
**Describe the bug**
I have pihole installed and when trying to download subtitles, the provider stops and says "ServiceUnavailable" or "SSLError".
I enabled debug logging and found the following many many times:

03/02/2021 11:18:14|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (3): s104.api.bsplayer-subtitles.com:80|

03/02/2021 11:18:14|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on s104.api.bsplayer-subtitles.com|

03/02/2021 11:18:14|INFO    |subliminal_patch.providers.bsplayer|ERROR: HTTPConnectionPool(host='s104.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6f2c6fff10>: Failed to establish a new connection: [Errno 111] Connection refused')).|

The fact that it says "Falling back to default DNS or IP" makes me think if it is pihole, but I'm not sure. I have whitelisted the domain (eventhough it isn't blacklisted), but that didn't help.

**To Reproduce**
1. Have pihole installed and setup as dns server in the router settings.
2. Whitelist the domain
3. Search for a subtitle using Bazarr

**Expected behavior**
To find and download the subtitle without the provider timing out/crashing.

**Software (please complete the following information):**
 - Bazarr: 0.9.0.8
 - Radarr: 3.0.1.4259
 - Sonarr: 3.0.4.1098
 - OS: Linux Ubuntu 20.04 (Linux-5.8.0-36-generic-x86_64-with-glibc2.29)
 - Pihole: pihole v5.2.4, webinterface v5.2.1, FTL v5.5.1

It might not be pihole at all, it's just what I think it is.

**Comment by morpheus65535** [comment] 2021-02-03 11:40
Unrelated to PiHole. This "Falling back to default DNS or IP" may be ignored. This one is a duplicate of #1235 fixed in v0.9.1.

**Closed by morpheus65535** 2021-02-03 11:40 UTC

**Comment by Casvt** [comment] 2021-02-03 13:16
The newest version here on github is v0.9.0.8. So I assume that v0.9.1 is under the development branch, but how do I update to a development version (now I have the master version). Under settings>general, I have changed the branch from master to development but it doesn't seem to update. Simply said, how do I update to v0.9.1?

**Comment by morpheus65535** [comment] 2021-02-03 13:35
You've got the first step by yourself but you need to run the "Update Bazarr sources from Github" task in System-->Tasks.
