### ISSUE TITLE
1.4.4-beta.27 is turning SRT files into blanks after syncing

### ISSUE THREAD

**Issue by alfuraiji** [morpheus65535/bazarr#2598] opened 2024-08-01 17:28 UTC
**Describe the bug**
Bazarr is turning SRT files into blanks ( deletes everything inside the file ) after syncing - ASS files sync normally. 
( happens with Arabic subtitles not sure about other languages ) 

**To Reproduce**
Just sync any subtitle with an SRT file 

**Software**
- Bazarr: [1.4.4-beta.27]

**Comment by morpheus65535** [comment] 2024-08-08 11:28
I haven't specifically tested with beta.27 but I can't reproduce with beta.30.

1. Downloaded an Arabic subtitles
2. Manually synced the Arabic subtitles with an external English subtitles as reference
3. Waited for sync to ends
4. The synced subtitles file contains a valid subtitles

Maybe provide a debug log if you're able to reproduce?

**Comment by alfuraiji** [comment] 2024-08-10 00:37
Tested with 1.4.4-beta.30 it works fine! tested with multiple SRTs

Sorry couldn't post the log because I cleared it and forgot which SRT got blanked 
will keep testing manually before I enable the auto-sync. 

Thanks

**Comment by alfuraiji** [comment] 2024-10-26 12:18
Hi It happened again .. Arabic SRT files still get cleared and become blank with auto sync enabled. 

those all are zero bytes now. 
<img width="713" alt="Screenshot 2024-10-26 at 3 08 04 PM" src="https://github.com/user-attachments/assets/c5ddd74e-bb19-42e1-a610-1ff0f33a4a17">

here is the log 

[bazarr (2).log.zip](https://github.com/user-attachments/files/17530563/bazarr.2.log.zip)

**Comment by morpheus65535** [comment] 2024-10-26 14:10
@alfuraiji it's a totally new issue:

```
BAZARR Error (cannot access local variable 'anidb_id' where it is not associated with a value) trying to get video information for this file: /data/anime/Detective Conan/Season 32/Detective Conan - S32E12 - The Lost Treasure Mystery - 2024-04-13 - HDTV-1080p v2 - Erai-raws.mkv|Traceback (most recent call last):
  File "/app/bin/bazarr/subtitles/utils.py", line 48, in get_video
    refiner(path, video)
  File "/app/bin/bazarr/subtitles/refiners/anidb.py", line 206, in refine_from_anidb
  	refine_anidb_ids(video)
  File "/app/bin/bazarr/subtitles/refiners/anidb.py", line 214, in refine_anidb_ids
    anidb_series_id, anidb_episode_no, anidb_season_episode_offset = anidb_client.get_show_information(
    																 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)		
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/dogpile/cache/region.py", line 1632, in get_or_create_for_user_func
    return self.get_or_create(		
           ^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/dogpile/cache/region.py", line 1092, in get_or_create
    with Lock(
  File "/app/bin/bazarr/../libs/dogpile/lock.py", line 185, in __enter__
    return self._enter()		
           ^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/dogpile/lock.py", line 94, in _enter
    generated = self._enter_create(value, createdtime)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/dogpile/lock.py", line 178, in _enter_create
    return self.creator()		
           ^^^^^^^^^^^^^^
  File "/app/bin/bazarr/../libs/dogpile/cache/region.py", line 1046, in gen_value
    created_value = creator(
                    ^^^^^^^^
  File "/app/bin/bazarr/subtitles/refiners/anidb.py", line 134, in get_show_information
    return anidb_id, episode - offset, offset		
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'anidb_id' where it is not associated with a value
```

@anderson-oki any idea?

**Comment by morpheus65535** [comment] 2024-10-26 14:33
Ok thanks! So it will be fixed in upcoming beta.

**Closed by morpheus65535** 2024-10-26 14:33 UTC
Labels: awaiting feedback, cannot reproduce

**Comment by alfuraiji** [comment] 2024-10-27 15:03
Great! Thanks
