### ISSUE TITLE
Unable to edit an already existent profile

### ISSUE THREAD

**Issue by raphaelshiga** [morpheus65535/bazarr#2660] opened 2024-09-15 23:21 UTC
When you click to Edit an already existent profile, the page is updated to a blank state.

1. To reproduce, go to "Settings > Language > Languages Profiles"
2. Click on the Wrench icon (Edit Profile).
3. Blank screen

Software:
 - Bazarr: 1.4.4

Attemps to solve the problem:
- Remove cookies (no success)
- Use another browser (tried on Microsoft Edge and Chrome - no suceess)

**Comment by JaiZed** [comment] 2024-09-16 03:01
I believe this is due to duplicate ids in certain database columns from very old implementations that only became an issue recently because of other improvements made. Unless you want to edit the database via a SQL editor, the easiest and best way is to simply delete the offending language profile and re-create it in exactly the same way. (This has nothing to do with web browsers.)

**Comment by raphaelshiga** [comment] 2024-09-16 14:38
Yeah, I can do this. I have just one profile. But maybe it's something that can be addressed for future releases, considering that I regularly update the container using Watchtower.

**Comment by morpheus65535** [comment] 2024-09-16 15:22
Can you provide a debug log while trying to edit this languages profile? I can't reproduce on my side.

**Comment by raphaelshiga** [comment] 2024-09-16 16:08
I didn't deleted it yet. Follow the debug log.
[bazarr.log](https://github.com/user-attachments/files/17016130/bazarr.log)

**Comment by JaiZed** [comment] 2024-09-16 16:12
That debug log is almost empty.
It just shows the startup and nothing else.

**Comment by raphaelshiga** [comment] 2024-09-16 16:34
It is a simple and fast action to reproduce. Even so, follow the entire log file with multiple tries of trying to edit the profile.
[bazarr.log](https://github.com/user-attachments/files/17016457/bazarr.log)

**Comment by JaiZed** [comment] 2024-09-16 16:50
There still isn't anything useful in the debug logs and I think that's because this is a front-end JavaScript error which doesn't do any logging. 
We really need to see the contents of the database table called `table_ languages_ profiles`.

**Comment by raphaelshiga** [comment] 2024-09-16 17:19
Sure

[bazarr_backup_v1.4.4_2024.09.16_14.16.30.zip](https://github.com/user-attachments/files/17017046/bazarr_backup_v1.4.4_2024.09.16_14.16.30.zip)

**Comment by JaiZed** [comment] 2024-09-16 18:42
Thanks for uploading the database.
As I suspected, the problem is with duplicate IDs.
In older versions of the software, we didn’t care about duplicate IDs because we didn’t use their values, but they are used now.

From the database, the column called `items` in the table called `table_ languages_ profiles`:
`[{"id": 1, "language": "pb", "forced": "True", "hi": "False", "audio_exclude": "True"}, {"id": 1, "language": "pb", "forced": "False", "hi": "False", "audio_exclude": "True"}, {"id": 2, "language": "en", "forced": "True", "hi": "False", "audio_exclude": "False"}, {"id": 2, "language": "en", "forced": "False", "hi": "False", "audio_exclude": "False"}]`

Notice that for the values of “id”, there are two values of 1 and another two values of 2. Each of these values are supposed to be unique.

@anderson-oki Is there anything you can do in the front end to handle these duplicate values? Can you ignore them on input and correct them on output?
Or @morpheus65535 Is there something in a database migration that we can do instead if we can’t handle it in the front end?

I think this fix should also be in 1.4.5.

**Comment by raphaelshiga** [comment] 2024-09-16 20:46
Thanks for the help.

Since my current profile is working and I don't really need to change it right now, I'll leave this way to test and report back to you.

@JaiZed I know it's outside of scope for this particular issue, but maybe you can help with another issue opened by me yesterday. A solution for that case would really help me and perhaps other people.

**Comment by morpheus65535** [comment] 2024-09-27 01:40
Should have been fixed in #2667 already available in latest nightly/beta.

**Closed by morpheus65535** 2024-09-27 01:40 UTC
