### ISSUE TITLE
Cant reset auth after restoring from backup

### ISSUE THREAD

**Issue by SebbeJohansson** [morpheus65535/bazarr#2441] opened 2024-03-28 20:20 UTC
**Describe the bug**
After restoring from a backup (from 1.4.1) after the whole config reset, I cant login. Setting auth via the config.yaml file does not work.

**To Reproduce**
1. Restore backup.
2. Try to login.
3. Fail to login.
4. Open config.yaml.
5. Try setting auth type to `None`, `none`, basic, form.
6. Still cant login no matter what is tried.

**Expected behavior**
I expect setting auth type to none or null to result in no authentication required.

**Screenshots**
Null auth type:
![image](https://github.com/morpheus65535/bazarr/assets/5083273/311cadd5-bb58-4371-80de-b5f9282707d7)
![image](https://github.com/morpheus65535/bazarr/assets/5083273/b7400893-d290-4988-9138-1571499857bc)

**Software (please complete the following information):**
- Bazarr Version: 1.4.2
- Package Version: v1.4.2-ls244 by linuxserver.io
- Sonarr Version: 4.0.2.1183
- Radarr Version: 5.3.6.8612
- Operating System: Linux-5.15.0-101-generic-x86_64-with
```
administrator@big-vault:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

**Additional context**
Going to a different page within the bazarr system allows me to access teh full system which in turn allows me to set the auth.
(for example http://bazarr-ip:bazarr-port/system/backup)

**Comment by morpheus65535** [comment] 2024-03-30 13:10
Thanks for reporting. It was probably caused by a browser cache not being invalidated. This should be fixed in upcoming beta. Let me know if it works for you!

**Comment by SebbeJohansson** [comment] 2024-04-01 13:45
Thanks!

**Comment by morpheus65535** [comment] 2024-04-22 16:30
No news, good news!

**Closed by morpheus65535** 2024-04-22 16:30 UTC
Labels: bug, awaiting feedback, fixed
