### ISSUE TITLE
No Results from Subscene with Asian Shows

### ISSUE THREAD

**Issue by TheEarlOfMillenium** [morpheus65535/bazarr#963] opened 2020-05-04 13:01 UTC
**Describe the bug**
Unable to get results from Subscene.com provider when searching for subtitles for episodes of ongoing Asian TV shows.

**To Reproduce**
1. Have The World of the Married show imported in Sonarr
2. Search for The World of the Married in Bazarr
3. Click Manual Search (person icon) for epsiode
4. See No Subtitles Found For This Episode

**Expected behavior**
Should be able to retrieve the following subtitles from Subscene.com:
`부부의 세계-The.World.of.the.Married.E12.200502.1080p.JTBC.WEB-DL.H264.AAC-AppleTor-VIU`

**Screenshots**
![image](https://user-images.githubusercontent.com/18256197/80968262-3a983880-8e4a-11ea-8108-a54828a930fc.png)
![image](https://user-images.githubusercontent.com/18256197/80968290-48e65480-8e4a-11ea-92c5-5f09c754585c.png)

**Software (please complete the following information):**
 - Bazarr: v 0.8.4.3
 - Sonarr version v 3.0.3.770
 - OS: Ubuntu 18.04

**Additional context**
Logs attached
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4574770/bazarr.log)

**Comment by morpheus65535** [comment] 2020-05-04 14:17
@ratoaq2 any hint about this one?

```
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe
    data = self.executor.extract_info(video_path)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info
    json_dump = self._execute(filename)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute
    return ensure_text(check_output([self.location, '-v', 'quiet', '-print_format', 'json',
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/movies/Movies/ヱヴァンゲリヲン新劇場版：序 (2007)/ヱヴァンゲリヲン新劇場版：序 (2007) - [Remux-1080p AVC TrueHD 6.1] - Radarr.mkv']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/bazarr/bazarr/list_subtitles.py", line 116, in store_subtitles_movie
    subtitle_languages = embedded_subs_reader.list_languages(reversed_path)
  File "/app/bazarr/bazarr/embedded_subs_reader.py", line 25, in list_languages
    data = api.know(file)
  File "/app/bazarr/bazarr/../libs/knowit/api.py", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: 
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                   /usr/bin/ffprobe                    |
|                        v4.2.1                         |
|                                                       |
|                        enzyme                         |
|                         0.4.1                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/bazarr/bazarr/../libs/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 230, in describe
    data = self.executor.extract_info(video_path)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 89, in extract_info
    json_dump = self._execute(filename)
  File "/app/bazarr/bazarr/../libs/knowit/providers/ffmpeg.py", line 123, in _execute
    return ensure_text(check_output([self.location, '-v', 'quiet', '-print_format', 'json',
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ffprobe', '-v', 'quiet', '-print_format', 'json', '-show_format', '-show_streams', '-sexagesimal', '/movies/Movies/ヱヴァンゲリヲン新劇場版：序 (2007)/ヱヴァンゲリヲン新劇場版：序 (2007) - [Remux-1080p AVC TrueHD 6.1] - Radarr.mkv']' returned non-zero exit status 1.

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```

**Comment by ratoaq2** [comment] 2020-05-04 18:09
ffprobe is failing. I suggest the user to execute the ffprobe against that file and check the output / error

**Comment by morpheus65535** [comment] 2020-05-04 18:16
@TheEarlOfMillenium please test this media file to see if ffprobe can analyze it.

**Comment by TheEarlOfMillenium** [comment] 2020-05-06 01:11
@morpheus65535 

Here is the probe on the file you mentioned above (Evangelion 1.11 You Are Not Alone 2007)
https://pastebin.com/F8N0pKqS

**Comment by morpheus65535** [comment] 2020-05-06 04:12
Your log file specify that `/usr/bin/ffprobe` is version 4.2.1 but the output from ffprobe you just provided are from version 3.4.6... Any idea why this happen?

**Comment by TheEarlOfMillenium** [comment] 2020-05-06 04:26
Running bazarr in docker. The 3.4.6 version is from Ubuntu on the server. I'll try and get v4xx for Ubuntu and try again.

**Comment by TheEarlOfMillenium** [comment] 2020-05-06 04:39
[Here](https://pastebin.com/SX7FZgfy) is the result using ffprobe version 4.2.1

**Comment by morpheus65535** [comment] 2020-05-06 11:21
@ratoaq2 looks good to me. Strange...

**Comment by ratoaq2** [comment] 2020-05-10 17:40
Could you run with all the parameters as described below?

```
/usr/bin/ffprobe -v quiet -print_format json -show_format -show_streams -sexagesimal /movies/Movies/ヱヴァンゲリヲン新劇場版：序 (2007)/ヱヴァンゲリヲン新劇場版：序 (2007) - [Remux-1080p AVC TrueHD 6.1] - Radarr.mkv
```

**Comment by TheEarlOfMillenium** [comment] 2020-05-12 03:10
[Here](https://pastebin.com/G2Zuwh0h) it is

**Comment by ratoaq2** [comment] 2020-05-12 21:05
I'm checking ffprobe docs:

```If a url is specified in input, ffprobe will try to open and probe the url content. If the url cannot be opened or recognized as a multimedia file, a positive exit code is returned.```

When running bazarr inside docker, it seems it can't either find, open or read the media file. I'm not sure if this might be related to the special characters in the file name.

I suppose you tested running ffprobe inside the docker container and it worked.
The next step would be to run knowit against the same file inside the docker container. So we can isolate if the issue is present in a standalone knowit, or only inside bazarr process env

**Comment by morpheus65535** [comment] 2020-05-25 10:43
Looking at this issue with fresh eyes, I can see you path and filename includes colons (:). On Windows, it wouldn't be possible to create a directory or file with this character. Under Linux, it's possible but highly discouraged. It cause a lot of issues (just Google "filename colon linux") and look at the results... I would try to remove that character from the directory and filename and see if it works.

**Comment by TheEarlOfMillenium** [comment] 2020-05-25 14:57
But the file path of the Korean TV Show I’m downloading subs for on Subscene doesn’t have colons in the filepath. Can the issue with the filepath in the movies be causing the issue with the show?

**Comment by morpheus65535** [comment] 2020-05-25 17:46
No but I was investigating with the path you provided. Of you have a new test case, please provide a new debug log.

**Comment by TheEarlOfMillenium** [comment] 2020-05-26 08:21
Its still the same test case its just you were looking at the wrong file. The file I am having an issue with is the episode for The World Of Married.

Here is a filtered log file for that specific file.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/4680812/bazarr.log)

**Comment by morpheus65535** [comment] 2020-05-28 00:41
@pannal why in hell are you appending the season to the title when searching for a series on subscene?

`subliminal_patch.providers.subscene|Searching for alternative results: The World of the Married - First Season`

https://github.com/morpheus65535/bazarr/blob/376d57e4e7abb1bd34e885bc13d9b77200637030/libs/subliminal_patch/providers/subscene.py#L312

**Comment by pannal** [comment] 2020-05-28 07:50
@morpheus65535 because their search changed over time and didn't allow filenames anymore, and expected a specific season to return the proper results to parse.

What's with the tone?

**Comment by morpheus65535** [comment] 2020-05-28 10:28
@pannal sorry, no harm intended. I was only tired trying to understand why this doesn't work for this actual series.

Any chance you might take a look at this one and see if you can make a quick fix?

**Comment by morpheus65535** [comment] 2020-05-28 10:34
@TheEarlOfMillenium are you able to run some test with other Asian shows?

**Comment by hawkash** [comment] 2020-05-29 00:57
This is also an issue with Arabic Subtitle. Bazarr found nothing but there are some in subscene website.

![Screen Shot 2020-05-29 at 3 52 09 AM](https://user-images.githubusercontent.com/37810955/83209069-0ae60300-a160-11ea-841e-c8b33b96058c.png)
![Screen Shot 2020-05-29 at 3 52 28 AM](https://user-images.githubusercontent.com/37810955/83209077-0f122080-a160-11ea-8f27-c5a8907605e9.png)

**Comment by TheEarlOfMillenium** [comment] 2020-05-30 07:04
> @TheEarlOfMillenium are you able to run some test with other Asian shows?

@morpheus65535 all other asian shows i have tried will not pull results from subscene but will be able to get subs from opensubs if available from them. Most of the shows have subs uploaded to subscene so I would prefer to get it from there.

Since this is also happening with Arab shows, could this be due to the series title in Subscene having special characters like the Arab letters/ Chinese or Chinese or Japanase Characters?

**Comment by hawkash** [comment] 2020-05-30 07:11
this is not an Arabic show, it is an American show. Also the title is in English. but idk why bazarr is not able to get the subs for many shows but able with some.

**Comment by morpheus65535** [comment] 2020-07-07 04:16
Is this still an issue?

**Comment by morpheus65535** [comment] 2020-07-13 18:13
Closing this issue, no answer.

**Closed by morpheus65535** 2020-07-13 18:13 UTC
Labels: awaiting feedback
