### ISSUE TITLE
Sync tasks queue cut short

### ISSUE THREAD

**Issue by rmichelena** [morpheus65535/bazarr#1840] opened 2022-05-11 17:25 UTC
Bazarr 1.0.4
Newly uploaded tv show
I upload 10 subtitles to Bazarr
In tools (per show, not per episode) I select the 10 episodes and choose "sync"
it only does the first 4 or 5 (actually the last, since the list is inverse)
nothing shows in the log (since 1.0.4, logs are not showing sync events, at least not manually triggered ones)

**Comment by morpheus65535** [comment] 2022-05-15 13:39
https://wiki.bazarr.media/Troubleshooting/FAQ/#synchronization-failed

**Comment by morpheus65535** [comment] 2022-05-15 13:41
I've just tested out and manual sync are showing properly in history when they are successful.

**Comment by rmichelena** [comment] 2022-05-15 18:34
If I select 2 or 3 or maybe even 4 or 5 subtitles and press “sync”, it works.
But if I select more, it’ll only sync the first (latest) 4 or 5.
Then I have to go back and select the remaining ones and sync them.
And it does sync them, so it’s not subs that fail to sync… it’s as if the queue times out or something like that. Files are not local (they’re on Google Drive) so each sync might take longer than usual, maybe that’s a factor.

**Comment by rmichelena** [comment] 2022-05-15 19:07
History does show the ones that were synced, that’s how I know it didn’t sync all of them.
Log does not show anything regarding sync events, neither successes nor failures.
And it’s not that it synced them and didn’t report in history, because when I reselect those and actually sync them and they do show in history, there are offsets reported.

**Comment by morpheus65535** [comment] 2022-05-15 20:15
I've been trying to reproduce your issue but I'm unable:
![image](https://user-images.githubusercontent.com/5130500/168492063-8b5a2724-58ba-415b-a04b-27b815cae9ab.png)
As you said, it could be releated to your cloud setup. I have no way to test that.

**Comment by kfstorm** [comment] 2022-06-05 04:55
I've seen this issue all the time. I run Bazarr on a small device. For each subtitle, it takes ~5 minutes to sync. If I select all episodes of the series, only the latest episode is submitted for syncing (observed from the developer tools). I guess the batching is implemented at the client side. Since the first sync request timeouts, the subsequent requests are never sent to the server.

**Comment by morpheus65535** [comment] 2022-06-06 10:39
> I've seen this issue all the time. I run Bazarr on a small device. For each subtitle, it takes ~5 minutes to sync. If I select all episodes of the series, only the latest episode is submitted for syncing (observed from the developer tools). I guess the batching is implemented at the client side. Since the first sync request timeouts, the subsequent requests are never sent to the server.

Can you confirm if you're facing the same issue with latest 1.0.5-beta? We've implemented a new UI and this part may have been reworked.

**Comment by morpheus65535** [comment] 2022-06-15 10:12
You'll have the issue with latest beta also. Currently the UI send one by one the sync requests. We must rework that part to send them (and all tools query) at once. @LASER-Yi and I will see how it can be done.

**Comment by morpheus65535** [comment] 2022-10-06 10:27
> Would such a rework allow to queue syncing of all subtitles for all movies/shows?

No.

**Comment by theg00s3** [comment] 2022-11-29 08:07
yeah I'm also having the same issue

**Comment by morpheus65535** [comment] 2022-11-29 11:20
> yeah I'm also having the same issue

It's not really an issue, it's by design. We must refactor stuff to make this possible.

**Comment by morpheus65535** [comment] 2022-12-12 19:06
I'll close this issue but I'll implement a jobs queue with UI in 1.2.0. Frontend jobs will be send to backend and won't depend on browser conext.

**Closed by morpheus65535** 2022-12-12 19:06 UTC
Labels: bug, priority:medium
