### ISSUE TITLE
OpenSubtitles.com provider doesn't handle download quota properly

### ISSUE THREAD

**Issue by enduity** [morpheus65535/bazarr#2153] opened 2023-05-24 23:55 UTC
While researching #2152, I discovered this (possibly contributing) bug.

**Describe the bug**
When the OpenSubtitles.com provider reaches the account's download quota, the event is handled as `AuthenticationError. Exception info: 'Login failed: Unauthorized'`. It shouldn't really break much, but since the actual response includes the exact reason for the throttle and when the service will be available again, fixing it would still improve the user experience.

**To Reproduce**
1. Use OpenSubtitles.com as a provider
2. Try to download more than 20 (?) subtitles with it in a short period of time
3. See wrong error in log as reason for provider being disabled for 10 minutes

**Expected behavior**
Handle the response from the OpenSubtitles.com API properly

**Software**
Bazarr: 1.2.1

**Log messages**
First message
`Throttling opensubtitlescom for 10 minutes, until 23/05/25 02:39, because of: AuthenticationError. Exception info: 'Login failed: Unauthorized'`
Second message (retry)
`Using opensubtitlescom again after 10 minutes, (disabled because: AuthenticationError)`

**The response from OpenSubtitles.com**
The response has the status 401. Here is an example response body from my account:
`{
    "message": "You have downloaded your allowed 20 subtitles for 24h.Your quota will be renewed in 00 hours and 27 minutes (2023-05-24 23:59:59 UTC) "
}`
This response format really isn't the best, but we have no choice.

**Comment by morpheus65535** [comment] 2023-05-25 02:21
@opensubtitles it seems the latest changes you've made to prevent anonymous downloads for unauthenticated users had a side effect. Is it possible you'd be returning a 401 instead of a 406 when authenticated user reach is daily quota?

**Comment by opensubtitlesdev** [comment] 2023-05-25 10:38
So about the quotas, if you query without authentication, you are limited to the api key's limitation: 5

if you query with a bearer token, it's the user quota who's applied, 20 for a basic user, 1000 for a VIP, as listed here for the website https://www.opensubtitles.com/en/support_us the only difference being only 5 anonymous downloads from the api.

When the limit is reached, a 406 error is returned, indicating the number of downloads performed (there's a little bug that allows to download 1 subtitle over quota at the moment) and the reset time.

The 401 Login failed: Unauthorized is only returned when a bad password is sent.

**Comment by morpheus65535** [comment] 2023-05-29 10:41
@enduity I've made a small change to prevent retrying ConfigurationError or AuthenticationError. Can you try to reproduce the issue in upcoming beta and provide debug log please?

**Comment by enduity** [comment] 2023-05-29 10:59
> @enduity I've made a small change to prevent retrying ConfigurationError or AuthenticationError. Can you try to reproduce the issue in upcoming beta and provide debug log please?

Sure, I'll try to reproduce it, but I'm not sure this particular response from the OpenSubtitles API is an issue on your end. I made the request for the response in my issue description using Postman, not Bazarr. I understand that one of them may produce unintended results, but both? I don't think I am imagining it, seems like a bug on their end possibly. When I have more time, I'll test out different scenarios to see if I can reproduce it.

I would like to suggest that you modify the error handling for the OpenSubtitles.com provider, if possible. Right now it's kind of difficult to read and leaving everything up to status codes seems like it could produce unintended results. I feel it would be better to make very specific error cases that actually look at the response it self and handle everything else as an unknown error. This would likely increase the amount of errors users get, but in my opinion it's much more frustrating for the software to act like nothing is wrong at all or give the wrong error.

**Comment by morpheus65535** [comment] 2023-05-29 12:44
@enduity cn you share with us the query you've made to get a 401 when download limit is reached? Did you use Bazarr apikey?

**Comment by enduity** [comment] 2023-05-29 13:25
Now I see that with my own API key, the response is completely normal (with 406 and proper structure), but with Bazarr's API key, the response is odd.

Request headers:
```
Content-Type: application/json
Authorization: Bearer (my token)
Api-Key: (my API key or Bazarr's)
User-Agent: PostmanRuntime/7.32.2
Accept: */*
Postman-Token: (generated per request)
Host: api.opensubtitles.com
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 54
```

Request body:
```json
{
    "file_id": 3714703,
    "sub_format": "srt"
}
```

**401** response using Bazarr's API key:
```json
{
   "message":"You have downloaded your allowed 20 subtitles for 24h.Your quota will be renewed in 11 hours and 02 minutes (2023-05-29 23:59:59 UTC) "
}
```

**406** response using my own API key:
```json
{
   "requests":21,
   "remaining":-1,
   "message":"You have downloaded your allowed 20 subtitles for 24h.Your quota will be renewed in 11 hours and 05 minutes (2023-05-29 23:59:59 UTC) ",
   "reset_time":"11 hours and 05 minutes",
   "reset_time_utc":"2023-05-29T23:59:59.000Z"
}
```

**Comment by opensubtitlesdev** [comment] 2023-05-30 14:29
thanks for your feedback @enduity, I could find the bug and fix it.

**Comment by enduity** [comment] 2023-05-30 15:11
@morpheus65535 Not that important, but it would be nice if the response of `"reset_time_utc"` from the API was considered when setting the length for the throttle. I think it could be implemented by modifying `DownloadLimitExceeded` to accept another argument in the form of what length the throttle should have and also using that value later instead of looking it up from the map.

**Comment by capoacaro** [comment] 2023-05-31 08:41
Any updates on this or what action a user has to take to get it solved? Up to yesterday I was getting a message i had reached my limit (while I have a VIP account) and today bazarr attempts the download and shortly after returns this:
"Throttling opensubtitlescom for 10 minutes, until 23/05/31 10:44, because of: ProviderError. Exception info: 'Service Unavailable' "

**Comment by almulder** [comment] 2023-05-31 21:17
So I upgraded to 1.2.2-beta.11 as I am having issues also with the quota, I am VIP on opensubtitles.com and in Bazarr I keep getting "DownloadLimitExceeded" Yet in my profile i have 300 out of 1000 used. If I removed the Provider clear cache and re-add provider, then it will download one more but then throws the error again.

**Comment by capoacaro** [comment] 2023-06-01 09:41
If this can be of any help...


BAZARR throttled providers have been reset.	01/06/2023 11:34:27
HTTPSConnectionPool(host='api.opensubtitles.com', port=443): Read timed out. (read timeout=30), retrying in 5 seconds...	01/06/2023 11:37:11
Throttling opensubtitlescom for 10 minutes, until 23/06/01 11:47, because of: ProviderError. Exception info: 'Internal Server Error'	01/06/2023 11:37:38
BAZARR All providers are throttled	01/06/2023 11:37:38	
BAZARR Finished searching for missing Movies Subtitles. Check History for more information.	01/06/2023 11:37:38

**Comment by opensubtitlesdev** [comment] 2023-06-01 12:05
We had a few server and proxy issues yesterday and today, connections error an internal server errors should be gone now hopefully.

to track the other issues, there will be a few more extra debugging fields in the responses, if you get again this 1001 subtitle downloaded error message, it would greatly help to send us the whole response for investigation.

**Comment by morpheus65535** [comment] 2023-06-01 12:19
> @enduity Not that important, but it would be nice if the response of `"reset_time_utc"` from the API was considered when setting the length for the throttle.

I'll think about that as an improvement but right now we'll figure out the main issues.

**Comment by opensubtitlesdev** [comment] 2023-06-01 12:23
We had a few server and proxy issues yesterday and today, connections error an internal server errors should be gone now hopefully.

to track the other issues, there will be a few more extra debugging fields in the responses, if you get again this 1001 subtitle downloaded error message while your quota isn't actually reached, it would greatly help to send us the whole response for investigation.

**Comment by almulder** [comment] 2023-06-01 16:27
@morpheus65535 how can I get a full log for @opensubtitlesdev, as it happened again, but will wait until tomorrow to see if the server and proxy issues they had fixes it.

**Comment by opensubtitlesdev** [comment] 2023-06-02 08:00
unfortunately there's no debugging information that can be used in the logs, I need to have the requests or the responses, ideally both.

seems there are situations where an authentication fails on a request, it can be because a token is not properly sent, cached for too long, or I don't know, I can't replicate the issue. 

All server responses indicating a token error or a quota over limit contain full debug data that will allow me to track down what is happening, can someone setup a full debug mode in bazarr that would output the queries and responses to the log ?

**Comment by morpheus65535** [comment] 2023-06-02 11:09
@opensubtitlesdev as discussed on Slack, I've provided the evidence of an intermittent bad interpretation of the perfectly valid token. The issue isn't automatic, you must run queries in loop for a while so don't expect to reproduce after a single API call.

**Comment by almulder** [comment] 2023-06-02 15:26
@morpheus65535 if you find a way to add the debug code that @opensubtitlesdev has mention, tag me once added to next beta and I can help since I am getting the issue. Just let me know how I can help.

**Comment by morpheus65535** [comment] 2023-06-02 15:28
@almulder I will. We're working on this right now in a debugging environment.

**Comment by morpheus65535** [comment] 2023-06-02 19:05
@opensubtitlesdev did fix something on his end and I cannot reproduce the issue anymore. Can you confirm if it's fixed for you also? @almulder @enduity

**Comment by almulder** [comment] 2023-06-02 20:33
> @opensubtitlesdev did fix something on his end and I cannot reproduce the issue anymore. Can you confirm if it's fixed for you also? @almulder @enduity

So far it has been running, already got 5 downloads with out error, it should max out to 1000 as I have loads for it to find.  I will keep you posted!

**Comment by capoacaro** [comment] 2023-06-02 23:19
> > @opensubtitlesdev did fix something on his end and I cannot reproduce the issue anymore. Can you confirm if it's fixed for you also? @almulder @enduity
> 
> So far it has been running, already got 20 downloads with out error, it should max out to 1000 as I have loads for it to find. I will keep you posted!
> 
> Update #1 73 and counting. Looks to be fixed! Thanks for everyone's hard work on getting this fixed.
> 
> Update #2 174 and counting. :)

Wish I could share your joy but here is still the same...does a scan and as the first download begins BAM! locked. (VIP account as i already mentioned)

_Throttling opensubtitlescom for 10 minutes, until 23/06/03 01:26, because of: ProviderError. Exception info: 'Internal Server Error'_

**Comment by morpheus65535** [comment] 2023-06-02 23:27
> @capoacaro  _Throttling opensubtitlescom for 10 minutes, until 23/06/03 01:26, because of: ProviderError. Exception info: 'Internal Server Error'_

This is a different issue than the one we are currently investigating. Enable debug log, clear the log, reproduce and provide the log please.

**Comment by capoacaro** [comment] 2023-06-02 23:36
> > @capoacaro  _Throttling opensubtitlescom for 10 minutes, until 23/06/03 01:26, because of: ProviderError. Exception info: 'Internal Server Error'_
> 
> This is a different issue than the one we are currently investigating. Enable debug log, clear the log, reproduce and provide the log please.

Done
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11639939/bazarr.log)

**Comment by morpheus65535** [comment] 2023-06-02 23:41
@capoacaro ok same issue:
`DownloadLimitExceeded: Daily download limit reached. 0 subtitles have been downloaded and 0 remaining subtitles can be downloaded. Quota will be reset in 0 hours and 26 minutes.`

Try to empty `config/cache` directory, wait for 26 minutes, reset provider in `System-->Providers` then retry. I'm not that confident that it will work but let try it for a last time.

**Comment by capoacaro** [comment] 2023-06-03 00:18
1.Emptyed /opt/bazarr/data/cache
2. waited for 30 minutes
3.server reboot
4.log delete
5.verbose on
6.reset fault
7.retry

no change in behaviour, log in attach

[bazarr.log](https://github.com/morpheus65535/bazarr/files/11640029/bazarr.log)

**Comment by morpheus65535** [comment] 2023-06-03 00:57
@capoacaro now you're getting the internal server error which is a different issue.

```
03/06/2023 02:15:18|DEBUG   |urllib3.connectionpool          |https://www.opensubtitles.com:443 "GET /download/24FD9C3C9E712D14021EB74E2E394837521129EC1A68E9A22D4E3A2A7F67560DE854D3424E4034FA3CADB407FD5EF7C4115076E0DD3D96C4CA2826DA863A707A7BEBB5E055526F1E077BD3E9BD52CF0BDE4A866FA3658468C40D5154826EB4A0A587CD36CC11E0C844E566F2D016865BDFDDAA9F72001E1C8DE6CBC807F73E8BB418E02FB2BA992F2C9C2811D6DF37C2A1DCB7EFC20E83E955F63CAC9BC2128147CF06808997E7B1D8D32B34ACB71EB44799A3CCC89791DB2CB7B44907116C38C36790C926FFA41BD315167292EAD7611B6FBDDB3CADC289900090383B3042DF7D32BC3596C92CB3168084334173227D971DFAD299004C448EDB6B196AD29B8A33CAD2EF424ABD422B43E0783CD9BFF40B808C5C87F5984D/subfile/Motherless%20Brooklyn%20(2019).srt HTTP/1.1" 500 None|
```

@opensubtitlesdev anything we can do about this one? Why would the API download endpoint would return a 500?

**Comment by opensubtitlesdev** [comment] 2023-06-03 11:46
> @capoacaro now you're getting the internal server error which is a different issue.
> 
> ```
> 03/06/2023 02:15:18|DEBUG   |urllib3.connectionpool          |https://www.opensubtitles.com:443 "GET /download/24FD9C3C9E712D14021EB74E2E394837521129EC1A68E9A22D4E3A2A7F67560DE854D3424E4034FA3CADB407FD5EF7C4115076E0DD3D96C4CA2826DA863A707A7BEBB5E055526F1E077BD3E9BD52CF0BDE4A866FA3658468C40D5154826EB4A0A587CD36CC11E0C844E566F2D016865BDFDDAA9F72001E1C8DE6CBC807F73E8BB418E02FB2BA992F2C9C2811D6DF37C2A1DCB7EFC20E83E955F63CAC9BC2128147CF06808997E7B1D8D32B34ACB71EB44799A3CCC89791DB2CB7B44907116C38C36790C926FFA41BD315167292EAD7611B6FBDDB3CADC289900090383B3042DF7D32BC3596C92CB3168084334173227D971DFAD299004C448EDB6B196AD29B8A33CAD2EF424ABD422B43E0783CD9BFF40B808C5C87F5984D/subfile/Motherless%20Brooklyn%20(2019).srt HTTP/1.1" 500 None|
> ```
> 
> @opensubtitlesdev anything we can do about this one? Why would the API download endpoint would return a 500?

this one doesn't come from the API, it's from the website, and it's just a good old regular error 500, a server error, on these paths it's usually a parsing error of the original file, and they are normally very limited.

unfortunately, those will be happening once in a while, but you shouldn't throttle the app in this situation, just try another subtitle.

for the other issues, I added so much logging and monitoring, I can track errors a lot better now, but will still need the server responses to come out in the bazarr log

**Comment by capoacaro** [comment] 2023-06-05 21:20
> > @capoacaro now you're getting the internal server error which is a different issue.
> > ```
> > 03/06/2023 02:15:18|DEBUG   |urllib3.connectionpool          |https://www.opensubtitles.com:443 "GET /download/24FD9C3C9E712D14021EB74E2E394837521129EC1A68E9A22D4E3A2A7F67560DE854D3424E4034FA3CADB407FD5EF7C4115076E0DD3D96C4CA2826DA863A707A7BEBB5E055526F1E077BD3E9BD52CF0BDE4A866FA3658468C40D5154826EB4A0A587CD36CC11E0C844E566F2D016865BDFDDAA9F72001E1C8DE6CBC807F73E8BB418E02FB2BA992F2C9C2811D6DF37C2A1DCB7EFC20E83E955F63CAC9BC2128147CF06808997E7B1D8D32B34ACB71EB44799A3CCC89791DB2CB7B44907116C38C36790C926FFA41BD315167292EAD7611B6FBDDB3CADC289900090383B3042DF7D32BC3596C92CB3168084334173227D971DFAD299004C448EDB6B196AD29B8A33CAD2EF424ABD422B43E0783CD9BFF40B808C5C87F5984D/subfile/Motherless%20Brooklyn%20(2019).srt HTTP/1.1" 500 None|
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @opensubtitlesdev anything we can do about this one? Why would the API download endpoint would return a 500?
> 
> this one doesn't come from the API, it's from the website, and it's just a good old regular error 500, a server error, on these paths it's usually a parsing error of the original file, and they are normally very limited.
> 
> unfortunately, those will be happening once in a while, but you shouldn't throttle the app in this situation, just try another subtitle.
> 
> for the other issues, I added so much logging and monitoring, I can track errors a lot better now, but will still need the server responses to come out in

**Comment by capoacaro** [comment] 2023-06-05 21:27
> > @capoacaro now you're getting the internal server error which is a different issue.
> > ```
> > 03/06/2023 02:15:18|DEBUG   |urllib3.connectionpool          |https://www.opensubtitles.com:443 "GET /download/24FD9C3C9E712D14021EB74E2E394837521129EC1A68E9A22D4E3A2A7F67560DE854D3424E4034FA3CADB407FD5EF7C4115076E0DD3D96C4CA2826DA863A707A7BEBB5E055526F1E077BD3E9BD52CF0BDE4A866FA3658468C40D5154826EB4A0A587CD36CC11E0C844E566F2D016865BDFDDAA9F72001E1C8DE6CBC807F73E8BB418E02FB2BA992F2C9C2811D6DF37C2A1DCB7EFC20E83E955F63CAC9BC2128147CF06808997E7B1D8D32B34ACB71EB44799A3CCC89791DB2CB7B44907116C38C36790C926FFA41BD315167292EAD7611B6FBDDB3CADC289900090383B3042DF7D32BC3596C92CB3168084334173227D971DFAD299004C448EDB6B196AD29B8A33CAD2EF424ABD422B43E0783CD9BFF40B808C5C87F5984D/subfile/Motherless%20Brooklyn%20(2019).srt HTTP/1.1" 500 None|
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @opensubtitlesdev anything we can do about this one? Why would the API download endpoint would return a 500?
> 
> this one doesn't come from the API, it's from the website, and it's just a good old regular error 500, a server error, on these paths it's usually a parsing error of the original file, and they are normally very limited.
> 
> unfortunately, those will be happening once in a while, but you shouldn't throttle the app in this situation, just try another subtitle.
> 
> for the other issues, I added so much logging and monitoring, I can track errors a lot better now, but will still need the server responses to come out in the bazarr log

I didn't check for  2 days but it seems to be ok now.  @opensubtitlesdev did you something on your end? Following your remark, the culprit was the  sub for the movie "motherless brooklyn" which I excluded from the search only to notice after that the automated scan had been running already fine before my manual action. In any case thx all for the help provided.

**Comment by opensubtitlesdev** [comment] 2023-06-07 06:53
> > > @capoacaro now you're getting the internal server error which is a different issue.
> > > ```
> > > 03/06/2023 02:15:18|DEBUG   |urllib3.connectionpool          |https://www.opensubtitles.com:443 "GET /download/24FD9C3C9E712D14021EB74E2E394837521129EC1A68E9A22D4E3A2A7F67560DE854D3424E4034FA3CADB407FD5EF7C4115076E0DD3D96C4CA2826DA863A707A7BEBB5E055526F1E077BD3E9BD52CF0BDE4A866FA3658468C40D5154826EB4A0A587CD36CC11E0C844E566F2D016865BDFDDAA9F72001E1C8DE6CBC807F73E8BB418E02FB2BA992F2C9C2811D6DF37C2A1DCB7EFC20E83E955F63CAC9BC2128147CF06808997E7B1D8D32B34ACB71EB44799A3CCC89791DB2CB7B44907116C38C36790C926FFA41BD315167292EAD7611B6FBDDB3CADC289900090383B3042DF7D32BC3596C92CB3168084334173227D971DFAD299004C448EDB6B196AD29B8A33CAD2EF424ABD422B43E0783CD9BFF40B808C5C87F5984D/subfile/Motherless%20Brooklyn%20(2019).srt HTTP/1.1" 500 None|
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > @opensubtitlesdev anything we can do about this one? Why would the API download endpoint would return a 500?
> > 
> > 
> > this one doesn't come from the API, it's from the website, and it's just a good old regular error 500, a server error, on these paths it's usually a parsing error of the original file, and they are normally very limited.
> > unfortunately, those will be happening once in a while, but you shouldn't throttle the app in this situation, just try another subtitle.
> > for the other issues, I added so much logging and monitoring, I can track errors a lot better now, but will still need the server responses to come out in the bazarr log
> 
> I didn't check for 2 days but it seems to be ok now. @opensubtitlesdev did you something on your end? Following your remark, the culprit was the sub for the movie "motherless brooklyn" which I excluded from the search only to notice after that the automated scan had been running already fine before my manual action. In any case thx all for the help provided.

when a subtitle raises a 500, some background checks are run to try and fix it. sometimes it works, and the subtitle gets available again, and works normally. And sometimes the subtitle can't be fixed, and he disappears from the search results, or the original subtitle gets deleted from opensubtitles.org and then gets deleted from .com

**Comment by morpheus65535** [comment] 2023-06-07 12:09
> @opensubtitlesdev for the other issues, I added so much logging and monitoring, I can track errors a lot better now, but will still need the server responses to come out in the bazarr log

I did add request/response debug logging in upcoming beta.

**Comment by morpheus65535** [comment] 2023-06-08 01:21
Error 500 will be ignored in upcoming beta. I guess everything is fixed now and will be merged to master soon. I'll close this issue.

**Closed by morpheus65535** 2023-06-08 01:21 UTC
Labels: awaiting feedback
