### ISSUE TITLE
[Bug] Bazarr not detecting all the subtitles in media file

### ISSUE THREAD

**Issue by ShadXo** [morpheus65535/bazarr#139] opened 2018-09-11 22:28 UTC
Bazarr not detecting all the subtitles in the media file, sometimes it detects 3 of 5, sometimes it detects all and sometimes none. The mkv's have the correct language flag set. See below 2 Movie and 1 Serie example.

Movie 1:
Text #1
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Title                       : QoQ-Team
Language                    : Dutch
Default                     : Yes
Forced                      : No

Text #2
ID                          : 4
Format                      : PGS
Muxing mode                 : zlib
Codec ID                    : S_HDMV/PGS
Codec ID/Info               : Picture based subtitle format used on BDs/HD-DVDs
Language                    : English
Default                     : No
Forced                      : No

Only English detected.

Movie 2:
Text
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Language                    : Dutch
Default                     : Yes
Forced                      : No

No subs detected.

Serie 1:
Text #1
ID                          : 3
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 41 min 15 s
Bit rate                    : 80 b/s
Count of elements           : 1500
Stream size                 : 24.3 KiB (0%)
Language                    : English
Default                     : No
Forced                      : No

Text #2
ID                          : 4
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 41 min 14 s
Bit rate                    : 76 b/s
Count of elements           : 658
Stream size                 : 23.2 KiB (0%)
Language                    : Dutch
Default                     : No
Forced                      : No

Text #3
ID                          : 5
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 41 min 14 s
Bit rate                    : 69 b/s
Count of elements           : 664
Stream size                 : 21.1 KiB (0%)
Language                    : French
Default                     : No
Forced                      : No

Text #4
ID                          : 6
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 41 min 14 s
Bit rate                    : 77 b/s
Count of elements           : 702
Stream size                 : 23.6 KiB (0%)
Language                    : German
Default                     : No
Forced                      : No

Text #5
ID                          : 7
Format                      : UTF-8
Codec ID                    : S_TEXT/UTF8
Codec ID/Info               : UTF-8 Plain Text
Duration                    : 41 min 14 s
Bit rate                    : 82 b/s
Count of elements           : 705
Stream size                 : 24.9 KiB (0%)
Language                    : Spanish
Default                     : No
Forced                      : No

en, es, fr are detected.

Just looked into the issue. Looks like dutch is not detected, maybe same issue for German?

**Comment by morpheus65535** [comment] 2018-09-11 23:31
What you see in MediaInfo as Dutch is in fact a language code define in the mkv container: "dut"

Bazarr rely on pycountry.languages library to populate a table containing each languages listed in ISO 639-3 standard.

"dut" isn't a valid language code in the ISO 639-3 standard. Dutch is define in ISO 639-3 as "nld" or in ISO 639-2 as "nl". (don't kill the messenger here...)

So when Bazarr get a language code like "dut", he doesn't know what to do with it and simply skip this subtitles track.

I agree that it sound strange but it's not a bug in Bazarr. It follow what the standard says.

Filebot have the same issue: https://www.filebot.net/forums/viewtopic.php?t=1728

**Comment by ShadXo** [comment] 2018-09-12 09:07
Hmm, I see.

dut is listed in ISO 639-2/B

Language codes:

ISO 639-1 | nl
ISO 639-2 | dut (B) nld (T)
ISO 639-3 | nld Dutch/Flemish

Same for German, maybe more languages.
ISO 639-2 | ger (B) deu (T)

Is there something I can do about it?

**Comment by morpheus65535** [comment] 2018-09-12 10:29
Even if you change the db, this table is reloaded every time your restart Bazarr. I will have to look at this data source instead to populate DB: http://www.opensubtitles.org/addons/export_languages.php

I have to evaluate the impact before going there.

**Comment by morpheus65535** [comment] 2018-09-12 14:37
Pycountry.languages module.

**Comment by ShadXo** [comment] 2018-09-12 14:40
Yeah, just found it myself, haha but thanks :p

**Comment by gjdoornink** [comment] 2018-10-23 18:50
Hello,

I have created a pull request with a fix for this issue.
As it turns out the iso639-3.json database in pycountry already contains ISO 639-2/B language codes.
The proposed patch uses these available language code for detecting subtitle languages.
I'm neither fluent in Python, nor in the workings of GitHub, so please be kind if not everything is up to par :-)

**Comment by ShadXo** [comment] 2018-10-24 22:10
Nice, I think thats the better database/dataprovider to use for subtitles and fixes all other changed language codes in iso639-3.

I saw something about that too but I never worked with Python, so could not help to find a solution (or do a few testing).
Happy that you were able to help. :)

**Comment by morpheus65535** [comment] 2018-10-24 23:59
It's been merged in dev branch. Thanks to @gjdoornink!

**Closed by morpheus65535** 2018-10-24 23:59 UTC
Labels: bug, priority:medium
