### ISSUE TITLE
ASS subtitle file is saved with .srt file extension during automatic subtitle search with "Use Original Format" language profile setting enabled

### ISSUE THREAD

**Issue by VeikkoLehmuskorpi** [morpheus65535/bazarr#2693] opened 2024-10-02 20:01 UTC
**Describe the bug**
When using the automatic subtitle search with a language profile that has the "Use Original Format" (Download subtitle file without format conversion) setting enabled, the downloaded ASS subtitle file is saved with .srt file extension. The contents of the subtitle file are not changed.

**To Reproduce**
1. Setup "Jimaku.cc" provider
2. Add "Girls Band Cry (2024)" series
3. Create a language profile and enable the "Use Original Format" setting in the language profile settings
4. Go to the "Girls Band Cry (2024)" series details view
5. Edit the series and set the "Languages Profile" to the newly created language profile
6. Automatically search for all missing series subtitles
7. Observe that ASS subtitle files with .srt file extensions were saved on disk 

**Expected behavior**
As [Jimaku.cc currently only provides ASS subtitle files for the searched series](https://jimaku.cc/entry/2698), when Bazarr finds and downloads the ASS subtitle files, it should respect the "Use Original Format" language profile setting and not convert the ASS subtitle files into SRT subtitle files

**Screenshots**
Jimaku.cc "Girls Band Cry (2024)" entry at the time of writing
![image](https://github.com/user-attachments/assets/fc64b75b-4964-4591-a7b6-5fb036cf07fe)

Language profile settings
![image](https://github.com/user-attachments/assets/64c5df4f-53e2-414b-9228-c36886325fcc)

"Girls Band Cry (2024)" series settings
![image](https://github.com/user-attachments/assets/a78e04f8-cd09-433a-a089-7c83fb3a1654)

**Software (please complete the following information):**
 - Bazarr: 1.4.4 (also tested with 1.4.5)
 - Radarr version 5.11.0.9244
 - Sonarr version 4.0.9.2244
 - OS: Windows 11

**Additional context**
Snippet of Bazarr logs with debug logging enabled from when the subtitle files were searched
```
2024-10-02 22:29:43|INFO    |subliminal_patch.core_persistent|Downloading best subtitles for <Episode ['Girls Band Cry', 2024, 1x5]>|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |Languages requested: {<Language: alpha3=jpn>}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |New set: 1 items|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |Nothing to translate found|
2024-10-02 22:29:43|INFO    |subliminal_patch.core           |Listing subtitles with provider 'jimaku' and languages {<Language: alpha3=jpn>}|
2024-10-02 22:29:43|INFO    |subliminal_patch.providers.jimaku|Will search for entry based on params: {'anilist_id': 164212}|
2024-10-02 22:29:43|INFO    |subliminal_patch.providers.jimaku|Matched entry: ID: '2698', anilist_id: '164212', name: 'Girls Band Cry', english_name: 'None', movie: False|
2024-10-02 22:29:43|DEBUG   |dogpile.lock                    |value creation lock <dogpile.cache.region.CacheRegion._LockWrapper object at 0x1B4E8208> acquired|
2024-10-02 22:29:43|DEBUG   |dogpile.lock                    |Calling creation function for previously expired value|
2024-10-02 22:29:43|DEBUG   |urllib3.connectionpool          |https://jimaku.cc:443 "GET /api/entries/2698/files?episode=5 HTTP/1.1" 200 None|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.providers.jimaku|Length of response on https://jimaku.cc/api/entries/2698/files?episode=5: 3|
2024-10-02 22:29:43|DEBUG   |dogpile.cache.region            |Cache value generated in 0.150 seconds for key(s): "subliminal_patch.providers.jimaku:_search_for_subtitles|entries/2698/files {'episode': 5}"|
2024-10-02 22:29:43|DEBUG   |dogpile.lock                    |Released creation lock|
2024-10-02 22:29:43|WARNING |subliminal_patch.providers.jimaku|Skipping subtitle '[Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN, CHS].ass' as it's suspected of containing multiple languages|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |<JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass [<Language: alpha3=jpn>]>: Found matches {'series', 'season', 'episode', 'year'}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.score          |Scores to use for <Episode ['Girls Band Cry', 2024, 1x5]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
2024-10-02 22:29:43|INFO    |subliminal_patch.score          |<JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass [<Language: alpha3=jpn>]>: Computed score 331 with final matches {'episode', 'series', 'season', 'hearing_impaired', 'year'}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |<JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN].ass [<Language: alpha3=jpn>]>: Found matches {'series', 'season', 'episode', 'year'}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.score          |Scores to use for <Episode ['Girls Band Cry', 2024, 1x5]>: {'hearing_impaired': 1, 'streaming_service': 1, 'video_codec': 2, 'resolution': 2, 'audio_codec': 3, 'source': 7, 'release_group': 14, 'episode': 30, 'season': 30, 'year': 90, 'series': 180, 'hash': 359}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.score          |Matched hearing_impaired|
2024-10-02 22:29:43|INFO    |subliminal_patch.score          |<JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN].ass [<Language: alpha3=jpn>]>: Computed score 331 with final matches {'episode', 'series', 'season', 'hearing_impaired', 'year'}|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |<JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass [<Language: alpha3=jpn>]>: Trying to download subtitle with matches {'episode', 'series', 'season', 'hearing_impaired', 'year'}, score: 331; release(s): [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass|
2024-10-02 22:29:43|INFO    |subliminal_patch.core           |Downloading subtitle <JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass [<Language: alpha3=jpn>]>|
2024-10-02 22:29:43|DEBUG   |urllib3.connectionpool          |https://jimaku.cc:443 "GET /entry/2698/download/%5BNekomoe%20kissaten&LoliHouse%5D%20GIRLS%20BAND%20CRY%20-%2005%20%5BWebRip%201080p%20HEVC-10bit%20AAC%20ASSx2%5D%5BJPN%5D%5BLinebreak%5D.ass HTTP/1.1" 200 None|
2024-10-02 22:29:43|DEBUG   |root                            |BAZARR got this Radarr version from its API: |
2024-10-02 22:29:43|INFO    |subliminal_patch.subtitle       |Guessing encoding for language ja|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.subtitle       |Trying encodings ['utf-8', 'shift-jis', 'cp932', 'euc_jp', 'iso2022_jp', 'iso2022_jp_1', 'iso2022_jp_2', 'iso2022_jp_2004', 'iso2022_jp_3', 'iso2022_jp_ext']|
2024-10-02 22:29:43|INFO    |subliminal_patch.subtitle       |Guessed encoding utf-8|
2024-10-02 22:29:43|ERROR   |subliminal_patch.subtitle       |PySRT-parsing failed, trying pysubs2|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.subtitle       |Trying parsing with PySubs2|
2024-10-02 22:29:43|DEBUG   |root                            |at line 1: section heading ﻿[Script Info]|
2024-10-02 22:29:43|DEBUG   |root                            |at line 10: section heading [V4+ Styles]|
2024-10-02 22:29:43|DEBUG   |root                            |at line 22: section heading [Events]|
2024-10-02 22:29:43|INFO    |subliminal_patch.subtitle       |Got format: ass|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |All languages downloaded|
2024-10-02 22:29:43|INFO    |subliminal_patch.core_persistent|Downloaded 1 subtitle(s)|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.subtitle       |Will assume srt format|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |Subtitle formats requested: ('srt',)|
2024-10-02 22:29:43|DEBUG   |subliminal_patch.core           |Saving <JimakuSubtitle: [Nekomoe kissaten&LoliHouse] GIRLS BAND CRY - 05 [WebRip 1080p HEVC-10bit AAC ASSx2][JPN][Linebreak].ass [<Language: alpha3=jpn;hi=True>]> to 'E:\\Anime\\Girls Band Cry\\Season 1\\Girls Band Cry - S01E05 - Raise Your Voice WEBDL-1080p.ja.sdh.srt'|
2024-10-02 22:29:43|DEBUG   |root                            |BAZARR Subtitles file saved to disk: E:\Anime\Girls Band Cry\Season 1\Girls Band Cry - S01E05 - Raise Your Voice WEBDL-1080p.ja.sdh.srt|
```

EDIT: Reworded, post said previously misleadingly "ASS subtitle file is converted into a SRT subtitle file", when actually no file conversion is done, the file is only saved with the wrong file extension

EDIT 2: Full log, cleared before doing an automatic subtitle search on one episode, reproducing the issue
https://gist.github.com/VeikkoLehmuskorpi/bc83757fb28a0e6e823d93aa7a31517a

**Comment by JaiZed** [comment] 2024-10-02 22:32
I cannot reproduce this issue.
Using your steps, I was able to download a file in the ASS format successfully.
The only thing I can think of is that use original format is not actually set in your language profile.

The language profile that you have attached to this issue is not a real one.
It does not show any language at all (but it does show use original format is enabled).

Please show us the actual language profile that you are using.

**Comment by VeikkoLehmuskorpi** [comment] 2024-10-03 16:21
@JaiZed I had accidentally cleared my "Languages Filter" in "Languages" settings, which also cleared the language selection from my language profile. I have now set the language correctly on the language profile, and saved all changes. It's the only language profile I have. I have reapplied the language profile on the series, but the issue still persists 

"Languages Filter" set
![20241003_chrome_i3B1kcIGxU](https://github.com/user-attachments/assets/2074a630-29d5-4aa4-b2b8-8bb36489d9d9)

Language profile with a language set
![20241003_chrome_it9sgodORq](https://github.com/user-attachments/assets/5dda0b6f-49dd-4d2f-96b6-1ad705441f5e)

Series settings
![20241003_chrome_m7v3qTohdC](https://github.com/user-attachments/assets/ce28f935-37c2-47bb-b236-38c9cb8f6c47)

**Comment by boydaihungst** [comment] 2024-10-04 00:30
If I remember correctly, it happens when you use one of these options. For now only sync doesn't convert it to srt file. 
![Screenshot_20241004-072649_Firefox_Nightly](https://github.com/user-attachments/assets/f495853d-92d5-45f1-901f-5d76e3c65686)

**Comment by JaiZed** [comment] 2024-10-04 01:24
@boydaihungst What you have described is normal behaviour when any of those settings are enabled (conversion to SRT files)
The original poster had none of them enabled and that has surfaced a specific bug that we now understand and are working on fixing.

**Comment by morpheus65535** [comment] 2024-10-12 15:37
Should be fixed in upcoming beta. Let me know if it's not the case and thanks for reporting!

**Closed by morpheus65535** 2024-10-12 15:37 UTC
