### ISSUE TITLE
Discord notifications stopped to work

### ISSUE THREAD

**Issue by TRaSH-** [morpheus65535/bazarr#676] opened 2019-11-23 17:40 UTC
Using DEV version (dockers) and it looks like the discord notifications isn't working anymore,
it might be even a apprise issue

```
23/11/2019 16:04:17|DEBUG   |apprise                         |Loaded URL: discord://597360787580911646/X5MENbxZnhCWg-DreOwJBqOjoq21yA-sD6rOgf_1JnofY3-qm8lkg8ztayolLeHQO6-F/?format=text&tts=no&verify=yes&image=no&footer=no&footer_logo=yes&avatar=no&overflow=upstream|
23/11/2019 16:04:17|DEBUG   |apprise.URLBase                 |Discord POST URL: https://discordapp.com/api/webhooks/xxx (cert_verify=True)|
23/11/2019 16:04:17|DEBUG   |apprise.URLBase                 |Discord Payload: {'tts': False, 'content': 'Bazarr test notification\r\nTest notification', 'wait': True}|
23/11/2019 16:04:17|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): discordapp.com:443|
23/11/2019 16:04:17|DEBUG   |subliminal_patch.http           |DNS: Falling back to default DNS or IP on discordapp.com|
23/11/2019 16:04:18|DEBUG   |urllib3.connectionpool          |https://discordapp.com:443 "POST /api/webhooks/xxxxx/xxxx HTTP/1.1" 400 58|
23/11/2019 16:04:18|WARNING |apprise.URLBase                 |Failed to send Discord notification: Bad Request - Unsupported Parameters., error=400.|
23/11/2019 16:04:18|DEBUG   |apprise.URLBase                 |Response Details:
{"message": "Cannot send an empty message", "code": 50006}|
```

**Comment by caronc** [comment] 2019-11-23 18:32
I'll look into this when I get home later today. Discord got a bit of an overhaul recently. You can now push attachments/images to it. I didn't realize I broke the existing method when I did my own internal testing.  I'll look into this further and keep you posted. Thank you for using the dev branch (so I didn't have to learn about this after a release :wink:).

**Comment by morpheus65535** [comment] 2019-11-23 18:41
@caronc we are still using 0.7.9. I need to try to update to latest before you put to much work in this.

**Comment by caronc** [comment] 2019-11-23 19:02
Oh, I was under the impression the OP was using my dev branch. He was referring to yours. Well that makes sense; Oops! 😳.  Sorry for hijacking this thread. Apprise v0.81 will get you a few more notification services, but won't touch Discord or any issue I'm aware of in it.

**Comment by dualznz** [comment] 2019-11-23 20:15
I have a working solution that appears to be working
clone [https://github.com/caronc/apprise](https://github.com/caronc/apprise) to your server then in `/opt/bazarr/libs` backup "apprise" to "apprise.b" then you unpack the cloned package from "caronc / apprise" to `/opt/bazarr/libs/apprise` then restart the bazarr service and try to send a push notification to discord and it should return a test response on your discord server.

**Comment by morpheus65535** [comment] 2019-11-24 14:31
I've tested upgrading apprise to 0.8.1 but it didn't fix the issue.

@caronc It seems there's something wrong with the payload when you get to send it: https://github.com/caronc/apprise/blob/7b4221039edc857faa601e2e09f4e3998d2b9adc/apprise/plugins/NotifyDiscord.py#L322

Here's the part of code in Bazarr trying to send the notification: https://github.com/morpheus65535/bazarr/blob/2602a0550dfadaee2081dbac16eb0760e32535e1/bazarr/main.py#L2104

Can you take a look please? Thanks!

**Comment by caronc** [comment] 2019-11-24 18:09
I'll try to keep this thread updated with what i learn in a concurrent one that was opened against Apprise.  In short: I can't reproduce this; it works every time for me.

Some thoughts:
* Could this be some abuse or webhook limitation reached?  Seems unlikely that so many people would be all impacted on the exact same day.
* What happens if you generate a new webhook?
* As a test can one (or all) of you just try installing Apprise using the upstream libraries and not the frozen version-ed ones in the Bazarr environment...  _just as a test_:
```bash
pip install apprise

cat << _EOF > discord.cfg
# URL based on OP's post:
discord:/{webhook}/?format=text&tts=no&verify=yes&image=no&footer=no&footer_logo=yes&avatar=no
_EOF

apprise -c discord.cfg -b "test"
```

Thoughts?

**Comment by morpheus65535** [comment] 2019-11-24 22:15
@caronc My tests were all done using a brand new server and webhook. I'll try to do it outside of Bazarr. later tonight.

**Comment by caronc** [comment] 2019-11-24 22:18
No problem; :slightly_smiling_face:  I won't be around to fix anything more tonight, but just make sure to check using [this branch](https://github.com/caronc/apprise/tree/179-discord-error-50006). The [changes](https://github.com/caronc/apprise/pull/180/files) were very subtle. I'll be interested in hearing how it goes!

**Comment by morpheus65535** [comment] 2019-11-25 01:20
Should be fixed in dev branch right now. Enjoy!

**Closed** 2019-11-25 01:24 UTC
