### ISSUE TITLE
[Bug] Manually executing a task breaks the scheduler

### ISSUE THREAD

**Issue by hotio** [morpheus65535/bazarr#161] opened 2018-09-29 10:57 UTC
When doing a clean restart of Bazarr and letting the scheduler wait 5 minutes, everything gets executed as expected for the `Update movies list from Radarr` task, is probably the same for other tasks.

```
29/09/2018 12:38:51|INFO|Bazarr is started and waiting for request on http://0.0.0.0:6767/|
29/09/2018 12:43:51|DEBUG|Starting movie sync from Radarr.|
29/09/2018 12:43:51|DEBUG|Starting new HTTP connection (1): radarr:7878|
29/09/2018 12:43:51|DEBUG|http://radarr:7878 "GET /api/profile?apikey=apikey HTTP/1.1" 200 None|
29/09/2018 12:43:51|DEBUG|Starting new HTTP connection (1): radarr:7878|
29/09/2018 12:43:51|DEBUG|http://radarr:7878 "GET /api/movie?apikey=apikey HTTP/1.1" 200 None|
29/09/2018 12:43:52|DEBUG|All movies synced from Radarr into database.|
29/09/2018 12:43:52|DEBUG|All movie missing subtitles updated in database.|
```
So far so good.....

When manually clicking on the refresh task icon to force a execution of the task, the task doesn't get executed and even worse the scheduler will not execute the task for the next 5 minute intervals.

See the 'Next execution' time in the below screenshot.
![tasks](https://user-images.githubusercontent.com/26902309/46244938-a3097300-c3e6-11e8-939f-c2fcad861a84.png)

The log also indicates the task no longer starting
```
29/09/2018 12:48:52|DEBUG|All movies synced from Radarr into database.|
29/09/2018 12:48:52|DEBUG|All movie missing subtitles updated in database.|
29/09/2018 12:49:46|DEBUG|Starting new HTTPS connection (1): api.github.com:443|
29/09/2018 12:49:47|DEBUG|https://api.github.com:443 "GET /repos/morpheus65535/Bazarr/releases HTTP/1.1" 200 None|
29/09/2018 12:49:54|DEBUG|Starting new HTTPS connection (1): api.github.com:443|
29/09/2018 12:49:54|DEBUG|https://api.github.com:443 "GET /repos/morpheus65535/Bazarr/releases HTTP/1.1" 200 None|
29/09/2018 12:55:12|DEBUG|Starting new HTTPS connection (1): api.github.com:443|
29/09/2018 12:55:13|DEBUG|https://api.github.com:443 "GET /repos/morpheus65535/Bazarr/releases HTTP/1.1" 200 None|
29/09/2018 12:56:29|DEBUG|Starting new HTTPS connection (1): api.github.com:443|
29/09/2018 12:56:29|DEBUG|https://api.github.com:443 "GET /repos/morpheus65535/Bazarr/releases HTTP/1.1" 200 None|
```

**Comment by morpheus65535** [comment] 2018-10-11 15:03
Do you still have the issue with 0.6.6.1?

**Comment by hotio** [comment] 2018-10-13 16:49
Yes the issue is still there, notice that when nothing manually has been done the 'Next Execution' says `in x minutes`, when pressing the task start button it changes to `now` and after that to `x minutes ago`. The backend behaves like the frontend reports it, so not an UI issue...

**Comment by morpheus65535** [comment] 2018-10-17 03:47
I've just tested it (sorry for the delay) and I cannot reproduce this issue. Even if I run Radarr sync task manually, it still kick in 5 minutes exactly after the moment I've press the run now button:

```
16/10/2018 23:35:20|DEBUG|All movies synced from Radarr into database.|
16/10/2018 23:35:20|DEBUG|All movie missing subtitles updated in database.|
16/10/2018 23:40:20|DEBUG|All movies synced from Radarr into database.|
16/10/2018 23:40:20|DEBUG|All movie missing subtitles updated in database.|
```

Maybe you can give me a little bit more information on your setup?

**Comment by hotio** [comment] 2018-10-23 14:35
Strange....I'm running it in an Ubuntu 18.04 docker container on an Ubuntu 18.04 host. Perhaps something different with python on windows vs *nix...

**Comment by morpheus65535** [comment] 2018-10-23 15:05
I've have instances of Bazarr runing on Widnows 10 and also on docker on Debian 9. Maybe something related to your Docker image? I don't see what but I am not able to reproduce your issue anywhere. :-/

**Comment by morpheus65535** [comment] 2018-11-15 13:33
@hotio doesn't use Bazarr anymore until we merge with SZ. As I cannot reproduce, I'll close this issue. If someone else have the same problem, please open a new one.

**Closed by morpheus65535** 2018-11-15 13:33 UTC
Labels: investigating

**Comment by hotio** [comment] 2019-04-21 23:31
I can confirm that this is no longer an issue.
