### ISSUE TITLE
Bazarr doesn't add episodes from Series

### ISSUE THREAD

**Issue by Neya5** [morpheus65535/bazarr#2299] opened 2023-11-12 14:47 UTC
Hi,

Bazarr doesn't sync correctly the series from Sonarr, the episodes are emplty and the subtitles can't be downloaded.
When I checked the log I have this issue : 

_Job "Sync with Sonarr (trigger: interval[1:00:00], next run at: 2023-11-12 15:19:08 UTC)" raised an exception__

`Traceback (most recent call last):
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: near "RETURNING": syntax error
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/neyashi/Apps/bazarr/bazarr/sonarr/sync/series.py", line 100, in update_series
    sync_episodes(series_id=show[\'id\'], send_event=send_event)
  File "/home/neyashi/Apps/bazarr/bazarr/sonarr/sync/episodes.py", line 116, in sync_episodes
    added_episodes = database.execute(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/orm/scoping.py", line 724, in execute
    return self._proxied.execute(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2229, in execute
    return self._execute_internal(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/orm/session.py", line 2124, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/orm/bulk_persistence.py", line 1225, in orm_execute_statement
    result = conn.execute(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/sql/elements.py", line 486, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 2326, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/neyashi/Apps/bazarr/bazarr/../libs/sqlalchemy/engine/default.py", line 748, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "RETURNING": syntax error
[SQL: INSERT INTO table_episodes (audio_codec, audio_language, episode, episode_file_id, file_size, format, monitored, path, resolution, "sceneName", season, "sonarrEpisodeId", "sonarrSeriesId", title, video_codec) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING "sonarrEpisodeId", path, "sonarrSeriesId"]
[parameters: (\'EAC3 Atmos\', "[\'English\']", 1, 1, 2611161221, \'WEBDL\', \'True\', \'/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E01 - Shaerrawed WEBDL-1080p.mkv\', \'1080p\', \'The Witcher S03E01 1080p WEB h264-ETHEL\', 3, 26, 1, \'Shaerrawedd\', \'h264\', \'EAC3 Atmos\', "[\'English\']", 2, 4, 2833511656, \'WEBDL\', \'True\', \'/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E02 - Unbound WEBDL-1080p.mkv\', \'1080p\', \'The.Witcher.S03E02.Unbound.1080p.NF.WEB-DL.DDP5.1.x264-NTb[TGx]\', 3, 27, 1, \'Unbound\', \'h264\', \'EAC3 Atmos\', "[\'English\']", 3, 5, 3262213890, \'WEBDL\', \'True\', \'/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E03 - Reunion WEBDL-1080p.mkv\', \'1080p\', \'The.Witcher.S03E03.Reunion.1080p.NF.WEB-DL.DDP5.1.x264-NTb[TGx]\', 3, 28, 1, \'Reunion\', \'h264\', \'EAC3 Atmos\', "[\'English\']", 4, 3, 2251672614 ... 20 parameters truncated ... 3, 30, 1, \'The Art of Illusion\', \'h264\', \'EAC3 Atmos\', "[\'English\']", 6, 67, 1918843267, \'WEBDL\', \'True\', "/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E06 - Everybody Has a Plan \'til They Get Punched in the Face WEBDL-1080p.mkv", \'1080p\', \'The.Witcher.S03E06.Everybody.Has.a.Plan.til.They.Get.Punched.in.the.Face.1080p.NF.WEB-DL.DDP5.1.x264-NTb[TGx]\', 3, 31, 1, "Everybody Has a Plan \'til They Get Punched in the Face", \'h264\', \'EAC3 Atmos\', "[\'English\']", 7, 64, 2124675868, \'WEBDL\', \'True\', \'/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E07 - Out of the Fire, Into the Frying Pan WEBDL-1080p.mkv\', \'1080p\', \'The.Witcher.S03E07.Out.of.the.Fire.Into.the.Frying.Pan.1080p.NF.WEB-DL.DDP5.1.x264-NTb[TGx]\', 3, 32, 1, \'Out of the Fire, Into the Frying Pan\', \'h264\', \'EAC3 Atmos\', "[\'English\']", 8, 65, 2649096771, \'WEBDL\', \'True\', \'/home/neyashi/media/TV Shows/The Witcher/Season 3/The Witcher - S03E08 - The Cost of Chaos WEBDL-1080p.mkv\', \'1080p\', \'The.Witcher.S03E08.The.Cost.of.Chaos.1080p.NF.WEB-DL.DDP5.1.x264-NTb[TGx]\', 3, 33, 1, \'The Cost of Chaos\', \'h264\')]
(Background on this error at: https://sqlalche.me/e/20/e3q8)`

**Comment by morpheus65535** [comment] 2023-11-12 14:52
Forth duplicate of #2281. Please use search before opening a new issue.

**Closed** 2023-11-12 14:52 UTC
Labels: duplicate
