### ISSUE TITLE
Bazarr wiping out config on uninstall in programdata

### ISSUE THREAD

**Issue by klepp0906** [morpheus65535/bazarr#1768] opened 2022-03-19 21:58 UTC
**Describe the bug**
I know youve done some work on preventing wiping of config on updates/upgrades (and i cant speak as to whether that is fixed or not as ive just now formatted windows and reinstalled to programdata again).  what i can speak to is the behavior on uninstallation.  If you install to the programdata directory it wipes out the entire folder and takes the config/db/backups with it.  
This is not ideal.  Hoping it can be fixed/changed to keep the settings stuff intact in line with the other arrs.

**To Reproduce**
1. Install bazarr to %programdata\bazarr
2. navigate to said folder in explorer
3. uninstall bazarr and watch the entire folder poof

**Expected behavior**
bazarr should leave the equivalent to what the other arrs leave behind.  at a minimum the backups/cfg/db.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.3
 - Radarr version [e.g. v 0.2.0.0001]
 - Sonarr version [e.g. v 2.0.0.0001]
 - OS: Windows 11

**Additional context**

**Comment by morpheus65535** [comment] 2022-03-20 13:39
I've just updated the installer to prevent deletion of non-empty application directory during uninstall.

**Comment by klepp0906** [comment] 2022-03-20 14:56
doing gods work.  i appreciate it very much morpheus <3

**Comment by morpheus65535** [comment] 2022-03-22 16:58
If you install using the new installer provided 2 days ago, it won't delete the config.

But, for sake of God, I've told dozens of times to not install Bazarr in %programdata% but you keep trying it. I've made what I could to protect you from yourself but I think we get to a point I must let you hang yourself.

**Comment by morpheus65535** [comment] 2022-03-22 22:44
Sorry I didn't want to tell that I've told you specifically dozens of times but more to users having this issue.Yes the problem is definitely related to ProgramData usage.

I've just deployed a brand new Windows 10 VM, installed Bazarr to C:\ProgramData\Bazarr, configure it properly and uninstall it. No configuration are lost at all and in fact, there's more leftover folders and files that I'm going to deal with in the upcoming installer.

Right now, I'm not sure what are the step to reproduce your issue...

**Comment by klepp0906** [comment] 2022-03-22 23:01
no no, you misunderstand i think.  uninstalling did in fact leave the essential data behind this time which is great.  It was when I went to reinstall it to the same directory, it wiped it out then :(

**Comment by morpheus65535** [comment] 2022-03-22 23:02
Ok let me look into it later tonight.

**Comment by morpheus65535** [comment] 2022-03-23 01:54
@klepp0906 should be fine with installer v1.15. Can you give it a try and confirm please?

**Comment by klepp0906** [comment] 2022-03-23 08:16
sure, just gotta tell me where to find installer v 1.15 :)

**Comment by morpheus65535** [comment] 2022-03-23 10:01
Same download link as usual!

**Comment by klepp0906** [comment] 2022-03-23 10:24
ah.  it literally JUST now popped up for me.  I was making a post with a screenshot showing you what the releases page showed/said and voila.  how peculiar.  i assumed you werent having it up for the masses just yet, hence my asking.  will report back once i get the kids to school at worst.

**Comment by klepp0906** [comment] 2022-03-23 10:44
Okay, tested the uninstallation and reinstallation.  seems to be leaving everything in place now.  

going to have to assume it would seamlessly begin working as due to timing and my db/config being from the development branch - i actually have to purge my settings to get bazarr to install and work correctly, then update to development, then restore my db.  

at least until i can get back into the master branch.

whats the best way to watch out for that?  when 1.0.4 becomes master? (i assume thats the exact point i can change my settings > general > updates > back to master?)

thanks for ironing this out btw.  i know based on your responses it became frustrating but on the bright side it will have saved you any of these inquiries and posts in the future, for good.

**Comment by morpheus65535** [comment] 2022-03-23 11:19
You can move back and forth between 1.0.3 and 1.0.4 without any issue. Let me know once you'll be able to test this branch change so we know for sure it's behind us.

**Comment by klepp0906** [comment] 2022-03-23 11:45
okay, so far with 100% consistency as ive been trying to iron it out on my end... if i install bazarr clean, it works.  the minute I restore my backup, it breaks.  

if i install bazarr clean, then change to development branch and force it to update THEN restore my db, it works. 

i currently have it working, on the development branch, with my db restored.  I'll change over to the master and let it update on its own and get back to you once it does.  if it keeps working - great.  perhaps my issue was trying to restore the backup beforehand.  I havent tested a change back AFTER getting the restore to take i dont think. 

will get back to you asap.

**Comment by morpheus65535** [comment] 2022-03-23 12:08
This looks more like a restore issue. Let me know and we'll look into it.

**Comment by klepp0906** [comment] 2022-03-23 16:42
looks like a definite issue of sorts then.  I just got home, clicked the update task after having set it to master again and this was the result

![image](https://user-images.githubusercontent.com/10392920/159751359-f269df2b-736f-4d86-ab6c-3515e3e5b6ae.png)

broken again :(

**Comment by morpheus65535** [comment] 2022-03-23 17:09
Send me your backup in PM on Discord so I can try to restore it and see whats happening under the hood.

**Comment by morpheus65535** [comment] 2022-03-25 10:56
Should be fixed properly in upcoming beta. Of course moving back to master 1.0.3 will remove the configs like it does before. At least now, when upgrading from one beta to another, you should be fine. Once merged 1.0.4 to master, everything should be ok.

**Closed by morpheus65535** 2022-03-25 10:56 UTC
Labels: bug, awaiting feedback, fixed
