### ISSUE TITLE
Error saving Subtitles file to disk - manual upload of .srt

### ISSUE THREAD

**Issue by moostmartijn** [morpheus65535/bazarr#2111] opened 2023-04-06 19:33 UTC
**Describe the bug**
Bazarr finds all the files for the series 'The Lord of the Rings - The Rings of Power', except for the .srt file of 'The Lord of the Rings - The Rings of Power - S01E06 - Udûn WEBDL-2160p AMZN HDR.mkv' 

In the folder of the serie is a .srt for the specific episode. Somehow Bazarr did not find the .srt so it thinks it's missing. Whenever I try to upload the .srt manually, I receive an error:

```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/subtitles/upload.py", line 99, in manual_upload_subtitle
    saved_subtitles = save_subtitles(path,
  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 1157, in save_subtitles
    os.remove(subtitle_path)
OSError: [Errno 5] I/O error: \'/media/series/The Lord of the Rings - The Rings of Power/Season 1/The Lord of the Rings - The Rings of Power - S01E06 - Udûn WEBDL-2160p AMZN HDR.nl.srt\
```

The path for Bazarr is the same as the path of Sonarr. I also set correct write permissions on the series folder and all the subfolders. 

Maybe it's because of the special character 'û' ?

I don't have any errors with other series. I did not have to manually upload any other .srt. There were no other .srt missing in Bazarr when they were available in the folder.

**To Reproduce**
1. Sync Sonarr with Bazarr
2. Upload missing .srt manually for episode
3. Receive error

**Expected behavior**
Ability to upload the .srt without any problems. 

**Screenshots**

<img width="790" alt="Schermafbeelding 2023-04-06 om 21 28 57" src="https://user-images.githubusercontent.com/31592734/230476458-8008ff6e-3227-43d7-bc72-5225d41d3c0d.png">

<img width="1679" alt="Schermafbeelding 2023-04-06 om 21 29 30" src="https://user-images.githubusercontent.com/31592734/230476552-2b816e93-e1ff-4f86-96c8-5e73afade06e.png">

**Software (please complete the following information):**
 - Bazarr: V1.2.0
 - Radarr version 4.3.2.6857
 - Sonarr version 3.0.10.1567
 - OS: MacOSX (Docker Desktop)

**Additional context**

**Comment by morpheus65535** [comment] 2023-04-06 19:36
Yes it's a duplicate of #1961. I've never been able to reproduce the issue.

**Closed by morpheus65535** 2023-04-06 19:36 UTC

**Comment by morpheus65535** [comment] 2023-04-06 19:49
It seems to be a Python/file system incompatibility where files are saved using some fs encoding but reed using another... really strange :-/

**Comment by moostmartijn** [comment] 2023-04-06 19:59
Unfortunately :( Somehow I'm not able to remove the episode from the Missing series list. I tried renaming the files, but it still points to the path with the special character. Is there another way to remove it from the missing series subtitles list?

**Comment by morpheus65535** [comment] 2023-04-06 21:15
You must rename the file and make sure Sonarr or Radarr catch the change. Once it's done, it should be reflected in Bazarr.
