### ISSUE TITLE
Regarding the problem that "assrt" in "providers" always reports GuessitException

### ISSUE THREAD

**Issue by hoong7** [morpheus65535/bazarr#1151] opened 2020-10-15 13:05 UTC
**Describe the bug**

After running bazarr, follow the tutorial and add "zimuku" and "assrt" to "providers". Assrt also adds api according to the prompts, but in actual operation, I found that bazarr only finds and downloads subtitles from "zimuku" , And "assrt" will always prompt "GuessitException" and "Next Retry in 10 minutes", I don't know where the problem is, I hope it can be resolved

**To Reproduce**

**Expected behavior**

I hope to find subtitles through assrt normally, because the subtitle quality of assrt may better 

**Screenshots**
![image](https://user-images.githubusercontent.com/71035460/96129151-dadda780-0f28-11eb-8b8f-443d4353aa95.png)
![image](https://user-images.githubusercontent.com/71035460/96129179-e29d4c00-0f28-11eb-8885-e13876bdaca0.png)
![image](https://user-images.githubusercontent.com/71035460/96129281-03fe3800-0f29-11eb-9dee-76d4e792a820.png)
![image](https://user-images.githubusercontent.com/71035460/96129408-2bed9b80-0f29-11eb-8101-3fa9c923c5ef.png)

**Software (please complete the following information):**
-Bazarr: [e.g.v 0.9.0.5]
-Radarr version [e.g. v 0.2.0.1504]
-Sonarr version [e.g. v 3.0.4.982]
-OS: [e.g. Windows 10 2004 19041.572]

**Comment by morpheus65535** [comment] 2020-10-15 13:09
Please provide the log file, not screenshot of some part of it...

**Comment by hoong7** [comment] 2020-10-15 13:16
> Please provide the log file, not screenshot of some part of it...

Is it the same log file as the #1150 screenshot?

**Comment by hoong7** [comment] 2020-10-15 17:15
I don’t know if it’s these logs,
10-16 1:03 I saw that an error occurred at exactly this point in time. I searched for "crtl+f" in the log for all logs related to "assrt", as well as screenshots of all logs before and after. I don’t know if it can be helpful to judge the problem of the bazarr I use, thanks

![image](https://user-images.githubusercontent.com/71035460/96163159-1a69bb00-0f4c-11eb-83e5-ea2319aec6ce.png)
![image](https://user-images.githubusercontent.com/71035460/96163192-28b7d700-0f4c-11eb-85a2-d20e7710915f.png)
![image](https://user-images.githubusercontent.com/71035460/96163313-54d35800-0f4c-11eb-99b4-9ecf70474305.png)
![image](https://user-images.githubusercontent.com/71035460/96163371-661c6480-0f4c-11eb-88f8-1a7a7407f1af.png)
![image](https://user-images.githubusercontent.com/71035460/96163518-9237e580-0f4c-11eb-868d-e77463c05f66.png)
![image](https://user-images.githubusercontent.com/71035460/96163587-a7147900-0f4c-11eb-9b2c-e53c3fd86ac1.png)

**Comment by morpheus65535** [comment] 2020-10-15 17:19
What part of "log file" didn't you understand? I need a text file, not  f***ing screenshot. We are repeating this to you since 2 days now. It's getting exhausting!

**Comment by hoong7** [comment] 2020-10-15 17:57
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5386849/bazarr.log)

**Comment by morpheus65535** [comment] 2020-10-15 18:12
I don't have an ASSRT account and don't read Chinese so I'm unable to try to reproduce this issue.

**Comment by hoong7** [comment] 2020-10-15 18:27
> I don't have an ASSRT account and don't read Chinese so I'm unable to try to reproduce this issue.

Ok but thanks anyway
In this situation, what problems can't be found in the log file?
Or what can I do for this problem
Or, I find their ASSRT API documentation and use Google to translate it to you?

**Comment by morpheus65535** [comment] 2020-10-16 00:09
Should be fixed in dev branch right now.

**Comment by morpheus65535** [comment] 2020-10-22 00:22
Is it fixed? Can I close this issue?

**Comment by morpheus65535** [comment] 2020-10-23 01:14
No news, good news. Re-open if required.

**Closed by morpheus65535** 2020-10-23 01:14 UTC
Labels: awaiting feedback
