### ISSUE TITLE
Purging episode data in get_episodes.py if connection fails

### ISSUE THREAD

**Issue by mortenmhp** [morpheus65535/bazarr#414] opened 2019-04-26 23:30 UTC
**Describe the bug**
I'm running a fairly slow server for sonarr/bazarr meaning that sometimes sonarr can't respond with the episode list for a series within 15s. I've increased the timeout manually, but it resets at every update and every now and then a connection error happens anyway. The issue is that whenever an exception is thrown for the request to get the episode list from sonarr, the episodes won't be added to current_episodes_sonarr and therefore they'll end up on the list of episodes to be deleted from the DB. This means that the next time the request goes through, the DB has to be rebuilt from the ground for that show. This seems unreasonable.

**To Reproduce**
Throw exception in get_episodes.py during the request to the episodes API in sonarr.

**Solution**
A solution could be to move the addition of episodes to the deleted_episodes list inside the "for seriesId in seriesIdList:" for loop inside the else clause of the try/except block to do it on a per series basis only if the request goes through. The calculation would obviously have to be modified as well.
If this is the only way episode data is deleted(e.g. after a show is deleted in sonarr), it may need to be done slightly differently if sonarrs response throws an exception for an unknown series, but it seems like it could be done quite easily.

**Comment by morpheus65535** [comment] 2019-04-27 00:41
Duplicate of #397. Fixed in dev branch if you want to test.

**Closed** 2019-04-27 00:41 UTC
Labels: duplicate
