### ISSUE TITLE
BsPlayer not working

### ISSUE THREAD

**Issue by Tenderlaan54** [morpheus65535/bazarr#1235] opened 2021-01-21 20:59 UTC
Keep getting this error for provider BsPlayer:

_HTTPConnectionPool(host='s105.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: /v1.php (Caused by NewConnectionError(': Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds..._

I am on version 0.9.0.8

Sometimes this provider works, but that is only 1 or 2 times a week that it works. tested with different ip addresses.

**Comment by mkanet** [comment] 2021-01-21 21:08
I am having the same issue.  However, mine is a brand new setup.

**Comment by morpheus65535** [comment] 2021-01-22 01:00
Could be duplicate from #805.

**Comment by Tenderlaan54** [comment] 2021-01-22 14:40
I think this issue is separate from the other. I already get this message during the first search. I have tested this on different ip addresses. It does work via the bsplayer app itself.

**Comment by morpheus65535** [comment] 2021-01-23 04:11
I've just pushed a fix to dev branch. Can you test it? BTW dev branch includes breaking changes and you won't be able to easily come back fro 0.9.1 to previous version.

**Comment by Tenderlaan54** [comment] 2021-01-23 07:50
strangely enough it now suddenly seems to work again. Still on v0.9.0.8 and I see that last night suddenly subtitles were downloaded via bsplayer again. go test the new version tonight.

**Comment by morpheus65535** [comment] 2021-01-23 14:44
BTW fixes are done in dev branch which is now 0.9.1.

**Comment by Tenderlaan54** [comment] 2021-01-23 16:31
okay but it seems to be working fine now again. Thought you were talking about a normal update. Will see if I can get the dev version working. By the way, great that you do all of this. Bazarr is a really great addition.

**Comment by morpheus65535** [comment] 2021-01-23 21:33
It will fails again in a couple of days when they are going to have problems with one of their server. Prior to my fix, Bazarr choose one random server from their servers farm. If this server is down, the provider was simply discarded. Now, I test servers in random loop and as soon as I get one that is working, I make requests to this one until next time.

I'll close this issue. If you still face it after upgrading to 0.9.1, please reopen it.

**Closed by morpheus65535** 2021-01-23 21:33 UTC
Labels: awaiting feedback

**Comment by COTMO** [comment] 2021-04-23 07:59
Keep getting this in my logs:
HTTPConnectionPool(host='s5.api.bsplayer-subtitles.com', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdfe68392e0>: Failed to establish a new connection: [Errno 111] Connection refused')), retrying in 5 seconds...

Version: 0.9.4

**Comment by KnifeFed** [comment] 2021-06-16 15:54
I have the same issue in 0.9.5 and I had to delete the BSPlayer provider for subtitle searching to work at all, i.e. it just retries the connection forever and doesn't try any other providers.
