### ISSUE TITLE
Existing subtitles are still "missing"

### ISSUE THREAD

**Issue by tordenflesk** [morpheus65535/bazarr#2583] opened 2024-07-17 23:51 UTC
**Describe the bug**
See screenshot, applies to all series/movies

**Screenshots**
https://i.imgur.com/LQy79y2.png

**Software (please complete the following information):**
 - Bazarr: v1.4.3

**Comment by jooleer** [comment] 2024-07-19 07:48
You can try to temporarily disable `Sub-Zero Modifications` under Settings --> Subtitles 

The errors are probably caused by a character in one of the subtitles that was not recognized in the IETF listed regex characters (possible one used in Norwegian like æ  ø  å etc)

Can you please provide a link to the subtitle file for easier debugging?

**Comment by tordenflesk** [comment] 2024-07-19 15:34
No change. You want me to link you all my 2700+ subtitles?

**Comment by anderson-oki** [comment] 2024-07-19 20:07
The warning you are seeing is unrelated.

If this is a bug we need the steps to reproduce. It should be reproducible.

From a fresh instance of Bazarr, and a new profile and settings creation, how can we reproduce the issue?

**Comment by tordenflesk** [comment] 2024-07-20 03:02
Unfortunately, I don't know when this started happening, so it's difficult to pin down any possible causes. Does my config.yaml contain anything improper for Bazarr to both detect and not detect subtitles at the same time?

```
---
addic7ed:
  cookies: ''
  password: ''
  user_agent: ''
  username: ''
  vip: false
analytics:
  enabled: true
anidb:
  api_client: ''
  api_client_ver: 1
animetosho:
  anidb_api_client: ''
  anidb_api_client_ver: 1
  search_threshold: 6
anticaptcha:
  anti_captcha_key: ''
assrt:
  token: ''
auth:
  apikey: 
  password: ''
  type: null
  username: ''
avistaz:
  cookies: ''
  user_agent: ''
backup:
  day: 6
  folder: /config/backup
  frequency: Weekly
  hour: 3
  retention: 31
betaseries:
  token: ''
cinemaz:
  cookies: cinemazx_session=
  user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
cors:
  enabled: true
deathbycaptcha:
  password: ''
  username: ''
embeddedsubtitles:
  fallback_lang: en
  hi_fallback: false
  included_codecs: []
  timeout: 600
  unknown_as_fallback: true
general:
  adaptive_searching: true
  adaptive_searching_delay: 1w
  adaptive_searching_delta: 3d
  anti_captcha_provider: null
  auto_update: true
  base_url: ''
  branch: master
  chmod: '0640'
  chmod_enabled: false
  days_to_upgrade_subs: 7
  debug: false
  default_und_audio_lang: ''
  default_und_embedded_subtitles_lang: ''
  dont_notify_manual_actions: true
  embedded_subs_show_desired: true
  embedded_subtitles_parser: ffprobe
  enabled_integrations: []
  enabled_providers:
  - embeddedsubtitles
  - cinemaz
  - gestdown
  - opensubtitlescom
  - subf2m
  - supersubtitles
  flask_secret_key: 
  hi_extension: hi
  ignore_ass_subs: true
  ignore_pgs_subs: true
  ignore_vobsub_subs: true
  ip: 0.0.0.0
  language_equals: []
  minimum_score: 90
  minimum_score_movie: 80
  movie_default_enabled: true
  movie_default_profile: 1
  multithreading: true
  page_size: 1000
  page_size_manual_search: 10
  parse_embedded_audio_track: false
  path_mappings: []
  path_mappings_movie: []
  port: 6767
  postprocessing_cmd: ''
  postprocessing_threshold: 90
  postprocessing_threshold_movie: 70
  serie_default_enabled: true
  serie_default_profile: 1
  single_language: false
  skip_hashing: false
  subfolder: current
  subfolder_custom: ''
  subzero_mods: remove_HI,remove_tags,OCR_fixes,common,fix_uppercase
  theme: dark
  upgrade_frequency: 12
  upgrade_manual: true
  upgrade_subs: true
  use_embedded_subs: false
  use_postprocessing: false
  use_postprocessing_threshold: false
  use_postprocessing_threshold_movie: false
  use_radarr: true
  use_scenename: true
  use_sonarr: true
  utf8_encode: true
  wanted_search_frequency: 6
  wanted_search_frequency_movie: 6
hdbits:
  passkey: ''
  username: ''
karagarga:
  f_password: ''
  f_username: ''
  password: ''
  username: ''
ktuvit:
  email: ''
  hashed_password: ''
legendasdivx:
  password: ''
  skip_wrong_fps: false
  username: ''
legendastv:
  featured_only: false
  password: ''
  username: ''
log:
  exclude_filter: ''
  ignore_case: false
  include_filter: ''
  use_regex: false
movie_scores:
  audio_codec: 3
  edition: 1
  hash: 119
  hearing_impaired: 1
  release_group: 13
  resolution: 2
  source: 7
  streaming_service: 1
  title: 60
  video_codec: 2
  year: 30
napisy24:
  password: ''
  username: ''
opensubtitles:
  password: FZR3Tk3WcyL8Va
  skip_wrong_fps: false
  ssl: false
  timeout: 15
  use_tag_search: false
  username: tordenflesk
  vip: false
opensubtitlescom:
  include_ai_translated: false
  password: FZR3Tk3WcyL8Va
  use_hash: true
  username: tordenflesk
podnapisi:
  verify_ssl: true
postgresql:
  database: ''
  enabled: false
  host: localhost
  password: ''
  port: 5432
  username: ''
proxy:
  exclude:
  - localhost
  - 127.0.0.1
  password: ''
  port: ''
  type: null
  url: ''
  username: ''
radarr:
  apikey: 
  base_url: ''
  defer_search_signalr: true
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 11
  http_timeout: 60
  ip: 10.0.0.106
  movies_sync: 15
  only_monitored: false
  port: 7878
  ssl: false
  sync_only_monitored_movies: false
  use_ffprobe_cache: false
series_scores:
  audio_codec: 3
  episode: 30
  hash: 359
  hearing_impaired: 1
  release_group: 14
  resolution: 2
  season: 30
  series: 180
  source: 7
  streaming_service: 1
  video_codec: 2
  year: 90
sonarr:
  apikey: 
  base_url: ''
  defer_search_signalr: true
  episodes_sync: 15
  exclude_season_zero: false
  excluded_series_types: []
  excluded_tags: []
  full_update: Daily
  full_update_day: 6
  full_update_hour: 10
  http_timeout: 60
  ip: 10.0.0.106
  only_monitored: false
  port: 8989
  series_sync: 15
  ssl: false
  sync_only_monitored_episodes: false
  sync_only_monitored_series: false
  use_ffprobe_cache: false

subscene:
  password: ''
  username: ''
subsync:
  checker:
    blacklisted_languages: []
    blacklisted_providers: []
  debug: false
  force_audio: false
  gss: true
  max_offset_seconds: 60
  no_fix_framerate: true
  subsync_movie_threshold: 86
  subsync_threshold: 96
  use_subsync: true
  use_subsync_movie_threshold: true
  use_subsync_threshold: true
titlovi:
  password: ''
  username: ''
titulky:
  approved_only: false
  password: ''
  username: ''
whisperai:
  endpoint: http://127.0.0.1:9000
  loglevel: INFO
  response: 5
  timeout: 3600
xsubs:
  password: ''
  username: ''

```

**Comment by anderson-oki** [comment] 2024-07-20 03:37
Can you reproduce the issue even with a new profile, using only english?

**Comment by tordenflesk** [comment] 2024-07-20 17:28
Re-creating my profiles would appear to have cleared the bug.

**Comment by anderson-oki** [comment] 2024-07-22 11:05
If you put the old profile back does the issue comes back?

**Comment by tordenflesk** [comment] 2024-07-22 11:26
I did not keep the broken Language Profiles, no...

**Comment by anderson-oki** [comment] 2024-07-22 12:20
Ill close the issue for now as we lack enough information. Maybe next time.

**Closed** 2024-07-22 12:21 UTC
Labels: cannot reproduce
