### ISSUE TITLE
New 1.0.2 version in master released yesterday wipes the config file...

### ISSUE THREAD

**Issue by distributorofpain** [morpheus65535/bazarr#1655] opened 2021-12-31 15:29 UTC
**Describe the bug**
Received a 500 error when in the application today checking on the progress of the remaining subtitles that we being brought in.  Was on the providers page under system.  Hit refresh a few times, nothing.  Told it to restart using the human icon at the top right, immediately prompted for a login and my cached login didnt work.  Refreshed the page and everything was back to default with no login required.  No settings anywhere nor a backup config file saved in the directory.  Logs show file not found on start up.  I looked at the log files deeper and found that it was showing file not found since earlier in the day.  Thats when i checked the version and saw that it had updated yesterday/last night.

**To Reproduce**
Let system auto-update.  

**Expected behavior**
File is not overwritten or deleted.

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.0.2 master branch
 - Radarr version: 
 - Sonarr version: 
 - OS: Windows 10

**Additional context**
Wouldnt mind a backup function like radarr/lidarr/sonarr have.  I have synctoy setup to automatically grab the files.  I will configure it to grab the config file now as i have to setup bazarr again and scan everything :(    Was still testing it so i hadnt setup a basic backup yet :(  Just dont know if the config file is all thats needed or not.

Also, i checked the folder to make sure the app had permissions to the config file. i changed a setting, restarted bazarr and checked to see if the setting held, it did.  I also verified the config file had the setting change in it.

**Comment by morpheus65535** [comment] 2021-12-31 15:41
How did you install? Using the Windows installer or manually?

This issue should have been fixed in 1.0.2: https://github.com/morpheus65535/bazarr/commit/6a88596aabd49d3ba2557d3757a41268026ee603

**Comment by distributorofpain** [comment] 2021-12-31 15:52
Windows installer.  I used bazarr.exe downloaded on 12/23/2021, looks like it was in a zip file named bazarr.zip when downloaded.  I show it as an installed program as well ( if that helps verify ).  

I should note, i found a file restore program online called Recuva that was able to pull both the config and throttled providers.dat file back from being wiped.  I put them back in place after stopping the service and then upon restart the settings are back.  I saved a copy to my backup location for all *arr programs ( whew! )

**Comment by morpheus65535** [comment] 2021-12-31 16:01
Ok that's very strange because Windows installer use %programdata%\Bazarr to store config and the update process never touch that. The updater only change file in Bazarr directory (C:\Bazarr by default).

**Comment by distributorofpain** [comment] 2021-12-31 16:04
I can confirm that it installed at %programdata%\bazarr and stored the config file in a sub folder called config.  I dont have a C:\Bazarr folder

![image](https://user-images.githubusercontent.com/18275482/147831714-cd255e16-b347-40c0-adc5-048cc186ace5.png)


Note, i created the config.bak file when i doing the restore.

**Comment by morpheus65535** [comment] 2021-12-31 16:43
The leftover cleaner after upgrade only delete files from Bazarr directory, not config directory:
https://github.com/morpheus65535/bazarr/blob/master/bazarr/check_update.py#L239

The previous issue that was fixed in 1.0.2 was for users who were having their config directory inside Bazarr directory (ie: C:\Bazarr\data).

I've upgraded my test Windows machine from 1.0.1 to 1.0.2 without any issue. I have used the installer with default options.

I'll leave this issue opened to see if others are having the same issue. For now, as I can't reproduce it, there's nothing more I can do.

**Comment by redglory** [comment] 2022-01-03 18:25
HI @morpheus65535 I had the same problem (also have all config files inside a "D:\Bazarr\config" folder.

Using master branch.

Tried to change branch to "development" and upgrade didn't work as expected:
`03/01/2022 18:16:00|ERROR   |root                            |BAZARR unable to cleanup leftover files after upgrade.|'Traceback (most recent call last):\n  File "d:\\bazarr\\bazarr\\check_update.py", line 159, in apply_update\n    except Exception:\n  File "d:\\bazarr\\bazarr\\check_update.py", line 198, in update_cleaner\n    logging.debug(\'BAZARR upgrade leftover cleaner will ignore directories matching this regex: \'\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\re.py", line 250, in compile\n    return _compile(pattern, flags)\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\re.py", line 302, in _compile\n    p = sre_compile.compile(pattern, flags)\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\sre_compile.py", line 764, in compile\n    p = sre_parse.parse(p, flags)\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\sre_parse.py", line 948, in parse\n    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\sre_parse.py", line 443, in _parse_sub\n    itemsappend(_parse(source, state, verbose, nested + 1,\n  File "D:\\Bazarr\\WinPython\\python-3.8.0\\lib\\sre_parse.py", line 836, in _parse\n    raise source.error("missing ), unterminated subpattern",\nre.error: missing ), unterminated subpattern at position 0'|`

**Comment by morpheus65535** [comment] 2022-01-03 20:01
@redglory Should be fixed in upcoming beta.

**Comment by klepp0906** [comment] 2022-01-05 16:13
just came to post this.  i could not connect this morning and reinstalled over top and once again could connect  again.  cept im butt naked barebones return to default.

**Comment by morpheus65535** [comment] 2022-01-16 14:59
@klepp0906 there's a remaining issue with Bazarr installed in the directory that is normally reserved to config (%programdata%/Bazarr). I'll try to fix it n the upcoming days.

**Comment by klepp0906** [comment] 2022-01-16 15:39
I have already moved it to program files but would certainly move it back if it was confirmed fixed/viable going forward lol. 

Thank you for your time and work regardless <3 you guys are heroes to a lot of people

**Comment by morpheus65535** [comment] 2022-01-17 05:02
Should be fine now. Feel free to reopen it if it happens again.

**Closed by morpheus65535** 2022-01-17 05:02 UTC
Labels: bug, priority:medium, cannot reproduce
