### ISSUE TITLE
Provider regielive JSON Decode error

### ISSUE THREAD

**Issue by Bruny07** [morpheus65535/bazarr#1518] opened 2021-08-28 11:44 UTC
**Describe the bug**
Since a few days regielive.ro provider throws a JSON Decode error when trying to search for a subtitle

**Software (please complete the following information):**
 - Bazarr: v0.9.7
 - Sonarr version 3.0.6.1265
 - OS: Linux

**Additional context**

28/08/2021 13:27:55|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): api.opensubtitles.org:80|
28/08/2021 13:27:55|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): api.regielive.ro:80|
28/08/2021 13:27:55|DEBUG   |urllib3.connectionpool          |http://api.opensubtitles.org:80 "POST /xml-rpc HTTP/1.1" 200 190|
28/08/2021 13:27:55|INFO    |subliminal_patch.providers.opensubtitles|No subtitles found|
28/08/2021 13:27:55|DEBUG   |urllib3.connectionpool          |http://api.regielive.ro:80 "POST /kodi/cauta.php HTTP/1.1" 301 162|
28/08/2021 13:27:55|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.regielive.ro:443|
28/08/2021 13:27:56|DEBUG   |urllib3.connectionpool          |https://api.regielive.ro:443 "GET /kodi/cauta.php HTTP/1.1" 404 None|
28/08/2021 13:27:56|ERROR   |subliminal_patch.core           |Unexpected error in provider 'regielive': Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/regielive.py", line 108, in list_subtitles    return self.query(video, self.language)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/regielive.py", line 92, in query    logger.info(response.json())  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 900, in json    return complexjson.loads(self.text, **kwargs)  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads    return _default_decoder.decode(s)  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)|Traceback (most recent call last):  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/regielive.py", line 108, in list_subtitles    return self.query(video, self.language)  File "/app/bazarr/bin/bazarr/../libs/subliminal_patch/providers/regielive.py", line 92, in query    logger.info(response.json())  File "/app/bazarr/bin/bazarr/../libs/requests/models.py", line 900, in json    return complexjson.loads(self.text, **kwargs)  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads    return _default_decoder.decode(s)  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode    obj, end = self.raw_decode(s, idx=_w(s, 0).end())  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode    raise JSONDecodeError("Expecting value", s, err.value) from Nonejson.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)|
28/08/2021 13:27:56|INFO    |root                            |Throttling regielive for 10 minutes, until 21/08/28 13:37, because of: JSONDecodeError. Exception info: 'Expecting value: line 2 column 1 (char 1)'|
28/08/2021 13:27:56|INFO    |socketio.server                 |emitting event "data" to all [/]|
28/08/2021 13:27:56|INFO    |subliminal_patch.core           |Discarding provider regielive|

**Comment by morpheus65535** [comment] 2021-08-28 13:01
Seems like the API URL reused from Kodi addons isn't working properly anymore and return a 404.

@GermanG are you able to take a look at it and see if there's something we can do about it? I'll try to contact the site admin by email.

**Comment by GermanG** [comment] 2021-08-29 08:33
Confirmed, the API as I knew it is not there anymore. The host api.regilive.ro is still there but it's just a "hello" result there and nothing else, my provider was based on the kodi plugin because I couldn't find any better documentation, just looked again and found my own gist as a top result in google. :/
Played a while with urls with no luck, I hope you have better luck contacting the site admin @morpheus65535 
The only alternative I can see is rewrite a scrap based one.

**Comment by morpheus65535** [comment] 2021-08-29 12:47
@GermanG thanks for your time, I'll keep you informed if I ever get any news from the site admin.

**Comment by alexandrucatalinene** [comment] 2022-12-15 10:11
I created a "wrapper" for the regielive API with local caching (in order to make it light on the regielive website). It's a drop in replacement, so if anyone wants to use it they can just replace the URL and it magically works.

I can post the URL if morpheus thinks it's okay.

**Comment by GermanG** [comment] 2022-12-15 11:26
Or you can create a PR with the new url, is it still regielive.ro?

**Comment by morpheus65535** [comment] 2022-12-15 15:01
@alexandrucatalinene of course I'll be happy to receive a PR for this. :-)

**Comment by morpheus65535** [comment] 2022-12-20 11:27
Should be fixed by @alexandrucatalinene PR. Feel free to test and confirm!

**Comment by morpheus65535** [comment] 2023-01-09 12:52
Fixed in development branch by #2032

**Closed by morpheus65535** 2023-01-09 12:52 UTC
Labels: awaiting feedback, fixed, broken provider
