### ISSUE TITLE
LegendasDivx: ParseResponseError. Exception info: 'Can not find the subtitle in the compressed file'

### ISSUE THREAD

**Issue by redglory** [morpheus65535/bazarr#962] opened 2020-05-04 12:46 UTC
**Describe the bug**
Bazarr is throttling LegendasDivx provider because of a ParseResponseError. Exception info: 'Can not find the subtitle in the compressed file'

**To Reproduce**
1. Go to 'Wanted'
2. Click on 'Download wanted subtitles'
3. If this exception is triggered, LegendasDivx is halted for 6 hours

**Expected behavior**
It doesn't make sense to halt a provider based on not finding a subtitle in the compressed file. I would expect to just point this on the log and move to the next subtitle.

**Screenshots**
[Imgur](https://imgur.com/ibROnem)

**Software (please complete the following information):**
Bazarr Version: 0.8.4.4
Sonarr Version: 3.0.3.784
Radarr Version: 0.2.0.1480
Operating System: Windows-10-10.0.18362-SP0
Python Version: 3.7.4

**Comment by morpheus65535** [comment] 2020-05-04 12:49
@GermanG would you take a look at this one please?

**Comment by guardiaopt** [comment] 2020-05-04 15:03
I don't think I can help this time, the problem is not on my part.

**Comment by morpheus65535** [comment] 2020-05-04 17:07
Raising an `APIThrottled` exception would be more consistent with the other providers.

**Comment by redglory** [comment] 2020-05-05 11:34
I'm improving legendasdivx.pt provider and will just log if can't return a subtitle with the request status_code and return

**Comment by morpheus65535** [comment] 2020-05-06 11:24
Should be fixed by your PR.

**Closed by morpheus65535** 2020-05-06 11:24 UTC
Labels: help wanted
