### ISSUE TITLE
Sync Subtitles not working since update

### ISSUE THREAD

**Issue by Olivier-Pickup** [morpheus65535/bazarr#2377] opened 2024-02-06 18:10 UTC
**Describe the bug**
when triing to sync audio with subtitle throught the Sync menu, it doesn't work after timeout.

**To Reproduce**
1. Go to a series with subtitles already downloaded with bazarr (or not)
2. Click on a subtitle then select "Sync"
3. bazarr is spawning a popup 
4. select default and click ok
5. bazar is spawning another popup bottom right
6. See a wierd error in popup

**Expected behavior**
Subtitle should have been synced with the audio of the episode.
**Screenshots**

**Software (please complete the following information):**
 - Bazarr: 1.4.1
 - Radarr version 5.2.6.8376
 - Sonarr version 3.0.10.1567
 - OS: Ubuntu 22.03 LTS

**Additional context**
Here is the error in the docker log:
`2024-02-06 18:35:31,661 - root                             (7f9bf0d23b38) :  ERROR (video_analyzer:271) - Video file "/media/NAS1/Series/True Detective/Season 4/True.Detective.S04E04.Part.4.WEBDL-1080p.h264.EAC3.Atmos.[EN+BG+CS+DA+ES+ET+FI+HR+HU+LT+LV+MK+NL+NB+PL+PT+RO+SK+SL+SR+SV]-NTb.mkv" cannot be found for analysis
`

The problem is wierd as i can access a subtitle or delete it or modify it and the subs has the same permission as the video file.

**Comment by morpheus65535** [comment] 2024-02-07 11:20
I've just tested to sync with the audio track of a mkv and it works as expected. I can't reproduce your issue. Check permissions again. This is more a support question than an a bug. I'll close this issue. You may come to Discord channel for support.

**Closed by morpheus65535** 2024-02-07 11:20 UTC
Labels: cannot reproduce

**Comment by Olivier-Pickup** [comment] 2024-02-08 08:09
have you tested with spaces in path ?

**Comment by morpheus65535** [comment] 2024-02-08 11:17
> have you tested with spaces in path ?

Yes: spaces, accented characters, brackets, etc.

**Comment by ftruzzi** [comment] 2024-03-12 19:30
Hi @morpheus65535, and thank you for your work!

I've been having the same issue with the sync. The problem seems to be that, during sync, bazarr is looking for my movie files at `/media/movies/my_movie.mkv` but the correct path is `/movies/my_movie.mkv` as in the rest of the app. The `/media` prefix exists in my *arr apps, but I have configured path mappings for both Sonarr and Radarr.

<img width="1527" alt="image" src="https://github.com/morpheus65535/bazarr/assets/461133/187c2ba8-4af4-40c1-9624-7aaff5b9bd49">

<img width="1355" alt="image" src="https://github.com/morpheus65535/bazarr/assets/461133/a7cfb390-2933-43d7-8374-ebf5f718fbf7">


<img width="1444" alt="image" src="https://github.com/morpheus65535/bazarr/assets/461133/693fbd88-1343-4054-be4f-401d90e6dcea">
