### ISSUE TITLE
Traceback cleanup for 'nonexistant' entries

### ISSUE THREAD

**Issue by systemcrash** [morpheus65535/bazarr#1606] opened 2021-11-06 16:05 UTC
**Describe the bug**
```
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6884, in get
    return clone.execute(database)[0]
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 4275, in __getitem__
    return self.row_cache[item]
IndexError: list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/bazarr/bin/bazarr/list_subtitles.py", line 130, in store_subtitles_movie
    item = TableMovies.select(TableMovies.movie_file_id, TableMovies.file_size)\\
  File "/app/bazarr/bin/bazarr/../libs/peewee.py", line 6887, in get
    raise self.model.DoesNotExist(\'%s instance matching query does \'
database.TableMoviesDoesNotExist: <Model: TableMovies> instance matching query does not exist:
SQL: SELECT "t1"."movie_file_id", "t1"."file_size" FROM "table_movies" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?
Params: [\'/data/Films/The.XYZ/The.XYZ.sample.mkv\', 1, 0]
```

**To Reproduce**
1. Have 'sample' file in same folder as an entry...? 

**Expected behavior**
Gracefully handle traceback - perhaps with a `try... except` block.

**Software (please complete the following information):**
Bazarr Version
1.0.0
Sonarr Version
3.0.6.1342
Radarr Version
3.2.2.5080
Operating System
Linux-4.4.180+-x86_64-with
Python Version
3.9.5
Bazarr Directory
/app/bazarr/bin
Bazarr Config Directory
/config

**Comment by halali** [comment] 2021-11-07 05:29
Issue is that your db is probably corrupted, you have misaing movie table in db. This is nothing we can catch. Its fatal error

**Comment by systemcrash** [comment] 2021-11-07 14:01
DB just created - perhaps function chain could start with
* Does DB exist
* Does DB have entries
* ...

**Comment by systemcrash** [comment] 2021-11-07 14:24
Perhaps something like:
```python
    def __getitem__(self, item):
        if isinstance(item, slice):
            stop = item.stop
            if stop is None or stop < 0:
                self.fill_cache()
            else:
                self.fill_cache(stop)
            try:
                return self.row_cache[item]
            except IndexError:
                return None
        elif isinstance(item, int):
            self.fill_cache(item if item > 0 else 0)
            try:
                return self.row_cache[item]
            except IndexError:
                return None
        else:
            raise ValueError('CursorWrapper only supports integer and slice '
                             'indexes.')
```

**Comment by morpheus65535** [comment] 2021-11-07 15:31
This IndexError is just the consequence of the database row related to this movie not found in table_movies. Did you changed path mapping recently?

**Comment by systemcrash** [comment] 2021-11-07 16:01
I understand the reason that the trace back occurs. But its root cause
seems to be unclear.

I do not think so. I had newly set it up and left it running overnight.

**Comment by morpheus65535** [comment] 2021-11-08 20:30
When Bazarr insert or update a movie row in the database, the next step is to run the store_subtitles function to index existing subtitles and calculate the missing ones. In the store_subtitles function, we try to select the proper row to update (the one for the movie added or updated) by using the path as a unique reference. In that case, it can't find the row that was just added or updated.

Investigating with the non-hidded params would probably help to determine the root cause.

**Comment by systemcrash** [comment] 2021-11-09 16:16
Is there something I can do/provide at this point? Or would a simple try/except fix the problem anyway?

**Comment by morpheus65535** [comment] 2021-11-09 16:41
I may add a try...except but you'll end-up with an episode/movie without proper indexing of subtitles. I'm not sure it's better but I can add it.

**Comment by systemcrash** [comment] 2021-11-09 17:52
If the traceback occurs because the code thinks the file doesn't exist in the first place, then the try/except prevents the traceback, and execution continues gracefully. :shrug:

**Comment by morpheus65535** [comment] 2021-11-09 18:34
Yes, you're not wrong. I'll take a look.

**Comment by morpheus65535** [comment] 2021-11-09 18:43
In fact this exception/trace shouldn't get raised at all since the peewee query is already embedded in a catch all try...except. It should simply log the exception and pass: https://github.com/morpheus65535/bazarr/blob/master/bazarr/list_subtitles.py#L159-L162

**Comment by systemcrash** [comment] 2021-11-09 20:02
I think the problem is the overly broad except. If you give specificity to
a except more than just 'except:' then it's also easier to understand what
the except code block is intended for. Altho that's just style.

And an except which occurs in a subroutine does not get captured by the
calling functions try.

**Comment by morpheus65535** [comment] 2021-11-10 04:22
I've just pushed a fix to dev branch. It will be included in upcoming beta. Can you test and confirm please?

**Comment by morpheus65535** [comment] 2021-11-21 14:51
No news, good news.

**Closed by morpheus65535** 2021-11-21 14:51 UTC
Labels: bug, awaiting feedback, fixed
