### ISSUE TITLE
Most SubDL subtitles don't seem to be listed in the manual movie search

### ISSUE THREAD

**Issue by hummingbirdy2** [morpheus65535/bazarr#2725] opened 2024-10-17 14:45 UTC
**Describe the bug**
Even if the subdl API returns available subtitles, they will not be listed in the manual search results.

**Expected behavior**
Available subtitles should be listed.

**Software (please complete the following information):**
 - Bazarr: 1.4.5

**Additional context**
In almost all my tests. No SubDL subtitles are listed in a manual movie search. Although, the API returns a number of subtitles. And that in the bazarr logs, we find the mention `Query returned X subtitles`.
The only case where I've had a subtitle listed, and that was for American History X with French subtitles.
After looking at the API response, I found that of the 11 subtitles listed, the only one displayed was the one with the key `episode` non-null.

_Listed subtitle item:_
```json
{
  "release_name": "658.837.504",
  "name": "SUBDL.com::american.history.x114706.zip",
  "lang": "french",
  "author": "Thz",
  "url": "/subtitle/583867-114706.zip",
  "subtitlePage": "/s/info/MrwXjU1oZ2",
  "season": 0,
  "episode": 4,  // <- non-null
  "language": "FR",
  "hi": true,
  "comment": "658.837.504",
  "releases": [
    "658.837.504"
  ],
  "episode_from": 4,  // <- non-null
  "episode_end": 4,
  "full_season": false
}
```

_Not listed subtitle item:_
```json
{
  "release_name": "American.History.X.1998.720p.BluRay.DTS.x264-HiDt.VSS.SB3",
  "name": "SUBDL.com::_american-history-x_french_573944.zip",
  "lang": "french",
  "author": "Esaus",
  "url": "/subtitle/583870-573944.zip",
  "subtitlePage": "/s/info/V40SewVlT3",
  "season": 0,
  "episode": null,  // <- null
  "language": "FR",
  "hi": true,
  "comment": "",
  "releases": [
    "American.History.X.1998.720p.BluRay.DTS.x264-HiDt.VSS.SB3"
  ],
  "episode_from": null,  // <- null
  "episode_end": 0,
  "full_season": false
}
```
At first glance, bazarr doesn't seem to list subtitles if the `episode` key is null. And this seems to be confirmed by my other searches: subtitles for films with this null key are never listed.
I didn't check if this behaviour is the same with automatic search.

**Comment by VXsz** [comment] 2024-10-21 01:47
Yes, this issue seems has been there for like 2 months by now, both on my windows, and a friend's pretty fresh windows install. The automatic search has the same issue and it won't grab subs automatically (the api returns a small set of subs, but it filters all of them away like explained by hummingbirdy2). Weirdly enough it sometimes does grab a subtitle.

**Comment by morpheus65535** [comment] 2024-10-23 22:37
@hummingbirdy2 it should eb fixed in upcoming beta. We shouldn't compare `episode_from` and `episode_end` for movies anyway.

@VXsz We do not support season packs for series so it could be the reason why. The other reason may be that they provide garbage in their API from time to time. They were suppose to properly reindex their stuff but they never confirmed it was done.

**Comment by morpheus65535** [comment] 2024-11-12 01:33
@hummingbirdy2 can I close this issue? Is it fixed?

**Closed as completed** 2024-12-01 13:37 UTC
Labels: bug, awaiting feedback, fixed
