### ISSUE TITLE
Wrong file name is being used for search

### ISSUE THREAD

**Issue by zehDonut** [morpheus65535/bazarr#2609] opened 2024-08-06 16:13 UTC
**Describe the bug**
Bazarr uses old file names to search for subtitles.
Bazarr displays the correct file name, according to what is set in radarr/sonarr and on disk, but uses an old filename (before automatic rename through radarr/sonarr) for searching subtitles.
Log file is attached.
[bazarr(2).log](https://github.com/user-attachments/files/16512953/bazarr.2.log)

**To Reproduce**
1. Rename a file on disk, or in radarr/sonarr
2. Run task "Sync with radarr/sonarr"
3. Manual search for subtitles
4. See pre-rename filename is being used for search

Example:
File name on disk: 
<img width="387" alt="image" src="https://github.com/user-attachments/assets/a9bc83d6-0eb5-4c35-81e0-8f4fdb2a09d1">
File name in bazarr:
<img width="456" alt="image" src="https://github.com/user-attachments/assets/bf85103e-33a2-4860-b960-8fe06d23bec7">
File name in (manual) search:
<img width="474" alt="image" src="https://github.com/user-attachments/assets/3ff21a65-8497-40e3-82fd-0370f3102632">

**Expected behavior**
Bazarr uses the correct file name for searching

**Software (please complete the following information):**
 - Bazarr:  1.4.3
 - Radarr version: 5.8.3.8933
 - Sonarr version: 4.0.8.1874
 - OS: Ubuntu 22.04 LTS, all *arr running from LSIO docker images

**Comment by morpheus65535** [comment] 2024-08-06 17:21
This os the expected behavior. Bazarr search using the scene name from Sonarr and Radarr to benefit from the maximum metadata while searching. We refine using all the data we keep in database.

Imagine if we were searching using the filename only for a movie called movie.mkv... how could we determine if the subtitles match properly or not?

I'll close this as a question since it's not an issue.

**Closed by morpheus65535** 2024-08-06 17:21 UTC
