### ISSUE TITLE
Opening Bazarr in browser renders white page and throws errors in the console.

### ISSUE THREAD

**Issue by 3therios** [morpheus65535/bazarr#1850] opened 2022-05-25 08:10 UTC
**Describe the bug**
Accessing Bazarr in browser returns a blank white page with errors about MIME type being text/plain.

**To Reproduce**
1. Install Bazarr via installer
2. Bazarr should be started automatically via service, if not start it.
3. Go to localhost:6767 in your browser (I'm using Brave / Chrome)

**Expected behavior**
The Bazarr application and UI appears correctly and I can use Bazarr

**Screenshots**
![image](https://user-images.githubusercontent.com/7747232/170212446-ee21f73c-231f-4ff0-af75-d14d57fc155d.png)

**Software (please complete the following information):**
 - Bazarr: v1.0.4 (Latest at the time of writing this issue)
 - Radarr version v4.1.0.6175
 - Sonarr version v3.0.8.1507
 - OS: Windows 10

**Additional context**
Have always had an issue where Bazarr resets randomly so I would be periodically forced to copy back in my config file.
Now even after a fresh install where I uninstalled, deleted `%programdata%/Bazarr` I still am unable to even render the site.
I have tested it in Chrome and Brave. In addition to that I cleared all local site and cache data yet no success.

Help or a fix would be appreciated.

**Comment by morpheus65535** [comment] 2022-05-25 10:16
Duplicate of #1822 pinned issue.

**Closed by morpheus65535** 2022-05-25 10:16 UTC
