### ISSUE TITLE
Job `Update all Episode Subtitles from disk` and `Update all Movie Subtitles from disk` do not rescan files

### ISSUE THREAD

**Issue by salomj** [morpheus65535/bazarr#1502] opened 2021-08-12 23:44 UTC
**Describe the bug**
When I run the jobs `Update all Episode Subtitles from disk`  or `Update all Movie Subtitles from disk`, it does not pick up the new subtitles added to the .mkv files.

If I run `Scan Disk` under the Series or the Movie individually, it works fine, just not the batch job. When you have 100s of Movies/Series, this is a really tedious workaround.

**To Reproduce**
1. Create an mkv file without subtitles
2. Get Bazarr to update
3. Add a subtitle stream to the mkv file
4. Run one of the above jobs

**Expected behavior**
It should scan the .mkv files to see if subtitle streams have been added

**Screenshots**

**Software (please complete the following information):**
 - Bazarr: v0.9.6
 - Radarr version: v3.0.6.1265
 - Sonarr version v3.2.2.5080
 - OS: Ubuntu 20.04.2 LTS [Linux-5.4.0-1041-raspi-aarch64-with] 
 - Docker Image `ghcr.io/linuxserver/bazarr:arm64v8-latest`

**Additional context**
I have jobs which pulls subtitles out of movie files when the subtitle is not one that plex likes (Eg. anything not subrip) and it also merges acceptable subtitles into the movie file if it is ones that plex likes. Bazarr doesn't like either of these stages as it seems that Bazarr is never rescanning the movie files. 

This also includes when update the movie file via any means, including deleting and re-importing the series via Sonarr/Radarr. Bazarr never seems to rescan the file.

**Comment by morpheus65535** [comment] 2021-08-13 11:44
We cache the video properties (including the embedded subtitles) to reduce the disk I/O. The only way to refresh that cache is to use the scan disk button or, make sure Sonarr or Radarr get notified f the file changes and update accordingly. If Sonarr/Radarr file size if file id changes, the cache is refreshed.

**Comment by salomj** [comment] 2021-08-13 15:53
Sonarr and Radarr do get updated. NOTE: I have straight up deleted the files on Sonarr and Radarr and reimported them, and Bazarr still uses cached versions of the file.

**Comment by morpheus65535** [comment] 2021-08-13 16:23
Ok I'm out of town but I'll look into it next week.

**Comment by morpheus65535** [comment] 2021-08-17 13:21
I've just tested with Sonarr and if you let Sonarr download and upgrade the video file, the cache is properly updated in Bazarr DB. However, if you modify the content of the video file on disk without changing the filename, Sonarr doesn't catch the change. The result is that Sonarr doesn't update the file size nor it create a new file id. If Sonarr doesn't catch the change, there's no way Bazarr can be informed of the change.

**Comment by morpheus65535** [comment] 2021-08-17 13:43
I've spoke with the guys from Sonarr/Radarr and this is the "expected" behavior. Radarr devs told me that they were thinky about checking file size for sometime. We'll see if it happen.

May I close this issue?

**Comment by salomj** [comment] 2021-08-17 13:43
How is Bazarr checking for file changes?

**Comment by morpheus65535** [comment] 2021-08-17 13:44
Bazarr rely on Sonarr/Radarr metadata provided by their respective API.

**Comment by salomj** [comment] 2021-08-17 13:46
> I've spoke with the guys from Sonarr/Radarr and this is the "expected" behavior. Radarr devs told me that they were thinking about checking file size for sometime. We'll see if it happen.
> 
> May I close this issue?

This is still an issue if I completely remove the file from Sonarr and then readd the file immediately, so even so they still have a bug when it comes to deleting and readding to get the file to refresh.

> Bazarr rely on Sonarr/Radarr metadata provided by their respective API.

Hmm... You don't ask the file system if the file has been updated?

**Comment by salomj** [comment] 2021-08-17 13:48
> May I close this issue?

You can if you want to, but without a resolve for this issue either here or somewhere else, I will stop using bazarr as this issue is something I cannot live without.

**Comment by morpheus65535** [comment] 2021-08-17 13:50
The issue is on Sonarr/Radarr side. Nothing I can fix on my side. I've tested and if I remove the file, rescan in Sonarr, add the file back, scan again: everything work as expected.

No I don't listen to filesystem change. That's the expected behavior by design.

I'm sorry to ear that you'll stop to use Bazarr because of an issue on Sonarr/Radarr side but, as I said, there's nothing to be done on our side.

**Closed by morpheus65535** 2021-08-17 13:50 UTC
Labels: question

**Comment by salomj** [comment] 2021-08-17 14:16
> I'm sorry to ear that you'll stop to use Bazarr because of an issue on Sonarr/Radarr side but, as I said, there's nothing to be done on our side.

Unfortunately, this issue is felt only in Bazarr, as it causes Bazarr to pull subtitles for videos which already have subtitles and to not pull subtitles for videos which do not, and it will do this forever without human intervention. The effects on Sonarr or Radarr being out of sync are minor in comparison to what is happening here.

I added a feature request to ease the pain of this issue.
https://bazarr.featureupvote.com/suggestions/203421/add-a-scan-all-to-the-movie-and-series-sections

**Comment by salomj** [comment] 2021-08-17 14:19
Might I also suggest removing the `from Disk` in the job title, as it doesn't do anything `from Disk` as implied from the title.

**Comment by morpheus65535** [comment] 2021-08-17 14:21
Yes it index external subtitles properly by scanning disk. I will think about having an option to disable the cache during daily scan from disk. Would that be helpful?

**Comment by salomj** [comment] 2021-08-17 14:45
Yes, if that means it will rescan the files, then it would most definitely be helpful.

**Comment by morpheus65535** [comment] 2021-08-17 14:51
Yes it will prevent using the cached ffprobe result that include embedded subtitles when the daily disk scan run. By default, it will be disabled so the cache will be used but at least you'll be able to enable this settings and Bazarr will be aware of the changes to the embedded subtitles.

**Comment by morpheus65535** [comment] 2021-08-17 18:36
The new settings is added to Settings-->Scheduler to ignore ffprobe cache. It will be available in upcoming 0.9.8-beta.3.

**Comment by salomj** [comment] 2021-08-17 19:57
> The new settings is added to Settings-->Scheduler to ignore ffprobe cache. It will be available in upcoming 0.9.8-beta.3.

Thank you
