### ISSUE TITLE
Addic7ed does not give any result

### ISSUE THREAD

**Issue by EmaldIsBack** [morpheus65535/bazarr#844] opened 2020-02-29 11:21 UTC
hello!
i am running a vps
i set up bazarr behind a nginx reverse proxy
opensubtitles works flawlessly, but not addic7ed (with anti-captcha.com and a vip addic7ed account)
here are the logs of the search for an episode
https://pastebin.com/Yc1wW1WZ
thank you very much for this awesome tool

**Comment by morpheus65535** [comment] 2020-02-29 22:07
From the log:

`HTTPSConnectionPool(host='www.addic7ed.com', port=443): Max retries exceeded with url: /login.php (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa339ea0090>, 'Connection to www.addic7ed.com timed out. (connect timeout=10)')), retrying in 5 seconds...`

You have something blocking your request to addic7ed website. It's unrelated to your reverse proxy. Maybe addic7ed is blocking request from your VPS provider or your provider is doing it. Who knows.

One thing for sure, it's not an issue with Bazarr so I'll close this one.

**Closed by morpheus65535** 2020-02-29 22:07 UTC
