### ISSUE TITLE
Posibility to add a second Radarr server

### ISSUE THREAD

**Issue by delcara** [morpheus65535/bazarr#418] opened 2019-04-29 18:04 UTC
I cannot add another radarr server. I've 2 radarr servers, one for my 4K movies and one for 1080P movies. This because transcoding 4K HDR 10 bit to 1080P for other devices in the house is not ideal. So i've seperated my media for this. In plex i have 2 seperated libraries for this, when 

I would like an option to add another radarr server in bazarr. That would make bazarr perfect for me!

**Comment by morpheus65535** [comment] 2019-04-29 18:56
Duplicate of #404.

**Closed by morpheus65535** 2019-04-29 18:56 UTC
Labels: duplicate, wontfix
