### ISSUE TITLE
Download failed with BetaSeries after manual search

### ISSUE THREAD

**Issue by Nakda** [morpheus65535/bazarr#1423] opened 2021-05-31 16:03 UTC
**Describe the bug**
After performing a manual search, and clicked on the download button associated to one of the available items, the UI displays a tickmark (success icon) whereas the download failed (no file on disk, still appears as missing from Bazarr UI).

**To Reproduce**
1. Go to a Serie dedicated page
2. Click on Start Search for a specific episode
3. Download an item from the result page

**Expected behavior**
The subtitle file should have been downloaded properly, or the UI should have mentioned a failed attempt.

**Screenshots**
![image](https://user-images.githubusercontent.com/25755503/120218476-4f035c00-c229-11eb-9077-f49365c5d775.png)

**Software (please complete the following information):**
- Bazarr: v0.9.5
- Sonarr version 3.0.6.1196
- OS: Rasperry Pi OS Lite (Linux raspberrypi 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux)

**Additional context**
- Log file states the file has been downloaded, but right after it says:
`No valid Subtitles file found for this file`
- Log states:
` 'BetaSeriesProvider' object has no attribute 'video'`

**Log file**
Debug mode enabled, and cleaned before performing the download attempt
[bazarr_download.log](https://github.com/morpheus65535/bazarr/files/6571333/bazarr_download.log)

**Comment by morpheus65535** [comment] 2021-06-07 16:42
Should be fixed in upcoming 0.9.6-beta.20. Can you test and confirm please?

**Comment by Nakda** [comment] 2021-06-09 09:03
Sorry for the late reply. Can I switch my Bazarr instance back and forth between dev and master branches or should I test with another instance?

**Comment by morpheus65535** [comment] 2021-06-09 10:40
You can switch to 0.9.6-beta.21 but I would wait for 0.9.6 final to move back to master.

**Comment by Nakda** [comment] 2021-06-09 10:45
Just tested. The subtitle file didn't download, but not because of the same error, so the original bug seems to be fixed. It now throws an error for `FormatAutodetectionError: No suitable formats`, probably because it's a `.zip` archive.

Here are the logs, if necessary: 
[bazarr.log](https://github.com/morpheus65535/bazarr/files/6623133/bazarr.log)

**Comment by morpheus65535** [comment] 2021-06-09 11:15
Of course that's another issue. The issue isn't with zip file but it looks like there's something wrong with the subtitles format. Try another one maybe?

**Closed** 2021-06-09 11:59 UTC
Labels: awaiting feedback, fixed
