### ISSUE TITLE
Bad handling of passwords containing only numbers

### ISSUE THREAD

**Issue by tmortagne** [morpheus65535/bazarr#2322] opened 2023-12-11 19:35 UTC
**Describe the bug**

I'm trying to configure OpenSubtitle.com or Addicted with a password containing only numbers.

When saving I'm getting the following error:

```
406

opensubtitlescom.password must is_type_of <class 'str'> but it is 30082008
```

Feels like it's parsing the content of that field based on its content instead of forcing it to be a string by definition.

Note that I think it's a regression since I'm pretty sure I configured those without any problem in the past and I had the surprise to discovered that the password was lost (but I have not idea since when exactly).

The easiest workaround is of course to change your password to also contain other characters (which is not a bad idea anyway).

**Software (please complete the following information):**
 - Bazarr: 1.4.0
 - OS: Linux-5.15.0-91-generic-x86_64-with-glibc2.35

**Comment by morpheus65535** [comment] 2023-12-11 21:19
Yes it's been caused by a breaking change in 1.4.0. Already fixed in nightly. Thanks for reporting!

**Closed by morpheus65535** 2023-12-11 21:19 UTC

**Comment by tmortagne** [comment] 2023-12-12 08:35
OK, thanks @morpheus65535, sorry if I missed a related issue.
