### ISSUE TITLE
Syntax error on dev branch

### ISSUE THREAD

**Issue by raidenlal** [morpheus65535/bazarr#854] opened 2020-03-08 09:26 UTC
**Describe the bug**
Dev branch LSIO image throws this exception:
Traceback (most recent call last):
  File "/app/bazarr/bazarr/main.py", line 52, in <module>
    from get_providers import get_providers, get_providers_auth, list_throttled_providers
  File "/app/bazarr/bazarr/get_providers.py", line 5, in <module>
    import subliminal_patch
  File "/app/bazarr/bazarr/../libs/subliminal_patch/__init__.py", line 7, in <module>
    from .subtitle import Subtitle, guess_matches
  File "/app/bazarr/bazarr/../libs/subliminal_patch/subtitle.py", line 299
    fragment = fragment.replace(ur"\h", u" ")
SyntaxError: invalid syntax
**To Reproduce**
Try to start lsio dev container in docker.

**Software (please complete the following information):**
 Latest linuxserver.io development branch image

commit d5feea0b097efe2f7813d9f0fbae4c7542603134 is the culprit?

**Comment by morpheus65535** [comment] 2020-03-08 13:53
Thanks for reporting! I've pushed a fix that should be included in next image somewhere in the next 2 hours.

**Comment by raidenlal** [comment] 2020-03-08 15:40
Neat, thank you. However the build failed for some reason: https://ci.linuxserver.io/job/Docker-Pipeline-Builders/job/docker-bazarr/job/development/658/console

I assume this is LSIO issue?

**Comment by morpheus65535** [comment] 2020-03-08 15:57
That's also my assumption. I've asked on their Discord channel and waiting for feedback.

**Comment by raidenlal** [comment] 2020-03-08 19:02
Fixed. Could not find root cause. If you have any info regarding what was wrong it would be nice to know about that. Thank you.

**Comment by morpheus65535** [comment] 2020-03-08 19:26
The issue was caused by some incompatible Python 2.x only introduced in a commit last night.

**Closed by morpheus65535** 2020-03-08 19:26 UTC
