### ISSUE TITLE
Bazarr fails to fetch episodes

### ISSUE THREAD

**Issue by costaht** [morpheus65535/bazarr#1425] opened 2021-06-02 23:12 UTC
**Describe the bug**
Bazarr is failing to immediately fetch episodes from Sonarr when a new tv show is added. The TV Show home will be shown as below **until** the next *Episode sync task* runs

**To Reproduce**
1. Add to Sonnar a new TV Show
2. Download an episode or season
3. Bazarr will create a home for that TV Show but no episodes will be loaded
4. Manually sync the episodes with Sonarr
5. Go to the TV Show home page and the recently added episodes will be there.

**Expected behavior**
Not only the home page has to be created, but the episodes also have to be synced once a new file is added to Sonarr.

**Screenshots**
![image](https://user-images.githubusercontent.com/50637431/120562754-0be5ec00-c3d5-11eb-9a73-0555817f4b72.png)

**Software (please complete the following information):**
**Bazarr Version** 0.9.6-beta.15
**Sonarr Version** 3.0.6.1196
**Radarr Version** 3.2.1.5070
**Operating System** Linux-4.18.0-305.0.1.el8.x86_64-x86_64-with-glibc2.2.5

**Additional context**
Once a new file is added to Sonarr, that's what I see on my logs:

```
02/06/2021 18:34:48|DEBUG   |peewee.sqliteq                  |received query UPDATE "table_shows" SET "tvdbId" = ?, "alternateTitles" = ?, "audio_language" = ?, "fanart" = ?, "imdbId" = ?, "overview" = ?, "path" = ?, "poster" = ?, "seriesType" = ?, "sonarrSeriesId" = ?, "sortTitle" = ?, "tags" = ?, "title" = ?, "year" = ? WHERE ("table_shows"."sonarrSeriesId" = ?)|
02/06/2021 18:34:48|DEBUG   |peewee                          |('UPDATE "table_shows" SET "tvdbId" = ?, "alternateTitles" = ?, "audio_language" = ?, "fanart" = ?, "imdbId" = ?, "overview" = ?, "path" = ?, "poster" = ?, "seriesType" = ?, "sonarrSeriesId" = ?, "sortTitle" = ?, "tags" = ?, "title" = ?, "year" = ? WHERE ("table_shows"."sonarrSeriesId" = ?)', [71663, "['Die Simpsons', 'Les Simpson', 'Los Simpson', 'Los Simpsons', 'The Simpsons QC']", "['English']", '/MediaCover/133/fanart.jpg', 'tt0096697', 'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family; Homer, Marge, Bart, Lisa and Maggie, as well as a virtual cast of thousands. Since the beginning, the series has been a pop culture icon, attracting hundreds of celebrities to guest star. The show has also made name for itself in its fearless satirical take on politics, media and American life in general.', '/mnt/hometheater/TV-Shows/The Simpsons', '/MediaCover/133/poster-250.jpg', 'standard', 133, 'simpsons', '[]', 'The Simpsons', '1989', 133])|
02/06/2021 18:34:48|INFO    |socketio.server                 |emitting event "data" to all [/]|
02/06/2021 18:34:48|DEBUG   |root                            |BAZARR updated this series into the database:/mnt/hometheater/TV-Shows/The Simpsons|
02/06/2021 18:34:48|DEBUG   |root                            |BAZARR syncing this specific episode from Sonarr: 11104|
02/06/2021 18:34:48|DEBUG   |peewee                          |('SELECT "t1"."path" FROM "table_episodes" AS "t1" WHERE ("t1"."sonarrEpisodeId" = ?) LIMIT ? OFFSET ?', [11104, 1, 0])|
02/06/2021 18:34:48|DEBUG   |root                            |BAZARR an exception occurred while parsing SignalR feed: TableEpisodesDoesNotExist('<Model: TableEpisodes> instance matching query does not exist:\nSQL: SELECT "t1"."path" FROM "table_episodes" AS "t1" WHERE ("t1"."sonarrEpisodeId" = ?) LIMIT ? OFFSET ?\nParams: [11104, 1, 0]')|
02/06/2021 18:34:49|DEBUG   |peewee                          |('SELECT COUNT(1) FROM (SELECT 1 FROM "table_shows" AS "t1") AS "_wrapped"', [])|
02/06/2021 18:34:49|DEBUG   |peewee                          |('SELECT "t1"."tvdbId", "t1"."alternateTitles", "t1"."audio_language", "t1"."fanart", "t1"."imdbId", "t1"."overview", "t1"."path", "t1"."poster", "t1"."profileId", "t1"."seriesType", "t1"."sonarrSeriesId", "t1"."sortTitle", "t1"."tags", "t1"."title", "t1"."year" FROM "table_shows" AS "t1" WHERE ("t1"."sonarrSeriesId" IN (?)) ORDER BY "t1"."sortTitle"', [133])|
```

**Comment by morpheus65535** [comment] 2021-06-03 02:33
Please test beta.17 and confirm if it's fixed.

**Comment by Magikarplvl4** [comment] 2021-06-03 09:04
Hi @morpheus65535 I checked the last beta, looking much better now. I see that the added episodes in sonarr are synced up with bazarr and it triggers a search. however, is it normal behavior that only the added episodes (and seasons) are synced with Bazarr?
For example, I added the tv show white collar with 6 seasons. I monitored just only season one. In Bazarr it shows only season 1

**Comment by morpheus65535** [comment] 2021-06-03 10:45
All episode should get synced whatever the status they are in.

**Comment by costaht** [comment] 2021-06-04 03:00
Ok, I just tested and I've got the same results as @Magikarplvl4. I also did the same test as [eff1gy](https://discordapp.com/channels/382221826564030464/540191312964485120/849854358001811476) and different from him, removing the show from Sonarr and adding it back didn't trigger any other bug.
Though, based on what you last said, the behavior below is not what you expect, right? 
Syncing TV Shows and Episodes didn't change anything.

![lu](https://user-images.githubusercontent.com/50637431/120738907-a110df80-c4be-11eb-92d6-2f7b6523d7cd.png)


![Screenshot from 2021-06-03 22-44-57](https://user-images.githubusercontent.com/50637431/120738908-a1a97600-c4be-11eb-98b2-9583ff40e7ae.png)

**Comment by batuhankrmn** [comment] 2021-06-04 03:04
I am on v0.9.6-beta.17 and can confirm that It's working great for me. Bazarr doing add and sync episodes directly when Sonarr finishes the downloading.

**Comment by morpheus65535** [comment] 2021-06-04 03:19
> Though, based on what you last said, the behavior below is not what you expect, right?
> Syncing TV Shows and Episodes didn't change anything.

Of course it's not expected. All episodes should sync, not just the monitored. There's no filtering on imported episodes other than having files on disk. Do they?

I don't understand why I'm not able to reproduce this issue. Can you provide a debug log while adding the series back in Sonarr?

**Comment by costaht** [comment] 2021-06-04 03:58
> There's no filtering on imported episodes other than having files on disk

No filters or tags, unless I'm overlooking something. The episodes available on Bazarr coincide with the number of files available on Sonarr. This is how the show looks like on Sonarr (everything being monitored):

![Screenshot from 2021-06-03 23-45-37](https://user-images.githubusercontent.com/50637431/120742906-e258bd80-c4c5-11eb-9d6a-cf0400cf319a.png)

![Screenshot from 2021-06-03 23-45-57](https://user-images.githubusercontent.com/50637431/120742912-e7b60800-c4c5-11eb-8e9e-44e307664d0e.png)

Here are the logs that reflect the steps below:

1. Add "The Good Doctor" to Sonarr
2. Add one episode to that Show
3. Bazarr immediately syncs with Sonarr and create the show home with a single episode
4. Bazarr immediately triggers search and find a pt-br sub
5. I delete the show from Sonarr keeping the file
6. Bazarr immediately removes the show's page
6. I add "The Good Doctor" to Sonarr again
7. Sonarr detects the episode
8. Bazarr immediately syncs with Sonarr and create the show home with a single episode again 

https://paste.centos.org/view/8fbaf009

**Comment by morpheus65535** [comment] 2021-06-04 04:01
@costaht ok so it's working as expected? I was under the impression it wasn't the case. Am I right?

**Comment by costaht** [comment] 2021-06-04 04:09
I mean, it looks fine to me. Maybe we misunderstood when you said:

>All episode should get synced whatever the status they are in.

So, as long as the file is available, Bazarr will grab it and ignore the episodes with no files available, Correct?

Ex:
![Screenshot from 2021-06-04 00-07-58](https://user-images.githubusercontent.com/50637431/120744430-f651ee80-c4c8-11eb-800c-c6e1c508831d.png)

**Comment by morpheus65535** [comment] 2021-06-04 11:35
> I mean, it looks fine to me. Maybe we misunderstood when you said:
> 
> > All episode should get synced whatever the status they are in.
> 
> So, as long as the file is available, Bazarr will grab it and ignore the episodes with no files available, Correct?
> 
> Ex:
> ![Screenshot from 2021-06-04 00-07-58](https://user-images.githubusercontent.com/50637431/120744430-f651ee80-c4c8-11eb-800c-c6e1c508831d.png)

Exactly and, TBH, it's nothing new. It's been like this since the initial version in September 2017: https://github.com/morpheus65535/bazarr/blob/a9187e033e4d559c4de7b4c12781fa7eb10d2302/get_episodes.py#L28

So I guess I can close this issue?

**Closed** 2021-06-04 13:55 UTC
Labels: awaiting feedback, fixed
