### ISSUE TITLE
Stuck in a starting, existed loop

### ISSUE THREAD

**Issue by nodiaque** [morpheus65535/bazarr#2098] opened 2023-03-18 00:23 UTC
**Describe the bug**
When I start bazarr, it keep restarting itself. Log show it's starting then exited

**To Reproduce**
Start the container and wait

**Expected behavior**
Container to start and stay started

**Screenshots**
![image](https://user-images.githubusercontent.com/324425/226072393-a6265831-5dad-457c-a4f6-009f1d490041.png)

**Software (please complete the following information):**
 - Bazarr: 1.2.0
 - Radarr 4.3.2.6857
 - Sonarr 3.0.10.1567
 - OS: Unraid 6.11.5

**Additional context**
Debug Log File [Attached]
[bazarr.log](https://github.com/morpheus65535/bazarr/files/11007066/bazarr.log)

**Comment by morpheus65535** [comment] 2023-03-18 01:32
Could be an issue with mediainfo binary. Are you running LSIO docker image?

**Comment by nodiaque** [comment] 2023-03-18 01:34
I'm running hotio docker.

It was running fine until I restarted the container. I forgot to reboot it when I added the root folder for reversed proxy. Before it was working, although I had many unable to analyze but it was working.

**Comment by morpheus65535** [comment] 2023-03-18 01:37
Ok so you've changed base url and once you've restarted it running into a loop... I'm pretty sure it's unrelated. Are you able to restore a backup or reconfigure from scratch to identify a specific root cause?

**Comment by nodiaque** [comment] 2023-03-18 01:38
I've just installed it. I could redo everything, I simply followed trash guide on install and configure, added embed and 2 other providers and that's about it

**Comment by morpheus65535** [comment] 2023-03-18 01:40
and you changed ffprobe to mediainfo?

**Comment by nodiaque** [comment] 2023-03-18 01:41
Yup, log showed it was trying with media info. I restarted about 3 hours after changing the config. I could try to put ffprobe again

**Comment by morpheus65535** [comment] 2023-03-18 01:43
Please. Just to be sure we narrow it to that.

**Comment by nodiaque** [comment] 2023-03-18 01:43
Ok, manage to switch to ffprobe and it's not closing again. So it's an issue with medianinfo

**Comment by nodiaque** [comment] 2023-03-18 01:45
I'm using docker cr.hotio.dev/hotio/bazarr since it was the one in trash guide. Seemed to be the samething as the other bazarr in unraid

**Comment by nodiaque** [comment] 2023-03-18 01:49
So since I switched to ffprobe, it's working fine. Reason why I switch is because there's a lot of

BAZARR ffprobe cannot analyze this video file /media/TV/Gotham/Season 3/S03E06 - Mad City - Follow the White Rabbit.mkv. Could it be corrupted? 

Error, but had same error with mediainfo. Weird is I can open those file no problem, watch them and run mediainfo on them. I also have 777 on each of the file.

Is there a place to say don't analyze specific extension? I saw it tried to scan avi file.

**Comment by dreondre** [comment] 2023-03-18 18:20
I'm facing the same problem. I enabled debug logging. This is around the tail end where it stops and restarts Bazarr

`18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8991|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8991 "GET /api/v3/tag?apikey=(removed) HTTP/1.1" 200 None|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8991|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8991|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8991 "GET /api/v3/series/?apikey=(removed) HTTP/1.1" 200 None|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8991|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8991 "GET /api/v3/episode?seriesId=1&apikey=(removed) HTTP/1.1" 200 None|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |Starting new HTTP connection (1): ***.***.***.***:8991|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8991 "GET /api/v3/episodeFile?seriesId=1&apikey=(removed) HTTP/1.1" 200 None|
18/03/2023 18:13:22|DEBUG   |peewee                          |('SELECT "t1"."ffprobe_cache" FROM "table_episodes" AS "t1" WHERE ("t1"."path" = ?) LIMIT ? OFFSET ?', ['/tv/Chainsaw Man (2022) {imdb-tt13616990}/Season 01/Chainsaw Man (2022) - S01E01 - DOG and CHAINSAW [WEBDL-1080p][AAC 2.0][h265]-APEX.mp4', 1, 0])|
18/03/2023 18:13:22|DEBUG   |root                            |BAZARR returning this binary: /usr/bin/mediainfo|
18/03/2023 18:13:22|DEBUG   |urllib3.connectionpool          |http://***.***.***.***:8991 "GET /api/v3/series/?apikey=(removed) HTTP/1.1" 200 None|
18/03/2023 18:13:22|DEBUG   |peewee                          |('SELECT "t1"."sonarrSeriesId" FROM "table_shows" AS "t1"', [])|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:22|DEBUG   |peewee                          |('SELECT "t1"."title", "t1"."path", "t1"."tvdbId", "t1"."sonarrSeriesId", "t1"."overview", "t1"."poster", "t1"."fanart", "t1"."audio_language", "t1"."sortTitle", "t1"."year", "t1"."alternativeTitles", "t1"."tags", "t1"."seriesType", "t1"."imdbId", "t1"."monitored" FROM "table_shows" AS "t1"', [])|
18/03/2023 18:13:22|DEBUG   |root                            |BAZARR All series synced from Sonarr into database.|
18/03/2023 18:13:22|INFO    |apscheduler.executors.default   |Job "update_series (trigger: date[2023-03-18 18:13:22 UTC], next run at: 2023-03-18 18:13:22 UTC)" executed successfully|
18/03/2023 18:13:22|INFO    |socketio.server                 |emitting event "data" to all [/]|
18/03/2023 18:13:28|DEBUG   |root                            |Bazarr version: 1.2.0|
18/03/2023 18:13:28|DEBUG   |root                            |Bazarr branch: master|
18/03/2023 18:13:28|DEBUG   |root                            |Operating system: Linux-5.14.0-162.18.1.el9_1.x86_64-x86_64-with|
18/03/2023 18:13:28|DEBUG   |root                            |Python version: 3.10.10|
`

Just like @nodiaque, when I revert back to ffprobe, the problem goes away.

**Comment by dreondre** [comment] 2023-03-18 18:29
I tried changing use_ffprobe_cache = False but it made no difference.

**Comment by morpheus65535** [comment] 2023-03-18 18:31
> I tried changing use_ffprobe_cache = False but it made no difference.

That's expected but thanks anyway. I'll try to test mediainfo with hotio and LSIO images ASAP.

**Comment by si458** [comment] 2023-03-18 22:09
I think I'm having a similar issue, I use the linuxserver container (latest image)
spotted my bazarr container wasn't running, restarted docker server, container starts fine but bazarr never actually starts?
I made no config changes what so ever
Any suggestions?

**Comment by morpheus65535** [comment] 2023-03-18 22:32
> I think I'm having a similar issue, I use the linuxserver container (latest image) spotted my bazarr container wasn't running, restarted docker server, container starts fine but bazarr never actually starts? I made no config changes what so ever Any suggestions?

If you haven't changed from ffprobe to mediainfo, you have a different issue. Make sure you didn't change the listening IP address in settings. It must stay 0.0.0.0.

**Comment by si458** [comment] 2023-03-18 22:57
> > I think I'm having a similar issue, I use the linuxserver container (latest image) spotted my bazarr container wasn't running, restarted docker server, container starts fine but bazarr never actually starts? I made no config changes what so ever Any suggestions?
> 
> If you haven't changed from ffprobe to mediainfo, you have a different issue. Make sure you didn't change the listening IP address in settings. It must stay 0.0.0.0.

I think my issue is a bad Internet connection maybe as it sits there after connecting to github the debug logs show? (Logs bk to front sorry stupid portainer)

```
2023-03-18 22:22:31,596 - root                             (7f5c151d9b48) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/ffprobe
2023-03-18 22:22:31,599 - urllib3.connectionpool           (7f5c151d9b48) :  DEBUG (connectionpool:1003) - Starting new HTTPS connection (1): raw.githubusercontent.com:443
2023-03-18 22:22:31,596 - root                             (7f5c151d9b48) :  DEBUG (binaries:47) - BAZARR returning this binary: /usr/bin/ffmpeg
2023-03-18 22:22:31,584 - app.database                     (7f5c151d9b48) :  DEBUG (database:50) - Connecting to SQLite database: /config/db/bazarr.db
2023-03-18 22:22:30,323 - root                             (7f5c151d9b48) :  DEBUG (logger:112) - Python version: 3.10.10
2023-03-18 22:22:30,323 - root                             (7f5c151d9b48) :  DEBUG (logger:111) - Operating system: Linux-5.15.0-1029-kvm-x86_64-with
2023-03-18 22:22:30,319 - root                             (7f5c151d9b48) :  DEBUG (logger:110) - Bazarr branch: master
2023-03-18 22:22:30,319 - root                             (7f5c151d9b48) :  DEBUG (logger:109) - Bazarr version: 1.2.0
[custom-init] No custom files found, skipping...
```

**Comment by morpheus65535** [comment] 2023-03-19 12:36
@si458 please stop squatting this issue and create your own. They are unrelated.

**Comment by morpheus65535** [comment] 2023-03-22 03:16
I've just tried to fix this. Let me know if upcoming beta works as expected.

**Comment by dreondre** [comment] 2023-03-22 09:09
I tried the latest development release of the LinuxServer image (published 2 hours ago) but the problem persists. 
I can try again later in the event another image gets pushed. I can provide more info (e.g. logs) later on if need be.

**Comment by morpheus65535** [comment] 2023-03-22 17:13
@dreondre thanks! I've open an issue with knowit module developer because it seems to be the one causing a segmentation fault that kill the python process that get restarted by Bazarr daemon (parent process).

**Comment by morpheus65535** [comment] 2023-03-22 21:14
Last commit should make it works but it's a temporary fix.

**Comment by morpheus65535** [comment] 2023-03-23 13:03
> I've confirmed it is stable now when mediainfo is set.

Thanks! I'll keep this open until I get news from knowit dev.

**Comment by Kooramah** [comment] 2023-04-18 16:25
I also ran into this loop when changing from ffprobe to mediainfo. I thought its because I changed the number of CPU threads I wanted to use. I thought it was odd that it did that but came here and found this.

I changed from latest to development and I'm no longer experiencing the issue. Thanks

**Comment by jsmdy** [comment] 2023-04-24 08:41
> I think I'm having a similar issue, I use the linuxserver container (latest image) spotted my bazarr container wasn't running, restarted docker server, container starts fine but bazarr never actually starts? I made no config changes what so ever Any suggestions?

same here on a seedbox :/

**Comment by morpheus65535** [comment] 2023-09-15 21:18
I'll close this issue as it related to an external library that I don't manage. I've never got any feed back to my issue so I don't expect this to be fixed soon.

In the meantime, use ffprobe instead of mediainfo.

**Closed by morpheus65535** 2023-09-15 21:18 UTC
Labels: bug, priority:medium, library related
