### ISSUE TITLE
Episodes Not Updating

### ISSUE THREAD

**Issue by clobber88** [morpheus65535/bazarr#1010] opened 2020-06-04 01:17 UTC
**Describe the bug**
Using a complete docker configuration from linuxserver with Radarr/Sonarr/Bazarr. Bazarr seems to be working properly with Radarr/Movies, but not with Sonarr/Tv. The series are imported from Sonarr, but not the episodes.

**To Reproduce**
1. Opening any series shows there are no episodes
2. In System, go to settings and manually force the "Sync Episodes with Sonarr"
3. Opening any series displays no episodes with screen shot attached.

**Expected behavior**
Every series to have episodes

**Screenshots**

Sonarr validation works:
![image](https://user-images.githubusercontent.com/5307590/83703877-a9e68100-a5de-11ea-9001-b81653319ce9.png)

Series exist:
![image](https://user-images.githubusercontent.com/5307590/83703321-34c67c00-a5dd-11ea-8c8a-1a4ecc232ef9.png)

But not episodes:
![image](https://user-images.githubusercontent.com/5307590/83703344-41e36b00-a5dd-11ea-92a4-6dbadc0b395f.png)
[bazarr.log](https://github.com/morpheus65535/bazarr/files/4726886/bazarr.log)

**Software (please complete the following information):**
 - Bazarr: 0.8.4.4
 - Radarr version 0.2.0.1480
 - Sonarr version 2.0.0.5344
 - OS: Ubuntu 16.04 LTS

**Additional context**
In the Bazarr web gui, I do see the pop up progress bars when syncing series and episodes
There is an error in the attached bazarr.log. It mentions an error with seriesId 179, but I do not know what series that is.
I have not configured any paths in Settings->General as I dont quite understand what that does.
There is also possibly a DNS error: DNS: Falling back to default DNS or IP on sonarr

**Comment by morpheus65535** [comment] 2020-06-04 01:36
What is the output from this url: `http://sonarr:8989/api/episode?seriesId=179&apikey=cfd6ea5314554ed88501f90eddfa9f9e`?

**Comment by clobber88** [comment] 2020-06-04 01:41
It is certainly an error. Thats why I was asking how to figure out what seriesId=179 is? Sonarr seems to be working fine.

{
  "message": "database disk image is malformed\ndatabase disk image is malformed",
  "description": "System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed\ndatabase disk image is malformed\n  at System.Data.SQLite.SQLite3.Reset (System.Data.SQLite.SQLiteStatement stmt) [0x00083] in <61a20cde294d4a3eb43b9d9f6284613b>:0 \n  at System.Data.SQLite.SQLite3.Step (System.Data.SQLite.SQLiteStatement stmt) [0x0003c] in <61a20cde294d4a3eb43b9d9f6284613b>:0 \n  at System.Data.SQLite.SQLiteDataReader.Read () [0x00043] in <61a20cde294d4a3eb43b9d9f6284613b>:0 \n  at Marr.Data.DataMapper.Query[T] (System.String sql, System.Collections.Generic.ICollection`1[T] entityList, System.Boolean useAltName) [0x000a2] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\Marr.Data\\DataMapper.cs:569 \n  at Marr.Data.QGen.QueryBuilder`1[T].ToList () [0x00052] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\Marr.Data\\QGen\\QueryBuilder.cs:279 \n  at Marr.Data.QGen.SortBuilder`1[T].ToList () [0x00000] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\Marr.Data\\QGen\\SortBuilder.cs:176 \n  at NzbDrone.Core.Tv.EpisodeRepository.GetEpisodes (System.Int32 seriesId) [0x0000d] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Core\\Tv\\EpisodeRepository.cs:81 \n  at NzbDrone.Core.Tv.EpisodeService.GetEpisodeBySeries (System.Int32 seriesId) [0x00000] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Core\\Tv\\EpisodeService.cs:98 \n  at NzbDrone.Api.Episodes.EpisodeModule.GetEpisodes () [0x001d0] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Api\\Episodes\\EpisodeModule.cs:30 \n  at NzbDrone.Api.REST.RestModule`1[TResource].<set_GetResourceAll>b__32_0 (System.Object options) [0x00000] in C:\\BuildAgent\\work\\5d7581516c0ee5b3\\src\\NzbDrone.Api\\REST\\RestModule.cs:111 \n  at (wrapper dynamic-method) System.Object.CallSite.Target(System.Runtime.CompilerServices.Closure,System.Runtime.CompilerServices.CallSite,System.Func`2<object, object>,object)\n  at Nancy.Routing.Route+<>c__DisplayClass4.<Wrap>b__3 (System.Object parameters, System.Threading.CancellationToken context) [0x00049] in <63c44d6f8d7e4f339a987bf9eb94d931>:0 "
}

**Comment by morpheus65535** [comment] 2020-06-04 01:47
Could it be duplicate of #1007?

**Closed** 2020-06-05 00:33 UTC
