### ISSUE TITLE
Provider 'Subscene' not working

### ISSUE THREAD

**Issue by mrnutsen** [morpheus65535/bazarr#1260] opened 2021-02-05 20:21 UTC
Getting this when using subscene as provider. captcha provider is ok and tested. username and password for subscene newly updated but to no resolve.

ERROR: 
Not using subscene until 21/02/05 21:22, because of: TypeError

Message:
Unexpected error in provider 'subscene': Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 152, in initialize    self.login()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 155, in login    r = self.session.get("https://subscene.com/account/login")  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 229, in get    return self.retry_method("get", *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 217, in retry_method    return retry_call(getattr(super(RetryingSession, self), method), fargs=args, fkwargs=kwargs, tries=3, delay=5,  File "/opt/bazarr/bazarr/../libs/retry/api.py", line 101, in retry_call    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)  File "/opt/bazarr/bazarr/../libs/retry/api.py", line 33, in __retry_internal    return f()  File "/opt/bazarr/bazarr/../libs/requests/sessions.py", line 546, in get    return self.request('GET', url, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 60, in request    return super(TimeoutSession, self).request(method, url, *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 165, in request    ret = self._request(method, url, *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 103, in _request    resp = self.sendChallengeResponse(resp, **kwargs)  File "/opt/bazarr/bazarr/../libs/cloudscraper/__init__.py", line 187, in sendChallengeResponse    sleep(self.delay)TypeError: an integer is required (got type NoneType)

Exception:
Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 170, in list_subtitles_provider    results = self[provider].list_subtitles(video, provider_languages)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/core.py", line 105, in __getitem__    provider.initialize()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 152, in initialize    self.login()  File "/opt/bazarr/bazarr/../libs/subliminal_patch/providers/subscene.py", line 155, in login    r = self.session.get("https://subscene.com/account/login")  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 229, in get    return self.retry_method("get", *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 217, in retry_method    return retry_call(getattr(super(RetryingSession, self), method), fargs=args, fkwargs=kwargs, tries=3, delay=5,  File "/opt/bazarr/bazarr/../libs/retry/api.py", line 101, in retry_call    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)  File "/opt/bazarr/bazarr/../libs/retry/api.py", line 33, in __retry_internal    return f()  File "/opt/bazarr/bazarr/../libs/requests/sessions.py", line 546, in get    return self.request(GET, url, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 60, in request    return super(TimeoutSession, self).request(method, url, *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 165, in request    ret = self._request(method, url, *args, **kwargs)  File "/opt/bazarr/bazarr/../libs/subliminal_patch/http.py", line 103, in _request    resp = self.sendChallengeResponse(resp, **kwargs)  File "/opt/bazarr/bazarr/../libs/cloudscraper/__init__.py", line 187, in sendChallengeResponse    sleep(self.delay)TypeError: an integer is required (got type NoneType)

**Comment by morpheus65535** [comment] 2021-02-05 20:23
Duplicate of #1230

**Closed by morpheus65535** 2021-02-05 20:23 UTC
