### ISSUE TITLE
Not searching Latin spanish subtitles in Opensubtitles.com

### ISSUE THREAD

**Issue by Iban2222** [morpheus65535/bazarr#2720] opened 2024-10-15 17:27 UTC
**Describe the bug**
When I try to search for a subtitle in Latin Spanish through Opensubtitles.com it only searches for "es" and not "ea" so there are subtitles that never appear.

I tried in the anime show "I Parry Everything" (imdb_id 32395862)
**To Reproduce**
1. Add new language profile with Spanish (Latino)
2. Use it to search
3. See the log for know how it search

**Expected behavior**
Use ea language when search in opensubtitles.com in "spanish (Latino)"

**Screenshots**
screenshot of bazarr.log
![imagen](https://github.com/user-attachments/assets/e91e4c75-2e46-4576-b89c-cce83bb156f4)

screenshot of bazarr language configuration
![imagen](https://github.com/user-attachments/assets/dc695763-722e-41ae-bcc3-83a5ae650beb)

If i try using the official api with the ea language it works fine
![imagen](https://github.com/user-attachments/assets/af726a7d-45aa-41a2-a98f-6749732b6bf4)

**Software (please complete the following information):**
 - Bazarr:  1.4.5
 - Sonarr version  4.0.9.2244
 - OS: Windows 11

**Additional context**
My English is not good and I had to use Google translate for some things, sorry if something is not explained well.

**Comment by hnorgaar** [comment] 2024-10-17 03:45
Also check you are not using "EQUAL" in settings-Language

**Comment by morpheus65535** [comment] 2024-10-21 03:26
Should be fixed in upcoming beta. Let me know if not. Thanks for reporting!

**Closed by morpheus65535** 2024-10-21 03:26 UTC

**Comment by amunocis** [comment] 2025-05-19 01:30
it seems like this problem is still in. I can't download subtitles from opensubtitles, sadly

**Comment by morpheus65535** [comment] 2025-05-19 23:33
> it seems like this problem is still in. I can't download subtitles from opensubtitles, sadly

I've just tested out succesfully:

![Image](https://github.com/user-attachments/assets/e1387381-f141-441d-8990-d739dd084d47)

**Comment by amunocis** [comment] 2025-05-20 01:16
> > it seems like this problem is still in. I can't download subtitles from opensubtitles, sadly
> 
> I've just tested out succesfully:
> 
> ![Image](https://github.com/user-attachments/assets/e1387381-f141-441d-8990-d739dd084d47)

that's nice, but I have more than 600 subtitles with error, and I'm not the only one :(

**Comment by morpheus65535** [comment] 2025-05-20 01:25
> that's nice, but I have more than 600 subtitles with error, and I'm not the only one :(

And how do you expect me to fix the issue if you don't provide any debug log or even a single test case?

**Comment by amunocis** [comment] 2025-05-22 02:49
ok, I think this could help you. I asked Gemini to filter some relevants logs about this issue. If you need anything else, let me know:
`--- Relevant Bazarr Log Snippets for GitHub Issue ---

**Bazarr Version (from log startup):**
2025-05-18 20:55:39|DEBUG   |root                            |Bazarr version: 1.5.3-beta.1|
2025-05-18 20:55:39|DEBUG   |root                            |Bazarr branch: development|
2025-05-18 20:55:39|DEBUG   |root                            |Python version: 3.12.10|

--- Start of Manual Search for a Specific Episode (e.g., Game of Thrones S01E10) ---

**1. Manual Search Initiated & Video Information:**
2025-05-18 21:01:09|DEBUG   |root                            |BAZARR Manually searching subtitles for this file: /data/media/series/Game of Thrones/Season 1/Game of Thrones - S01E10 - Fire and Blood WEBRip-1080p.mkv|
2025-05-18 21:01:09|DEBUG   |root                            |BAZARR is using these video object properties: {
    "name": "/data/media/series/Game of Thrones/Season 1/Game of Thrones - S01E10 - Fire and Blood WEBRip-1080p.mkv",
    "source": "Web",
    "series": "Game of Thrones",
    "season": 1,
    "episode": 10,
    "title": "Fire and Blood",
    "year": 2011,
    "series_imdb_id": "tt0944947",
    "hashes": {
        "opensubtitlescom": "4cbab2d6d54c90c4" 
    },
    "fps": "23.976"
}| 
[... other properties omitted for brevity]

**2. Languages Requested by Bazarr (Internal):**
2025-05-18 21:01:09|DEBUG   |subliminal_patch.core           |Languages requested: {<Language: alpha3=spa;country=MX>, <Language: hi=True;alpha3=spa;country=MX>}| 
[Note: hi=True indicates a hearing-impaired variant, but the core issue is with spa;country=MX]

**3. Initial API Call to OpenSubtitles.com (results in Rate Limit, then successful login):**
2025-05-18 21:01:09|DEBUG   |urllib3.connectionpool          |Starting new HTTPS connection (1): api.opensubtitles.com:443|
2025-05-18 21:01:10|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "POST /api/v1/login HTTP/11" 429 41|
2025-05-18 21:01:10|DEBUG   |subliminal_patch.providers.opensubtitlescom|Response Body: {"message": "API rate limit exceeded"}|
2025-05-18 21:01:10|INFO    |root                            |Provider opensubtitlescom throttle count 1 of 5, waiting 5sec and trying again|
[... Bazarr waits and retries ...]
2025-05-18 21:01:28|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "POST /api/v1/login HTTP/11" 200 350|
2025-05-18 21:01:28|DEBUG   |subliminal_patch.providers.opensubtitlescom|Response Body: {"user": {...}, "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9...", "status": 200, ...}| 
[Login to OpenSubtitles.com successful after retry]

**4. Subsequent API Call to OpenSubtitles.com for Subtitles (PROBLEM HERE):**
   (Using Game of Thrones S01E02 as an example, as S01E10 was the first after login and might be slightly different due to the throttle handling, but the issue is consistent)
2025-05-18 21:01:28|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitlescom' and languages {<Language: alpha3=spa;country=MX>, <Language: hi=True;alpha3=spa;country=MX>}|
2025-05-18 21:01:28|DEBUG   |subliminal_patch.providers.opensubtitlescom|Searching using this hash: a7ee01af74eed2a1|
2025-05-18 21:01:28|DEBUG   |subliminal_patch.providers.opensubtitlescom|Searching for those languages: ea| 
[THIS IS THE KEY LINE - it's searching for 'ea' instead of a proper Spanish Latino code]
2025-05-18 21:01:29|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "GET /api/v1/subtitles?episode_number=2&imdb_id=944947&languages=ea&moviehash=a7ee01af74eed2a1&season_number=1 HTTP/11" 200 66|
[Actual API call showing languages=ea]

**5. Result from OpenSubtitles.com and Bazarr's Conclusion:**
2025-05-18 21:01:29|DEBUG   |subliminal_patch.providers.opensubtitlescom|Query returned 0 subtitles|
2025-05-18 21:02:29|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
2025-05-18 21:02:29|DEBUG   |root                            |BAZARR No Subtitles were found for this file: /data/media/series/Game of Thrones/Season 1/Game of Thrones - S01E02 - The Kingsroad WEBRip-1080p.mkv|

--- This pattern repeats for other episodes ---

**Example: Game of Thrones S03E01:**
2025-05-18 21:01:51|DEBUG   |subliminal_patch.core           |Languages requested: {<Language: alpha3=spa;country=MX>}|
2025-05-18 21:01:51|INFO    |subliminal_patch.core           |Listing subtitles with provider 'opensubtitlescom' and languages {<Language: alpha3=spa;country=MX>}|
2025-05-18 21:01:51|DEBUG   |subliminal_patch.providers.opensubtitlescom|Searching using this hash: b4051372ff89f540|
2025-05-18 21:01:51|DEBUG   |subliminal_patch.providers.opensubtitlescom|Searching for those languages: ea|
2025-05-18 21:01:52|DEBUG   |urllib3.connectionpool          |https://api.opensubtitles.com:443 "GET /api/v1/subtitles?episode_number=1&imdb_id=944947&languages=ea&moviehash=b4051372ff89f540&season_number=3 HTTP/11" 200 None|
2025-05-18 21:01:52|DEBUG   |subliminal_patch.providers.opensubtitlescom|Query returned 0 subtitles|
2025-05-18 21:01:52|INFO    |subliminal_patch.core_persistent|Downloaded 0 subtitle(s)|
2025-05-18 21:01:52|DEBUG   |root                            |BAZARR No Subtitles were found for this file: /data/media/series/Game of Thrones/Season 3/Game of Thrones - S03E01 - Valar Dohaeris WEBRip-1080p.mkv|

--- End of Relevant Log Snippets ---`

**Comment by morpheus65535** [comment] 2025-05-22 03:06
@amunocis the issue reside on os.com side: we use imdb id to search for series or movies but the one provided by Sonarr for Game of Thrones (tt0944947) cannot be found on os.com. You could search for an English subtitles and you wouldn't find it either.

![Image](https://github.com/user-attachments/assets/2152fcac-d060-4bba-8395-c74bd8863bc0)

![Image](https://github.com/user-attachments/assets/4277a35d-1576-40f1-8c03-716e5db6b1b5)

**Comment by amunocis** [comment] 2025-05-22 16:39
Ok, with that info you showed before, I tried to download 52 movies. Got VIP on opensubtitles and started. It was unable to find any subtitle. The message is always: DEBUG |subliminal_patch.providers.opensubtitlescom|Query returned 0 subtitles

Not sure if I can drop a big (filtered) log, but here it is

[bazarr.log](https://github.com/user-attachments/files/20396722/bazarr.log)
