### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by joulester** [morpheus65535/bazarr#917] opened 2020-04-09 15:31 UTC
I Run bazarr in an lxc under proxmox. it uses 100% and i´m guessing that is not a normal behaviour.
It is installed from source under debain 10. 

Bazarr Version: 0.8.4.2
Sonarr Version: 2.0.0.5344
Radarr Version: 0.2.0.1480
Operating System: Linux-5.3.18-2-pve-x86_64-with-debian-10.3
Python Version: 3.7.3
Bazarr Directory: /home/bazarr
Bazarr Config Directory: /home/bazarr/data

settings:

Update Series list from Sonarr | every 60 seconds
Sync episodes with Sonarr | every 5 minutes 
Update Movie list from Radarr | every 5 minutes 
Cache maintenance | every 24 hours 
Update Bazarr from source on Github | every 6 hours 
Search for wanted Subtitles | every 12 hours 
Update all Episode Subtitles from disk | everyday at 4:00
Update all Movie Subtitles from disk | everyday at 5:00 

![bazarr](https://user-images.githubusercontent.com/19240362/78911487-a6bf9080-7a86-11ea-9852-0282d1879362.PNG)

[bazarr.txt](https://github.com/morpheus65535/bazarr/files/4457100/bazarr.txt)

**Comment by morpheus65535** [comment] 2020-04-09 15:40
Your log file is flooded with connection error to providers and ioerror when trying to access media files. Fix your network and volume for your container. BTW, I've never used lxc. Why not simply use docker? We have pretty good images.

**Comment by morpheus65535** [comment] 2020-04-11 13:03
I'll close this one as I cannot reproduce your issue. Feel free to come to Discord support channel as there's maybe other users in your position.

**Closed by morpheus65535** 2020-04-11 13:03 UTC

**Comment by joulester** [comment] 2020-04-12 11:56
Hi! I will try again with the debug enabled this time and the issue happens at 12:33.
I hope you see something i missed!

[bazarr.txt](https://github.com/morpheus65535/bazarr/files/4466260/bazarr.txt)

**Comment by morpheus65535** [comment] 2020-04-12 12:30
Looks like `/home/bazarr/bin/Linux/x86_64/ffprobe/ffprobe` is having a hard time trying to analyze your AVI files. Also, most of your providers are throttled. 

Also, next time you provide a debug log, please make sure that it cover only the period while you reproduce the issue. You've got a 90 000 lines log and I won't be reading it line by line...

**Comment by joulester** [comment] 2020-04-12 22:11
and I still removed 90% of it. Any tips on the throttling? The avi files I will remove from Bazarr

**Comment by morpheus65535** [comment] 2020-04-13 00:13
I can say why it's getting throttled once it is done, only when it happen.
