### ISSUE TITLE
Bazarr does not restart successfully upon applying update

### ISSUE THREAD

**Issue by cheng2wei** [morpheus65535/bazarr#2456] opened 2024-04-16 04:31 UTC
**Describe the bug**
Development build will not restart when applying update.

**To Reproduce**
1. Release new update
2. Auto-install update
3. During restart, restart file is not created
4. bazarr stays down as a result

**Expected behavior**
Bazarr should restart after applying the update.

**Logs**
```
2024-04-10 02:30:03|DEBUG   |root                            |BAZARR new release have been installed, now we restart|
2024-04-10 02:30:03|ERROR   |root                            |BAZARR Cannot create restart file: KeyError('RESTARTFILE')|
2024-04-10 02:30:03|INFO    |root                            |Bazarr is being restarted...|
2024-04-10 02:30:03|ERROR   |apscheduler.executors.default   |Job "Update Bazarr (trigger: interval[6:00:00], next run at: 2024-04-10 08:30:01 PDT)" raised an exception|Traceback (most recent call last):  File "/opt/bazarr/bazarr/../libs/apscheduler/executors/base.py", line 125, in run_job    retval = job.func(*job.args, **job.kwargs)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/opt/bazarr/bazarr/app/check_update.py", line 105, in check_if_new_update    download_release(url=release['download_link'])  File "/opt/bazarr/bazarr/app/check_update.py", line 136, in download_release    apply_update()  File "/opt/bazarr/bazarr/app/check_update.py", line 192, in apply_update    webserver.restart()  File "/opt/bazarr/bazarr/app/server.py", line 97, in restart  File "/opt/bazarr/bazarr/utilities/central.py", line 48, in restart_bazarr    raise SystemExit(EXIT_NORMAL)SystemExit: 0|
2024-04-10 02:30:03|INFO    |socketio.server                 |emitting event "data" to all [/]
```

**Software (please complete the following information):**
 - Bazarr: [e.g. v 0.6.1] [v1.4.3-beta.17](https://github.com/morpheus65535/bazarr/releases/tag/v1.4.3-beta.17)
 - Radarr version [e.g. v 0.2.0.0001]: N/A
 - Sonarr version [e.g. v 2.0.0.0001]: N/A
 - OS: [e.g. Windows 10]: Debian

**Additional context**

**Comment by morpheus65535** [comment] 2024-04-19 02:35
Should be fixed in upcoming release. Let me know if it works properly after being updated to beta.21.

**Comment by cheng2wei** [comment] 2024-04-19 21:52
@morpheus65535 I'll have to update to beta.21 and wait until beta.22 to properly verify this, right?

**Comment by morpheus65535** [comment] 2024-04-19 21:54
Yes but it will be released tonight.

**Comment by flensburg2** [comment] 2024-04-20 07:53
I am on beta 22 right now, but it was not starting by itself. Got the error message below.
Actually, I have had this problem for quite many beta releases now, where I notice the bazarr service is not working sometimes, and I have to manually restart it by killing the nssm process and starting again. Just recently I am starting to relate it to new releases and the updating process.
2024-04-20 09:08:45|ERROR   |root                            |BAZARR Cannot create restart file: KeyError('RESTARTFILE')|

**Comment by morpheus65535** [comment] 2024-04-20 12:02
@flensburg2 can you check if bazarr.py contain those lines? https://github.com/morpheus65535/bazarr/blob/development/bazarr.py#L122-L125

**Comment by flensburg2** [comment] 2024-04-20 12:41
I can confirm I find the same lines 122-125 in my bazarr.py file

**Comment by cheng2wei** [comment] 2024-04-20 14:23
Still having the same issue going from .21 to .22.

I'm not too familiar with bazarr source or its upgrade flow, but does a new process get created during upgrades? Would that be why there is no os.environ value for RESTARTFILE?

**Comment by morpheus65535** [comment] 2024-04-20 14:51
Previously we weren't defining environment variables in bazarr.py which is only a daemon process. It start a subprocess (main.py) and this one may not be getting parent process environment variables. My latest fix should address that (I hope...).

**Comment by flensburg2** [comment] 2024-04-21 08:07
Looks like the update from beta 22 to beta 23 went fine here. Bazarr process was running after the update.

**Comment by morpheus65535** [comment] 2024-04-21 12:40
> Looks like the update from beta 22 to beta 23 went fine here. Bazarr process was running after the update.

Keep me informed on how goes subsequent upgrades.

**Comment by flensburg2** [comment] 2024-04-23 06:19
Automatic update and restart went fine from beta 23 to beta 24 as well.

**Comment by morpheus65535** [comment] 2024-04-23 10:21
@cheng2wei is it fixed for you?

**Comment by cheng2wei** [comment] 2024-04-23 14:07
Yep, auto update and restart is working. On beta 24 now.

**Closed** 2024-04-23 18:36 UTC
Labels: bug, priority:high, awaiting feedback, fixed
