### ISSUE TITLE
Won't start if radarr or sonarr hostnames are unreachable during startup

### ISSUE THREAD

**Issue by pabloromeo** [morpheus65535/bazarr#1519] opened 2021-08-28 14:09 UTC
**Describe the bug**
If the hostnames configured for either radarr or sonarr are not resolvable while Bazarr is starting up, the app never starts the web listener, and just continues to attempt to reconnect to radarr/sonarr.

**To Reproduce**
1. Go to either the Sonarr or Radarr config for a properly configured App and just change the hostname to an invalid one
2. Restart Bazarr
3. It won't initialize the web frontend
4. You can fix it by manually editing config.ini and reverting the hostname change or just turning off the Sonarr/Radarr "enabled" setting.

**Expected behavior**
Bazarr should still start the frontend.

**Logs**
    
    2021-08-28 10:50:05,619 - root                             (b2b18688) :  INFO (signalr_client:41) - BAZARR trying to connect to Sonarr SignalR feed...
    
    2021-08-28 10:50:05,636 - root                             (b2b18e80) :  INFO (signalr_client:105) - BAZARR trying to connect to Radarr SignalR feed...
    
    2021-08-28 10:50:05,667 - root                             (b27040b0) :  INFO (signalr_client:129) - BAZARR SignalR client for Radarr is connected and waiting for events.
    
    2021-08-28 10:50:10,884 - root                             (b2704358) :  ERROR (get_rootfolder:28) - BAZARR Error trying to get rootfolder from Sonarr. Connection Error.
    
    2021-08-28 10:50:10,967 - root                             (b27043e0) :  ERROR (get_episodes:351) - BAZARR Error trying to get series from Sonarr. Connection Error.
    
    2021-08-28 10:50:10,975 - apscheduler.executors.default    (b27043e0) :  ERROR (base:131) - Job "sync_episodes (trigger: date[2021-08-28 10:50:10 -03], next run at: 2021-08-28 10:50:10 -03)" raised an exception
    
    2021-08-28 10:50:10,992 - root                             (b2704358) :  ERROR (get_series:220) - BAZARR Error trying to get profiles from Sonarr. Connection Error.
    
    2021-08-28 10:50:11,011 - root                             (b2704358) :  ERROR (get_series:261) - BAZARR Error trying to get tags from Sonarr. Connection Error.
    
    2021-08-28 10:50:11,029 - root                             (b2704358) :  ERROR (get_series:344) - BAZARR Error trying to get series from Sonarr. Connection Error.
    
    2021-08-28 10:50:16,219 - root                             (b15594f0) :  ERROR (get_episodes:351) - BAZARR Error trying to get series from Sonarr. Connection Error.
    
    2021-08-28 10:50:16,238 - apscheduler.executors.default    (b15594f0) :  ERROR (base:131) - Job "sync_episodes (trigger: date[2021-08-28 10:50:15 -03], next run at: 2021-08-28 10:50:15 -03)" raised an exception
    

**Software (please complete the following information):**
 - Bazarr: v0.9.7
 - Radarr version: 3.0.6.1265
 - Sonarr version: 3.2.2.5080
 - OS: Linux-5.10.52-v7l+-armv7l-with (Docker Swarm running ghcr.io/linuxserver/bazarr)

**Additional context**
This is probably not a common scenario for most users as Sonarr/Radarr will be reachable and available.
In my case I randomly notice the issue, since every once in a while Docker Swarm fails to update local DNS entries for newly created services. And those are the cases where Bazarr can't reach Sonarr/Radarr, until the unregistered service is restarted.

**Comment by morpheus65535** [comment] 2021-08-28 14:11
Duplicate of #1506

**Closed by morpheus65535** 2021-08-28 14:11 UTC
