### ISSUE TITLE
legendasdivx can't find subtitles

### ISSUE THREAD

**Issue by n0pe0n** [morpheus65535/bazarr#1104] opened 2020-09-11 22:39 UTC
Describe the bug
When searching for subtitles with the provider "legendasdivx", he cannot find subtitles for the movie or series i am looking for. I checked the website itself and the subtitles are available in the movie and in the series.

See debuglog file.
[Bazarr.log](https://pastebin.com/nYD2NU87)

To Reproduce

Search for subtitles for movie/series
Expected behavior
Expect to find the subtitles listed on the site.

Screenshots

Software (please complete the following information):

Bazarr Version: 0.9.0.3
Sonarr Version: 3.0.3.913
Radarr Version: 0.2.0.1504
Operating System: Linux-4.15.0-117-generic-x86_64-with (ubuntu 16.04)
Python Version: 3.8.5

**Comment by morpheus65535** [comment] 2020-09-14 10:52
I have no way of creating an account on LegendasDivx so I cannot confirm if I can reproduce the issue. There's nothing wrong in your debug log.

@GermanG can you take a look?

**Comment by luiscamalmeida** [comment] 2020-09-14 13:45
Hi,

Same problem. I've got this in the logs.

Throttling legendasdivx for 10 minutes, until 20/09/14 14:49, because of: KeyError. Exception info: 'season'.

**Comment by GermanG** [comment] 2020-09-14 19:34
Just a quick try with  "Devs S01E01" and got both pt and pt-br. I'm going to take a look at the reported logs.

**Comment by GermanG** [comment] 2020-09-14 19:46
Well, the issue reported by @n0pe0n is right, but there's no error in the logs, simply the search
```
https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=search&query=%5CZoey%5Cs+Extraordinary+Playlist+S01%5C
```
Has an empty result page.
On the other hand a simpler search like "Zoey" 
```
https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=search&query=%5CZoey
```
Gets results.

**Comment by n0pe0n** [comment] 2020-09-14 21:08
@GermanG right now I can't put the log here, but I tried it on lovecraft episode 5 and can't find anything on the provider "legendasdivx"
tomorrow I'll put the log for you to see, okay?

**Comment by n0pe0n** [comment] 2020-09-14 21:10
![Screenshot_20200914_221000_com android chrome](https://user-images.githubusercontent.com/69114477/93138559-1b05fc00-f6d7-11ea-84d4-0b17b145ed2c.jpg)

**Comment by luiscamalmeida** [comment] 2020-09-14 21:24
I belive the problem is with the specials. They got a season number of 0 and after removing those everything seems to be working as expected.

[logs.txt](https://github.com/morpheus65535/bazarr/files/5221049/logs.txt)

![image](https://user-images.githubusercontent.com/22885224/93137483-6e774a80-f6d5-11ea-82a4-f83d82734f6f.png)

**Comment by luiscamalmeida** [comment] 2020-09-14 21:29
@n0pe0n Can't it be that bazarr won't download the sub because it has no score?

![image](https://user-images.githubusercontent.com/22885224/93140022-a84a5000-f6d9-11ea-9177-1ff61627ed91.png)

**Comment by n0pe0n** [comment] 2020-09-14 21:36
@luiscamalmeida that may be it, but when doing manual search should at least appear correct?  and that’s not what you’re doing.

**Comment by n0pe0n** [comment] 2020-09-14 21:46
[bazarr.log](https://github.com/morpheus65535/bazarr/files/5221201/bazarr.log)
see this log, it was taken now, and again unsuccessfully does not find anything in legendasdivx :(

**Comment by morpheus65535** [comment] 2020-09-16 02:15
I've just tested and I can't reproduce:
![image](https://user-images.githubusercontent.com/5130500/93284361-85cf3a00-f7a0-11ea-98c4-4ad7b771a619.png)

I don't have this series but I've tested with a movie and a series and they both work perfectly fine.

BTW I was using @n0pe0n username and password. Coudl it be related to blocked IP address? @GermanG any idea?

**Comment by n0pe0n** [comment] 2020-09-16 17:33
[bazarr_2.log](https://github.com/morpheus65535/bazarr/files/5233878/bazarr_2.log)
new log, now search but only with subtitles in PT and not in PT-BR.. and the provider exists in 2 languages, pt and pt-br.
@GermanG any idea?

**Comment by n0pe0n** [comment] 2020-09-16 17:54
another movie i'm not finding all the subtitles you have on legendasdivx ..
vou deixar em 2 imagens... 

![Sem Título](https://user-images.githubusercontent.com/69114477/93374029-131c9800-f84e-11ea-8213-1d43027fc327.png)

![1](https://user-images.githubusercontent.com/69114477/93374052-19ab0f80-f84e-11ea-9d3a-d6e7ab6f8343.png)

**Comment by GermanG** [comment] 2020-09-17 16:42
In the case of the "not  found" issue it seems to be the quote(quote(querytext)) Asi
I replaced 
```
         if isinstance(video, Episode):
             querytext = '"{} S{:02d}E{:02d}"'.format(video.series, video.season, video.episode)
             querytext = quote(quote(querytext))
```
with 
```
         if isinstance(video, Episode):
             querytext = '{} S{:02d}E{:02d}'.format(video.series, video.season, video.episode)
             # querytext = quote(quote(querytext))
```
And now on Zoey's case finds subtitles... but I ended with two issues the score in not good enough or it cannot find the download link!
```
2020-09-17 18:36:34,537 - subliminal_patch.providers.legendasdivx (7effcb7fe640) :  DEBUG (legendasdivx:358) - Legendasdivx.pt :: Found 2 subtitles
2020-09-17 18:36:34,540 - subliminal_patch.providers.legendasdivx (7effcb7fe640) :  DEBUG (legendasdivx:265) - Legendasdivx.pt :: Found subtitle link on: https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=316290 
2020-09-17 18:36:34,540 - subliminal_patch.providers.legendasdivx (7effcb7fe640) :  DEBUG (legendasdivx:265) - Legendasdivx.pt :: Found subtitle link on: https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=308096 
2020-09-17 18:36:34,541 - subliminal_patch.core            (7effe9ffb640) :  DEBUG (core:367) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=316290' [pt-BR:None]>: Found matches {'series', 'episode', 'season'}
2020-09-17 18:36:34,541 - subliminal_patch.score           (7effe9ffb640) :  INFO (score:52) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=316290' [pt-BR:None]>: Computing score for video <Episode ["Zoey's Extraordinary Playlist", 1x1]> with {'hearing_impaired': False}
2020-09-17 18:36:34,541 - subliminal_patch.score           (7effe9ffb640) :  DEBUG (score:122) - Matched hearing_impaired
2020-09-17 18:36:34,541 - subliminal_patch.score           (7effe9ffb640) :  INFO (score:128) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=316290' [pt-BR:None]>: Computed score 241 with final matches {'series', 'hearing_impaired', 'episode', 'season'}
2020-09-17 18:36:34,541 - subliminal_patch.core            (7effe9ffb640) :  DEBUG (core:367) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=308096' [pt-BR:None]>: Found matches {'series', 'resolution', 'episode', 'season'}
2020-09-17 18:36:34,542 - subliminal_patch.score           (7effe9ffb640) :  INFO (score:52) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=308096' [pt-BR:None]>: Computing score for video <Episode ["Zoey's Extraordinary Playlist", 1x1]> with {'hearing_impaired': False}
2020-09-17 18:36:34,542 - subliminal_patch.score           (7effe9ffb640) :  DEBUG (score:122) - Matched hearing_impaired
2020-09-17 18:36:34,542 - subliminal_patch.score           (7effe9ffb640) :  INFO (score:128) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=308096' [pt-BR:None]>: Computed score 243 with final matches {'series', 'resolution', 'episode', 'season', 'hearing_impaired'}
2020-09-17 18:36:34,542 - subliminal_patch.core            (7effe9ffb640) :  INFO (core:380) - <LegendasdivxSubtitle 'https://www.legendasdivx.pt/modules.php?name=Downloads&d_op=getit&cat=vvpukk&lid=308096' [pt-BR:None]>: Score 243 is below min_score (324)
2020-09-17 18:36:34,542 - subliminal_patch.core            (7effe9ffb640) :  INFO (core:800) - Downloaded 0 subtitle(s)
```
```
2020-09-17 18:37:22,593 - urllib3.connectionpool           (7effcb7fe640) :  DEBUG (connectionpool:394) - https://www.legendasdivx.pt:443 "GET /modules.php?name=Downloads&file=jz&d_op=search&op=_jz00&query=Zoey's%20Extraordinary%20Playlist%20S01E01&form_cat=28 HTTP/1.1" 200 7354
2020-09-17 18:37:22,615 - subliminal_patch.providers.legendasdivx (7effcb7fe640) :  DEBUG (legendasdivx:358) - Legendasdivx.pt :: Found 1 subtitles
2020-09-17 18:37:22,617 - subliminal_patch.providers.legendasdivx (7effcb7fe640) :  DEBUG (legendasdivx:267) - Legendasdivx.pt :: Couldn't find download link. Trying next...
```
Still trying to figure this out.

**Comment by n0pe0n** [comment] 2020-09-17 17:05
@GermanG, ok thanks for the help mate

**Comment by n0pe0n** [comment] 2020-09-17 19:07
@GermanG see this log, a caption entered on legendasdvix 33 minutes ago, but in the bazarr it still says nothing found... :(

[bazarr (1).log](https://github.com/morpheus65535/bazarr/files/5241340/bazarr.1.log)

![Sem Título](https://user-images.githubusercontent.com/69114477/93516077-69a6d680-f921-11ea-8c15-db0e1f7e8845.png)
![1](https://user-images.githubusercontent.com/69114477/93516086-6e6b8a80-f921-11ea-9a92-3efdc2737851.png)

**Comment by n0pe0n** [comment] 2020-10-02 18:06
@GermanG , another log to see what's wrong with the provider.
There is a PT-PT sub-language in the provider and it does not download or find in the manual search.

[bazarr.log](https://github.com/morpheus65535/bazarr/files/5319572/bazarr.log)


![ld](https://user-images.githubusercontent.com/69114477/94955080-f1740f80-04e1-11eb-9392-56c74c1b6936.png)

![Sem Título](https://user-images.githubusercontent.com/69114477/94955225-25e7cb80-04e2-11eb-8caa-b3d9eeed49a9.png)

**Comment by morpheus65535** [comment] 2020-10-06 13:04
I've just pushed a fix to dev branch that prevent PT from being prioritized when multiple languages are requested. Now, we search for languages one after the other and append the results before returning the subtitles.

Can you test it and report your results? Thanks!

**Comment by morpheus65535** [comment] 2020-10-07 21:34
Confirm as being fixed by OP.

**Closed by morpheus65535** 2020-10-07 21:34 UTC
Labels: awaiting feedback
