### ISSUE TITLE
development: Bazarr doesn't commit to history after searching subs

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [morpheus65535/bazarr#545] opened 2019-09-15 16:27 UTC
**Describe the bug**
When searching for subs, Bazarr does not add to the history, which causes history to be blank, and notifications not to fire.

**To Reproduce**
1. Search for subs

**Expected behavior**
For history to be filled, and notifications to fire

**Screenshots**
n/a

**Software (please complete the following information):**
 - Bazarr: development

**Additional context**
```
IntegrityError: NOT NULL constraint failed: table_history_movie.id
```

**Comment by morpheus65535** [comment] 2019-09-15 17:56
You have reinstalled Radarr or started from scratch. Radarr have reassigned the previously used ID to other movies and Bazarr don't want to overwrite them. Either you delete your bazarr.db or, at least, empty the `table_movies` and `table_history_movie` tables.

**Comment by morpheus65535** [comment] 2019-09-15 18:28
My bad, I miss read the NOT NULL constraint part.

**Comment by morpheus65535** [comment] 2019-09-15 18:35
It works for me. Movie is added, desired language added, missing subtitles searched for and downloaded. It also appear in history.

**Comment by morpheus65535** [comment] 2019-09-17 10:48
As discussed, I cannot reproduce it. As we are in communication over Discord, I'll close this one.

**Closed by morpheus65535** 2019-09-17 10:48 UTC
